# -*- mode: ruby -*-
# vi: set ft=ruby :
#
# Copyright (C) 2016  Michael Tesch
#
# You may distribute under the terms of either the GNU General Public
# License or the Apache License, as specified in the LICENSE file.
#
# For more information, see the LICENSE file.
#
def gui?; !ENV.fetch('OVJ_VM_GUI', '').empty?; end
def ncpu; Integer(ENV.fetch('OVJ_VM_NCPU', '1')); end
def mem; Integer(ENV.fetch('OVJ_VM_MEM', "%d" % (ncpu * 1024))); end

Vagrant.configure("2") do |config|
  config.vm.box = "OpenVnmrJ/ubuntu14"
  # only update vbguest on the box_defs/ boxes
  config.vbguest.auto_update = false
  config.vm.provider "virtualbox" do |vb|
    vb.linked_clone = true
    vb.gui = gui?
    vb.memory = mem
    vb.cpus = ncpu
  end
  config.vm.post_up_message = "VM started with #{ncpu} cpus, #{mem} MB memory, and gui=#{gui?}"
  config.vm.provision "shell", inline: <<-SHELL
    set -e
    echo "dash dash/sh boolean false" | debconf-set-selections
    DEBIAN_FRONTEND=noninteractive dpkg-reconfigure dash
    echo "127.0.0.1 $(hostname)" >> /etc/hosts
    echo "do nothing"
  SHELL
end
