/*
 * @(#)dds_cpp_topic.h    generated by: makeheader    Mon Dec  3 23:08:33 2007
 *
 *		built from:	topic.ifcxx
 */

#ifndef dds_cpp_topic_h
#define dds_cpp_topic_h


  #ifndef dds_cpp_infrastructure_h
    #include "dds_cpp/dds_cpp_infrastructure.h"
  #endif
  #ifndef dds_c_topic_h
    #include "dds_c/dds_c_topic.h"
  #endif
  #ifndef dds_cpp_dll_h
    #include "dds_cpp/dds_cpp_dll.h"
  #endif

class DDSTopicDescription_impl;

class DDSDomainParticipant;

class DDSTopic;

class DDSCPPDllExport DDSTopicDescription {
  public: 

    /*i
      @brief Get the underlying implementation class object.	  
     */
    virtual DDSTopicDescription_impl* get_impl_TopicDescriptionI() 
        = 0;

  public: 

    /*e \dref_TopicDescription_get_type_name
     */
    virtual const char* get_type_name() 
        = 0;

    /*e \dref_TopicDescription_get_name
     */
    virtual const char* get_name() 
	    = 0;

    /*e \dref_TopicDescription_get_participant
     */
    virtual DDSDomainParticipant* get_participant() 
	    = 0;
  protected: 
    virtual ~DDSTopicDescription();
};

class DDSCPPDllExport DDSContentFilteredTopic : 
    public DDSTopicDescription 
{
  public: 

    /*e \dref_ContentFilteredTopic_narrow
     */
    static DDSContentFilteredTopic* narrow(
	DDSTopicDescription* topic_description);

    /*e \dref_ContentFilteredTopic_get_filter_expression
     */
    virtual const char* get_filter_expression() 
        = 0; 

    /*e \dref_ContentFilteredTopic_get_expression_parameters
     */
    virtual DDS_ReturnCode_t get_expression_parameters(
        DDS_StringSeq& parameters)
        = 0;

    /*e \dref_ContentFilteredTopic_set_expression_parameters
     */
    virtual DDS_ReturnCode_t set_expression_parameters(
	const DDS_StringSeq& parameters)
        = 0;

    /*e \dref_ContentFilteredTopic_get_related_topic
     */
    virtual DDSTopic* get_related_topic() 
        = 0;

  protected:

    virtual ~DDSContentFilteredTopic();
};

class DDSCPPDllExport DDSMultiTopic : public DDSTopicDescription {
  // --- <<interface>> DDSMultiTopic: ----------------------------------
  public:

    /*e \dref_MultiTopic_narrow
     */
    static DDSMultiTopic* narrow(DDSTopicDescription* topic_description);

    /*e \dref_MultiTopic_get_subscription_expression
     */
    virtual const char* get_subscription_expression()
        = 0;

    /*e \dref_MultiTopic_get_expression_parameters
     */
    virtual DDS_ReturnCode_t get_expression_parameters(
        DDS_StringSeq& parameters)
        = 0;

    /*e \dref_MultiTopic_set_expression_parameters
     */
    virtual DDS_ReturnCode_t set_expression_parameters(
	const DDS_StringSeq& parameters)
        = 0;

  // --- <<lifecycle>>: ------------------------------------------------
  protected:

    virtual ~DDSMultiTopic();
};

class DDSTopicListener;

class DDSCPPDllExport DDSTopic : 
    public DDSDomainEntity, public DDSTopicDescription 
{
  public: 
    /*e \dref_Topic_narrow
     */
    static DDSTopic* narrow(DDSTopicDescription* topic_description);

    /*e \dref_Topic_get_inconsistent_topic_status
     */
    virtual DDS_ReturnCode_t get_inconsistent_topic_status(
        DDS_InconsistentTopicStatus& status)
        = 0;

    /*e \dref_Topic_set_qos
     */
    virtual DDS_ReturnCode_t set_qos(const DDS_TopicQos& qos)
        = 0;

    /*e \dref_Topic_get_qos
     */
    virtual DDS_ReturnCode_t get_qos(DDS_TopicQos& qos)
        = 0;

    /*e \dref_Topic_set_listener
     */
    virtual DDS_ReturnCode_t set_listener(DDSTopicListener* l, 
        DDS_StatusMask mask = DDS_STATUS_MASK_ALL)
        = 0;

    /*e \dref_Topic_get_listener
     */
    virtual DDSTopicListener* get_listener()
        = 0;

  protected:

    virtual ~DDSTopic();
};

class DDSCPPDllExport DDSTopicListener : public virtual DDSListener {
  public: 

    /*e \dref_TopicListener_on_inconsistent_topic
     */
    virtual void on_inconsistent_topic(DDSTopic* topic, 
        const DDS_InconsistentTopicStatus& status);

  public:

    virtual ~DDSTopicListener();

};

class DDSCPPDllExport DDSContentFilter {

  public:
    virtual ~DDSContentFilter() { };
    
    /*e \dref_ContentFilter_compile
     */
    virtual DDS_ReturnCode_t compile(
	void** new_compile_data, const char *expression,
	const DDS_StringSeq& parameters,const DDS_TypeCode* type_code,
	const char* type_class_name,
	void *old_compile_data) = 0;

    /*e \dref_ContentFilter_evaluate
     */
    virtual DDS_Boolean evaluate(
	void* compile_data,const void* sample) = 0;

    /*e \dref_ContentFilter_finalize
     */
    virtual void finalize(
	void* compile_data) = 0;
};

class DDSCPPDllExport DDSSqlFilter : public virtual DDSContentFilter {

  public:
    
    DDS_ReturnCode_t compile(
	void** new_compile_data, const char *expression,
	const DDS_StringSeq& parameters,const DDS_TypeCode* type_code,
        const char* type_class_name,
	void *old_compile_data);

    DDS_Boolean evaluate(
	void* compile_data,const void* sample);

    void finalize(
	void* compile_data);
    
  public:
    
    virtual ~DDSSqlFilter();

    DDSSqlFilter();

  private:
    const struct DDS_ContentFilter* _cSqlFilter;
};

struct DDS_DataTypeUtilityImpl;

class DDSDataReader;

class DDSDataWriter;

class DDSCPPDllExport DDSTypeSupport {
  public: 
    virtual DDSDataReader*  create_datareaderI(DDSDataReader* dataReader)
	= 0;

    virtual DDS_ReturnCode_t  destroy_datareaderI(DDSDataReader* dataReader)
	= 0;

    virtual DDSDataWriter*  create_datawriterI(DDSDataWriter* dataWriter)
	= 0;

    virtual DDS_ReturnCode_t  destroy_datawriterI(DDSDataWriter* dataWriter)
	= 0;
  protected:
      virtual ~DDSTypeSupport();

  public:
    struct DDS_DataTypeUtilityImpl* get_c_datatype_utilityI() {
	return _cDataTypeUtility;
    }

    static int get_sizeI();

    static int get_alignmentI();

  protected:
    DDSTypeSupport(struct DDS_DataTypeUtilityImpl* cDataTypeUtility) {
	_cDataTypeUtility = cDataTypeUtility;
    }

  private:
    struct DDS_DataTypeUtilityImpl* _cDataTypeUtility;
};

#endif /* dds_cpp_topic_h */
