/*
 * @(#)disc_pluggable_impl.h    generated by: makeheader    Mon Dec  3 23:08:19 2007
 *
 *		built from:	pluggable_impl.ifc
 */

#ifndef disc_pluggable_impl_h
#define disc_pluggable_impl_h


#ifdef __cplusplus
    extern "C" {
#endif


#define DISCPluginInfo_isSamePlugin(left, right)    \
(((left)->vendorId == (right)->vendorId) &&         \
 ((left)->classId == (right)->classId) &&           \
 ((left)->version == (right)->version))


#define DISCPluginInfo_copyShallow(to, from)    \
        (to)->vendorId = (from)->vendorId;      \
        (to)->classId = (from)->classId;        \
        (to)->version = (from)->version;


#ifdef __cplusplus
    }	/* extern "C" */
#endif

#endif /* disc_pluggable_impl_h */
