/*
 * @(#)disc_rtps_impl.h    generated by: makeheader    Mon Dec  3 23:08:19 2007
 *
 *		built from:	rtps_impl.ifc
 */

#ifndef disc_rtps_impl_h
#define disc_rtps_impl_h


#ifdef __cplusplus
    extern "C" {
#endif



/* --------------------------------------------------------- */

/* RTPS spec - PB + DG*domainId + dX */ \
#define DISCRtps_getWellKnownMulticastPort(domain_id, port_base, domain_id_gain, port_offset) \
    (port_base + (domain_id_gain*domain_id) + port_offset)

/* RTPS spec - PB + DG*domainId + PG*participantId + dX */ \
#define DISCRtps_getWellKnownUnicastPort(domain_id, participant_id, port_base, domain_id_gain, participant_id_gain, port_offset) \
    (port_base + (domain_id_gain*domain_id) + (participant_id_gain*participant_id) + port_offset)

/* --------------------------------------------------------- */



#ifdef __cplusplus
    }	/* extern "C" */
#endif

#endif /* disc_rtps_impl_h */
