# -*- mode: ruby -*-
# vi: set ft=ruby :
#
# Copyright (C) 2016  Michael Tesch
#
# You may distribute under the terms of either the GNU General Public
# License or the Apache License, as specified in the LICENSE file.
#
# For more information, see the LICENSE file.
#

Vagrant.configure("2") do |config|
  config.vm.box = "AndrewDryga/vagrant-box-osx"
  config.vm.synced_folder '.', '/vagrant', disabled: true
  config.vm.provider "virtualbox" do |vb|
    # Display the VirtualBox GUI when booting the machine
    #vb.gui = true
    # Customize the amount of memory on the VM:
    vb.linked_clone = true
    vb.memory = "8192"
    vb.cpus = 4
  end

  # brew runs as a user
  config.vm.provision "shell", privileged: false, inline: <<-SHELL
    set -e
    brew update
    brew install scons postgres
  SHELL
end
