/*
 * @(#)event_dll.h    generated by: makeheader    Mon Dec  3 23:07:59 2007
 *
 *		built from:	dll.ifc
 */

#ifndef event_dll_h
#define event_dll_h



#if defined(RTI_WIN32) || defined(RTI_WINCE)
  #if defined(RTI_event_DLL_EXPORT)
    #define RTIEventDllExport __declspec( dllexport )
  #else
    #define RTIEventDllExport
  #endif /* RTI_event_DLL_EXPORT */

  #if defined(RTI_event_DLL_VARIABLE) 
    #if defined(RTI_event_DLL_EXPORT)
      #define RTIEventDllVariable __declspec( dllexport )
    #else
      #define RTIEventDllVariable __declspec( dllimport )
      #endif /* RTI_event_DLL_EXPORT */
  #else 
    #define RTIEventDllVariable
  #endif /* RTI_event_DLL_VARIABLE */
#else
  #define RTIEventDllExport
  #define RTIEventDllVariable
#endif /* RTI_WIN32 || RTI_WINCE */


#endif /* event_dll_h */
