/*
 * @(#)dds_c_data_TTypeSupport.h    generated by: makeheader    Mon Dec  3 23:08:30 2007
 *
 *		built from:	TTypeSupport.c
 */

#ifndef dds_c_data_TTypeSupport_h
#define dds_c_data_TTypeSupport_h

#ifdef __cplusplus
    extern "C" {
#endif

#ifdef __cplusplus
    }	/* extern "C" */
#endif

#endif /* dds_c_data_TTypeSupport_h */
