/*
 * @(#)ndds_utility_cpp.h    generated by: makeheader    Mon Dec  3 23:08:34 2007
 *
 *		built from:	ndds_utility_cpp.ifcxx
 */

#ifndef ndds_utility_cpp_h
#define ndds_utility_cpp_h


#ifndef dds_c_infrastructure_h
  #include "dds_c/dds_c_infrastructure.h"
#endif
#ifndef ndds_utility_c_h
  #include "ndds/ndds_utility_c.h"
#endif

class DDSCPPDllExport NDDSUtility {
  public:
    /*e \dref_Utility_sleep */
    static void sleep(const struct DDS_Duration_t& durationIn);
};

#endif /* ndds_utility_cpp_h */
