/*
 * @(#)ndds_c.h    generated by: makeheader    Mon Dec  3 23:09:06 2007
 *
 *		built from:	c.ifc
 */

#ifndef ndds_c_h
#define ndds_c_h


  #ifdef NDDS_DLL_VARIABLE
    #define RTI_dds_c_DLL_VARIABLE
    #define RTI_disc_DLL_VARIABLE
    #define RTI_pres_DLL_VARIABLE
    #define RTI_writer_history_DLL_VARIABLE
    #define RTI_commend_DLL_VARIABLE
    #define RTI_mig_DLL_VARIABLE
    #define RTI_netio_DLL_VARIABLE
    #define RTI_transport_DLL_VARIABLE
    #define RTI_event_DLL_VARIABLE
    #define RTI_cdr_DLL_VARIABLE
    #define RTI_reda_DLL_VARIABLE
    #define RTI_dl_driver_DLL_VARIABLE
    #define RTI_osapi_DLL_VARIABLE
    #define RTI_clock_DLL_VARIABLE
    #define RTI_log_DLL_VARIABLE
  #endif

  #ifndef makeheader_h
    #include "ndds/log/log_makeheader.h"
  #endif
  #ifndef osapi_type_h
    #include "ndds/osapi/osapi_type.h"
  #endif
  #ifndef dds_c_dll_h
    #include "ndds/dds_c/dds_c_dll.h"
  #endif
  #ifndef dds_c_common_h
    #include "ndds/dds_c/dds_c_common.h"
  #endif
  #ifndef log_dll_h
    #include "ndds/log/log_dll.h"
  #endif
  #ifndef log_common_h
    #include "ndds/log/log_common.h"
  #endif
  #ifndef dds_c_log_h
    #include "ndds/dds_c/dds_c_log.h"
  #endif
  #ifndef dds_c_sequence_h
    #include "ndds/dds_c/dds_c_sequence.h"
  #endif
  #ifndef dds_c_infrastructure_h
    #include "ndds/dds_c/dds_c_infrastructure.h"
  #endif
  #ifndef dds_c_topic_h
    #include "ndds/dds_c/dds_c_topic.h"
  #endif
  #ifndef dds_c_publication_h
    #include "ndds/dds_c/dds_c_publication.h"
  #endif
  #ifndef dds_c_subscription_h
    #include "ndds/dds_c/dds_c_subscription.h"
  #endif
  #ifndef dds_c_domain_h
    #include "ndds/dds_c/dds_c_domain.h"
  #endif
  #ifndef dds_c_data_h
    #include "ndds/dds_c/dds_c_data.h"
  #endif
  #ifndef dds_c_builtin_h
    #include "ndds/dds_c/dds_c_builtin.h"
  #endif
  #ifndef ndds_transport_c_h
    #include "ndds/ndds_transport_c.h"
  #endif
  #ifndef ndds_writerhistory_c_h
    #include "ndds/ndds_writerhistory_c.h"
  #endif
  #ifndef ndds_discovery_c_h
    #include "ndds/ndds_discovery_c.h"
  #endif
  #ifndef ndds_config_c_h
    #include "ndds/ndds_config_c.h"
  #endif
  #ifndef ndds_utility_c_h
    #include "ndds/ndds_utility_c.h"
  #endif

#endif /* ndds_c_h */
