# -*- mode: ruby -*-
# vi: set ft=ruby :
#
# Copyright (C) 2016  Michael Tesch
#
# You may distribute under the terms of either the GNU General Public
# License or the Apache License, as specified in the LICENSE file.
#
# For more information, see the LICENSE file.
#
def gui?; !ENV.fetch('OVJ_VM_GUI', '').empty?; end
def ncpu; Integer(ENV.fetch('OVJ_VM_NCPU', '1')); end
def mem; Integer(ENV.fetch('OVJ_VM_MEM', "%d" % (ncpu * 1024))); end

Vagrant.configure("2") do |config|
  #config.vm.box = "centos/7"
  config.vm.box = "bento/centos-7.5"
  #config.vm.box_version = "?"
  config.ssh.insert_key = false # only needed for vagrant 1.8.5 #7610
  config.vm.synced_folder '.', '/vagrant', disabled: true
  config.vm.provider "virtualbox" do |vb|
    vb.linked_clone = true
    vb.gui = gui?
    vb.memory = mem
    vb.cpus = ncpu
  end
  config.vm.post_up_message = "VM started with #{ncpu} cpus, #{mem} MB memory, and gui=#{gui?}"
  config.vm.provision "shell", inline: <<-SHELL
    set -e
    yum install -y epel-release
    yum update -y # this hoses the guest additions, install vagrant vbguest to workaround

    # these are needed to build
    yum install -y git scons zip unzip gcc-gfortran gcc-c++ gsl-devel \
        mesa-libGL-devel mesa-libGLU-devel
    yum install -y glibc-devel.i686 libstdc++.i686 libX11-devel.i686 \
        libXt-devel.i686 motif-devel.i686

    # these are needed to install
    yum -y groupinstall "GNOME Desktop"
    yum install -y gdb libtool automake autoconf expect rsh-server xinetd \
        tftp-server strace tcsh kernel-devel compat-libf2c-34 \
        mutt sendmail-cf k3b ghostscript ImageMagick rsh cups gedit \
        dos2unix gnuplot xterm enscript
    yum install -y libXtst-devel.i686 libXext-devel.i686 libXi.i686 \
        libstdc++-devel.i686 ncurses-libs.i686 ncurses-devel.i686 \
        mesa-libGL-devel.i686 \
        atk.i686 gtk2.i686 mesa-libGL.i686 \
        mesa-libGLU.i686 libidn.i686 libxml2.i686 libXaw.i686 libXpm.i686

    systemctl set-default graphical.target
    systemctl start graphical.target

    yum clean all
    # disable SELinux
    setenforce 0
    sed -i 's/SELINUX=\(enforcing\|permissive\)/SELINUX=disabled/g' /etc/selinux/config
  SHELL
end
