# -*- mode: ruby -*-
# vi: set ft=ruby :
#
# Copyright (C) 2016  Michael Tesch
#
# You may distribute under the terms of either the GNU General Public
# License or the Apache License, as specified in the LICENSE file.
#
# For more information, see the LICENSE file.
#

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://atlas.hashicorp.com/search.
  config.vm.box = "bento/centos-6.8"
  #config.vm.box_version = "2.2.9"

  #config.vm.box = "centos/6"
  #config.vm.box_version = "1608.02"

  config.ssh.insert_key = false # only needed for vagrant 1.8.5 #7610

  # Disable automatic box update checking. If you disable this, then
  # boxes will only be checked for updates when the user runs
  # `vagrant box outdated`. This is not recommended.
  # config.vm.box_check_update = false

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  # config.vm.synced_folder "../data", "/vagrant_data"

  # Disable the sync'd folder because often the VB guest additions are inoperable.
  # And so far nothing in the OpenVnmrJ build requires the cross-mount.
  # If your VirtualBox guest additions are correct, you can re-enable this.
  config.vm.synced_folder '.', '/vagrant', disabled: true

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  #
  config.vm.provider "virtualbox" do |vb|
    # Display the VirtualBox GUI when booting the machine
    #vb.gui = true
    # Customize the amount of memory on the VM:
    vb.memory = "2048"
    vb.customize "pre-boot", ["storageattach", :id,
                              "--storagectl", "IDE Controller",
                              "--port", "1",
                              "--device", "0",
                              "--type", "dvddrive",
                              "--medium", "emptydrive",
                             ]
  end

  # Enable provisioning with a shell script. Additional provisioners such as
  # Puppet, Chef, Ansible, Salt, and Docker are also available. Please see the
  # documentation for more information about their specific syntax and use.

  config.vm.provision "shell", inline: <<-SHELL
    yum install -y epel-release
    yum update -y # todo: this hoses the guest additions

    # these are needed to build
    yum install -y git scons zip unzip gcc-gfortran gcc-c++ mesa-libGL-devel mesa-libGLU-devel
    yum install -y glibc-devel.i686 libstdc++.i686 libX11-devel.i686 libXt-devel.i686 openmotif-devel.i686
    yum install -y gsl-devel libtiff-devel
    ln -s /usr/bin/gfortran /usr/bin/g77

    # these are needed to install
    yum -y groupinstall "Desktop"
    sudo yum install -y gdb libtool automake autoconf expect rsh-server xinetd tftp-server strace tcsh
    sudo yum install -y libXext-devel.i686
    sudo yum install -y kernel-devel compat-libf2c-34 compat-gcc-34-g77 openmotif22 tk tcl
    sudo yum install -y mutt sendmail-cf k3b ghostscript ImageMagick rsh libXtst-devel.i686
    sudo yum install -y libXi.i686 libstdc++-devel.i686 ncurses-libs.i686 ncurses-devel.i686
    sudo yum install -y mesa-libGL-devel.i686 tcl.i686 tcl-devel.i686 tk.i686 tk-devel.i686
    sudo yum install -y libtiff.i686 libtiff-devel.i686 atk.i686 gtk2.i686 mesa-libGL.i686
    sudo yum install -y mesa-libGLU.i686 libidn.i686 libxml2.i686 libXaw.i686 libXpm.i686

    yum clean all
    # disable SELinux
    setenforce 0
    sed -i 's/SELINUX=\(enforcing\|permissive\)/SELINUX=disabled/g' /etc/selinux/config
  SHELL

  #config.vm.provision "file", source: "~/.gitconfig", destination: ".gitconfig"
  #config.vm.provision "file", source: ENV["ovjBuildDir"], destination: "ovjbuild"

end
