# -*- mode: ruby -*-
# vi: set ft=ruby :
#
# Copyright (C) 2016  Michael Tesch
#
# You may distribute under the terms of either the GNU General Public
# License or the Apache License, as specified in the LICENSE file.
#
# For more information, see the LICENSE file.
#

Vagrant.configure("2") do |config|
  config.vm.box = "bento/centos-6.8"
  #config.vm.box_version = "2.2.9"
  #config.vm.box = "centos/6"
  #config.vm.box_version = "1608.02"
  config.ssh.insert_key = false # only needed for vagrant 1.8.5 #7610
  config.vm.synced_folder '.', '/vagrant', disabled: true
  config.vm.provider "virtualbox" do |vb|
    #vb.gui = true
    vb.linked_clone = true
    vb.memory = "4096"
    vb.cpus = 2
    vb.customize "pre-boot", ["storageattach", :id,
                              "--storagectl", "IDE Controller",
                              "--port", "1",
                              "--device", "0",
                              "--type", "dvddrive",
                              "--medium", "emptydrive",
                             ]
  end
  config.vm.provision "shell", inline: <<-SHELL
    yum install -y epel-release
    yum update -y # this hoses the guest additions, install vagrant vbguest to workaround

    # these are needed to build
    yum install -y git scons zip unzip gcc-gfortran gcc-c++ mesa-libGL-devel mesa-libGLU-devel
    yum install -y glibc-devel.i686 libstdc++.i686 libX11-devel.i686 libXt-devel.i686 openmotif-devel.i686
    yum install -y gsl-devel libtiff-devel
    ln -s /usr/bin/gfortran /usr/bin/g77

    # these are needed to install
    yum -y groupinstall "Desktop"
    sudo yum install -y gdb libtool automake autoconf expect rsh-server xinetd tftp-server strace tcsh
    sudo yum install -y libXext-devel.i686
    sudo yum install -y kernel-devel compat-libf2c-34 compat-gcc-34-g77 openmotif22 tk tcl
    sudo yum install -y mutt sendmail-cf k3b ghostscript ImageMagick rsh libXtst-devel.i686
    sudo yum install -y libXi.i686 libstdc++-devel.i686 ncurses-libs.i686 ncurses-devel.i686
    sudo yum install -y mesa-libGL-devel.i686 tcl.i686 tcl-devel.i686 tk.i686 tk-devel.i686
    sudo yum install -y libtiff.i686 libtiff-devel.i686 atk.i686 gtk2.i686 mesa-libGL.i686
    sudo yum install -y mesa-libGLU.i686 libidn.i686 libxml2.i686 libXaw.i686 libXpm.i686

    yum clean all
    # disable SELinux
    setenforce 0
    sed -i 's/SELINUX=\(enforcing\|permissive\)/SELINUX=disabled/g' /etc/selinux/config
  SHELL
end
