/*
 * @(#)writer_history_odbc.h    generated by: makeheader    Mon Dec  3 23:08:12 2007
 *
 *		built from:	odbc.ifc
 */

#ifndef writer_history_odbc_h
#define writer_history_odbc_h



#ifndef writer_history_dll_h
#include "writer_history/writer_history_dll.h"
#endif

#ifndef writer_history_interface_h
#include "writer_history/writer_history_interface.h"
#endif

/*e
  \defgroup WriterHistoryOdbcPluginModule Writer History ODBC Plugin
  \ingroup WriterHistoryModule

  \brief Writer History ODBC plugin implementation.
*/

/*e \ingroup WriterHistoryOdbcPluginModule
  \brief Maximum length of a DSN.
*/
#define NDDS_WRITERHISTORY_ODBC_PLUGIN_DSN_MAX_LENGTH 100

/*e \ingroup WriterHistoryObdcPluginModule
  \brief Maximum length of an ODBC driver library.
*/
#define NDDS_WRITERHISTORY_ODBC_PLUGIN_LIBNAME_MAX_LENGTH 255

/*e \ingroup WriterHistoryOdbcPluginModule
  \brief Name of the attribute used to configure a Odbc dsn.
*/
#define NDDS_WRITERHISTORY_ODBC_PLUGIN_DSN_ATTRIBUTE_NAME "dsn"

/*e \ingroup WriterHistoryOdbcPluginModule
  \brief Name of the attribute used to configure an Odbc username.
*/
#define NDDS_WRITERHISTORY_ODBC_PLUGIN_USERNAME_ATTRIBUTE_NAME "username"

/*e \ingroup WriterHistoryOdbcPluginModule
  \brief Name of the attribute used to configure an Odbc password.
*/
#define NDDS_WRITERHISTORY_ODBC_PLUGIN_PASSWORD_ATTRIBUTE_NAME "password"

/*e \ingroup WriterHistoryOdbcPluginModule
  \brief Name of the attribute used to configure an Odbc driver.
*/
#define NDDS_WRITERHISTORY_ODBC_PLUGIN_DRIVER_ATTRIBUTE_NAME "driver"

/*e
  \brief Name of the property used to configure shared/exclusive connection handles.
*/
#define NDDS_WRITERHISTORY_ODBC_PLUGIN_SHARED_ATTRIBUTE_NAME "shared"

/*e
  \brief Name of the property used to configure the timeout used for the mutexes.
*/
#define NDDS_WRITERHISTORY_ODBC_PLUGIN_TIMEOUT_ATTRIBUTE_NAME "timeout"


/*e \ingroup WriterHistoryOdbcPluginModule
  \brief Name of the attribute used to configure the maximum size of the instance cache.
*/
#define NDDS_WRITERHISTORY_ODBC_PLUGIN_INSTANCE_CACHE_MAX_SIZE_ATTRIBUTE_NAME "instance_cache_max_size"

/*e \ingroup WriterHistoryOdbcPluginModule
  \brief Name of the attribute used to configure the initial size of the instance cache.
*/
#define NDDS_WRITERHISTORY_ODBC_PLUGIN_INSTANCE_CACHE_INIT_SIZE_ATTRIBUTE_NAME "instance_cache_init_size"

/*e \ingroup WriterHistoryOdbcPluginModule
  \brief Name of the attribute used to configure the maximum size of the instance cache.
*/
#define NDDS_WRITERHISTORY_ODBC_PLUGIN_SAMPLE_CACHE_MAX_SIZE_ATTRIBUTE_NAME "sample_cache_max_size"

/*e \ingroup WriterHistoryOdbcPluginModule
  \brief Name of the attribute used to configure the initial size of the instance cache.
*/
#define NDDS_WRITERHISTORY_ODBC_PLUGIN_SAMPLE_CACHE_INIT_SIZE_ATTRIBUTE_NAME "sample_cache_init_size"

/*e \ingroup WriterHistoryOdbcPluginModule
  \brief Name of the attribute used to determine if the database storage associated to a WH will be cleaned up
  after the data writer deletion.
*/
#define NDDS_WRITERHISTORY_ODBC_PLUGIN_CLEANUP_ATTRIBUTE_NAME "cleanup_on_destroy"

/*e \ingroup WriterHistoryOdbcPluginModule
  \brief Name of the attribute used to determine if the database storage associated to a WH will be
  restored if the tables already exist on WH creation.
*/
#define NDDS_WRITERHISTORY_ODBC_PLUGIN_RESTORE_ATTRIBUTE_NAME "restore"

#ifdef __cplusplus
    extern "C" {
#endif


extern WRITERHISTORYDllExport 
RTI_INT32 NDDS_WriterHistory_OdbcPlugin_create(
    struct NDDS_WriterHistory_Plugin ** plugin_out);



#ifdef __cplusplus
    }	/* extern "C" */
#endif


#endif /* writer_history_odbc_h */
