/*
 * @(#)writer_history_interface_impl.h    generated by: makeheader    Mon Dec  3 23:08:12 2007
 *
 *		built from:	interface_impl.ifc
 */

#ifndef writer_history_interface_impl_h
#define writer_history_interface_impl_h


#ifdef __cplusplus
    extern "C" {
#endif


#define NDDS_WriterHistory_Property_copy(to, src) \
    RTIOsapiMemory_copy(to, src, sizeof(struct NDDS_WriterHistory_Property))


#define NDDS_WriterHistory_Listener_initialize(listener) \
    listener->listener_data = NULL; \
    listener->initialize_sample = NULL; \
    listener->finalize_sample = NULL; \
    listener->initialize_instance = NULL; \
    listener->finalize_instance = NULL;


#define NDDS_WriterHistory_Listener_is_valid(plugin) \
    ((plugin->initialize_instance == NULL) ? RTI_FALSE :\
    ((plugin->initialize_sample == NULL) ? RTI_FALSE :\
    RTI_TRUE))


#define NDDS_WRITERHISTORY_MEMORY_PLUGIN_NAMESPACE "dds.data_writer.history.memory_plugin"


#define NDDS_WRITERHISTORY_ODBC_PLUGIN_NAMESPACE "dds.data_writer.history.odbc_plugin"


#define NDDS_WRITERHISTORY_BUILTIN_MEMORY_PLUGIN_NAME  NDDS_WRITERHISTORY_MEMORY_PLUGIN_NAMESPACE".builtin"


#define NDDS_WRITERHISTORY_BUILTIN_ODBC_PLUGIN_NAME NDDS_WRITERHISTORY_ODBC_PLUGIN_NAMESPACE".builtin"


#define NDDS_WRITERHISTORY_PLUGIN_NAME_PROPERTY "dds.data_writer.history.plugin_name"


#ifdef __cplusplus
    }	/* extern "C" */
#endif

#endif /* writer_history_interface_impl_h */
