# -*- mode: ruby -*-
# vi: set ft=ruby :
#
# Copyright (C) 2018  Michael Tesch
#
# This file is a part of the OpenVnmrJ project.  You may distribute it
# under the terms of either the GNU General Public License or the
# Apache 2.0 License, as specified in the LICENSE file.
#
# For more information, see the OpenVnmrJ LICENSE file.
#

# Returns true if `VMGUI` environment variable is set to a non-empty
# value.  Defaults to false
def gui_enabled?
  !ENV.fetch('VMGUI', '').empty?
end
def ncpu
  Integer(ENV.fetch('VMNCPU', '1'))
end

Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-18.04"
  config.vm.synced_folder '.', '/vagrant', disabled: true
  config.vm.provider "virtualbox" do |vb|
    vb.cpus = ncpu
    vb.memory = "%d" % (ncpu * 1024)
    # Display the VirtualBox GUI when booting the machine?
    vb.gui = gui_enabled?
  end
  config.vm.provision "shell", inline: <<-SHELL
    export DEBIAN_FRONTEND=noninteractive
    set -e
    dpkg --add-architecture i386
    apt-get -qq update
    apt-get -qq -y dist-upgrade

    # these are needed to build
    apt-get install -y git scons g++ gfortran gdm3 gnome-session \
      lib32stdc++-7-dev libc6-dev-i386 libglu1-mesa-dev

    # these are needed to install
    #apt-get install -y openjdk-8-jre
    apt-get install -y csh expect bc rsh-server tftpd \
      mutt sharutils gnome-power-manager k3b kdiff3 rarpd \
      ghostscript imagemagick postgresql sendmail-cf \
      gedit dos2unix zip cups gnuplot gnome-terminal enscript
    #debconf-set-selections <<< "postfix postfix/mailname string your.hostname.com"
    #debconf-set-selections <<< "postfix postfix/main_mailer_type string 'Internet Site'"
    chmod a+rw /var/run/postgresql

    # these are needed to build
    # apt-get uninstalls these if an amd64 version is installed for something else >:(
    # so install them last...
    apt-get install -y libmotif-dev:i386 libx11-dev:i386 libxt-dev:i386 libxft-dev:i386

    echo "dash dash/sh boolean false" | debconf-set-selections
    dpkg-reconfigure dash

    # dpkg-reconfigure gdm
    # echo "127.0.0.1 $(hostname)" >> /etc/hosts
  SHELL
end
