/*
 * @(#)dds_c_infrastructure.h    generated by: makeheader    Mon Dec  3 23:08:26 2007
 *
 *		built from:	infrastructure.ifc
 */

#ifndef dds_c_infrastructure_h
#define dds_c_infrastructure_h



  #ifndef osapi_type_h
    #include "osapi/osapi_type.h"
  #endif

  #ifndef osapi_thread_h
    #include "osapi/osapi_thread.h"
  #endif

  #ifndef dds_c_dll_h
    #include "dds_c/dds_c_dll.h"
  #endif
  #ifndef dds_c_common_h
    #include "dds_c/dds_c_common.h"
  #endif
  #ifndef dds_c_string_h
    #include "dds_c/dds_c_string.h"
  #endif
  #ifndef dds_c_sequence_h
    #include "dds_c/dds_c_sequence.h"
  #endif
  #ifndef pres_liveliness_h
    #include "pres/pres_liveliness.h"
  #endif

#ifdef __cplusplus
    extern "C" {
#endif


DDS_SEQUENCE(DDS_CharSeq, DDS_Char);


DDS_SEQUENCE(DDS_WcharSeq, DDS_Wchar);


DDS_SEQUENCE(DDS_OctetSeq, DDS_Octet);


DDS_SEQUENCE(DDS_ShortSeq, DDS_Short);


DDS_SEQUENCE(DDS_UnsignedShortSeq, DDS_UnsignedShort);


DDS_SEQUENCE(DDS_LongSeq, DDS_Long);


DDS_SEQUENCE(DDS_UnsignedLongSeq, DDS_UnsignedLong);


DDS_SEQUENCE(DDS_LongLongSeq, DDS_LongLong);


DDS_SEQUENCE(DDS_UnsignedLongLongSeq, DDS_UnsignedLongLong);


DDS_SEQUENCE(DDS_FloatSeq, DDS_Float);


DDS_SEQUENCE(DDS_DoubleSeq, DDS_Double);


DDS_SEQUENCE(DDS_LongDoubleSeq, DDS_LongDouble);


DDS_SEQUENCE(DDS_BooleanSeq, DDS_Boolean);


DDS_SEQUENCE(DDS_StringSeq, char*);


DDS_SEQUENCE(DDS_WstringSeq, DDS_Wchar*);


struct DDS_Time_t {
    /*e
     * \dref_TimeStamp_sec
     */
    DDS_Long sec; 
    
    /*e
     * \dref_TimeStamp_nanosec
     */
    DDS_UnsignedLong nanosec; 
#ifdef __cplusplus
    inline bool operator==(const DDS_Time_t& r) {
	return (sec == r.sec && nanosec == r.nanosec);
    };
    inline bool operator!=(const DDS_Time_t& r) {
	return (sec != r.sec || nanosec != r.nanosec);
    };
    inline bool operator<(const DDS_Time_t& r) {
        if (sec == r.sec) {
            return (nanosec < r.nanosec);
        }
	return (sec < r.sec);
    };
    inline bool operator>(const DDS_Time_t& r) {
        if (sec == r.sec) {
            return (nanosec > r.nanosec);
        }
	return (sec > r.sec);
    };
    inline bool operator<=(const DDS_Time_t& r) {
        if (sec == r.sec) {
            return (nanosec <= r.nanosec);
        }
	return (sec < r.sec);
    };
    inline bool operator>=(const DDS_Time_t& r) {
        if (sec == r.sec) {
            return (nanosec >= r.nanosec);
        }
	return (sec > r.sec);
    };
    inline DDS_Time_t operator+(const DDS_Time_t& r) {
	DDS_Time_t result = {sec + r.sec, nanosec + r.nanosec};
	if(result.nanosec >= 1000000000) {
	    ++result.sec;
	    result.nanosec -= 1000000000;
	}
	return result;
    };
#endif/* __cplusplus */
};

#ifndef __cplusplus
#define DDS_Time_t_equals(l, r) \
    ((l).sec == (r).sec && (l).nanosec == (r).nanosec)
#define DDS_Time_t_greater_than(l, r) \
    (((l).sec > (r).sec) || \
     (((l).sec == (r).sec) && \
      ((l).nanosec > (r).nanosec)))
#define DDS_Time_t_less_than(l, r) \
    (((l).sec < (r).sec) || \
     (((l).sec == (r).sec) && \
      ((l).nanosec < (r).nanosec)))
#endif/* !__cplusplus */



#define DDS_TIME_ZERO    { 0L, 0UL }


#define DDS_Time_is_zero(timePtr) \
        ((timePtr)->sec == 0L || (timePtr)->nanosec == 0UL)

 extern DDSCDllVariable const DDS_Long DDS_TIME_INVALID_SEC;


#define DDS_TIMESTAMP_INVALID_SEC DDS_TIME_INVALID_SEC

 extern DDSCDllVariable const DDS_UnsignedLong DDS_TIME_INVALID_NSEC;


#define DDS_TIMESTAMP_INVALID_NSEC DDS_TIME_INVALID_NSEC

 extern DDSCDllVariable const struct DDS_Time_t DDS_TIME_INVALID;


#define DDS_Time_is_invalid(timePtr) \
        ((timePtr)->sec < 0)

struct DDS_Duration_t { 
    /*e \dref_TimeStamp_sec
     */
    DDS_Long sec; 
    
    /*e \dref_TimeStamp_nanosec
     */
    DDS_UnsignedLong nanosec; 
};

 extern DDSCDllVariable const DDS_Long DDS_DURATION_INFINITE_SEC;


/*i deprecated */
#define DDS_DURATION_INFINITY_SEC DDS_DURATION_INFINITE_SEC

 extern DDSCDllVariable const DDS_UnsignedLong DDS_DURATION_INFINITE_NSEC;


/*i deprecated */
#define DDS_DURATION_INFINITY_NSEC DDS_DURATION_INFINITE_NSEC

 extern DDSCDllVariable const struct DDS_Duration_t
DDS_DURATION_INFINITE;


#define DDS_Duration_is_infinite(durationPtr) \
        ((durationPtr)->sec == DDS_DURATION_INFINITE_SEC && \
         (durationPtr)->nanosec == DDS_DURATION_INFINITE_NSEC)


#define DDS_Duration_copy(out, in) \
    ((out.sec = in.sec) && \
     (out.nanosec = in.nanosec))

#define DDS_Duration_equal(me, other) \
    ((me)->sec == (other)->sec && \
    (me)->nanosec == (other)->nanosec)

 extern DDSCDllVariable const DDS_Long DDS_DURATION_ZERO_SEC;

 extern DDSCDllVariable const DDS_UnsignedLong DDS_DURATION_ZERO_NSEC;

 extern DDSCDllVariable const struct DDS_Duration_t
DDS_DURATION_ZERO;


#define DDS_Duration_is_zero(durationPtr) \
        ((durationPtr)->sec == DDS_DURATION_ZERO_SEC && \
         (durationPtr)->nanosec == DDS_DURATION_ZERO_NSEC)

typedef DDS_HANDLE_TYPE_NATIVE DDS_InstanceHandle_t;


DDS_SEQUENCE(DDS_InstanceHandleSeq, DDS_InstanceHandle_t);

 extern DDSCDllVariable const DDS_InstanceHandle_t
DDS_HANDLE_NIL;

extern DDSCDllExport DDS_Boolean
DDS_InstanceHandle_equals(const DDS_InstanceHandle_t* self,
                          const DDS_InstanceHandle_t* other);


#define DDS_InstanceHandle_is_nil(handlePtr) \
        DDS_InstanceHandle_equals(handlePtr, &DDS_HANDLE_NIL)

struct DDS_GUID_t {
    /*e \dref_GUID_t_value 
    */
    DDS_Octet value[16];
};

 extern DDSCDllVariable const struct DDS_GUID_t DDS_GUID_AUTO;

 extern DDSCDllVariable const struct DDS_GUID_t DDS_GUID_UNKNOWN;

extern DDSCDllExport DDS_Boolean
DDS_GUID_equals(const struct DDS_GUID_t* self,
                const struct DDS_GUID_t* other);

extern DDSCDllExport
void DDS_GUID_copy(struct DDS_GUID_t* self,
                   const struct DDS_GUID_t* other);

extern DDSCDllExport void 
DDS_GUID_print(
    const struct DDS_GUID_t* self, 
    const char *desc, unsigned int indent);

extern DDSCDllExport
void DDS_GUID_zero(struct DDS_GUID_t* self);

struct DDS_SequenceNumber_t { 
    /*e \dref_SequenceNumber_t_high
     */
    DDS_Long high; 
    
    /*e \dref_SequenceNumber_t_low
     */
    DDS_UnsignedLong low; 
};

 extern DDSCDllVariable const struct DDS_SequenceNumber_t
DDS_SEQUENCE_NUMBER_UNKNOWN;

 extern DDSCDllVariable const struct DDS_SequenceNumber_t
DDS_SEQUENCE_NUMBER_ZERO;

 extern DDSCDllVariable const struct DDS_SequenceNumber_t
DDS_SEQUENCE_NUMBER_MAX;


#define DDS_SequenceNumber_compare(sn1,sn2) \
    ((((sn1)->high) > ((sn2)->high)) ? 1 : \
     ((((sn1)->high) < ((sn2)->high)) ? -1 : \
      ((((sn1)->low) > ((sn2)->low)) ? 1 : \
       ((((sn1)->low) < ((sn2)->low)) ? -1 : 0))))

struct DDS_OriginalWriterInfo_t { 
    /*i \dref_OriginalWriterInfo_t_writer_guid */
    struct DDS_GUID_t writer_guid;
    /*i \dref_OriginalWriterInfo_t_sequence_number */
    struct DDS_SequenceNumber_t sequence_number;
    /*TODO: Add inline parameters */
};

typedef enum {
    /*e \dref_ExceptionCode_t_NO_EXCEPTION_CODE
     */
    DDS_NO_EXCEPTION_CODE              = 0,
    /*e \dref_ExceptionCode_t_USER_EXCEPTION_CODE
     */    
    DDS_USER_EXCEPTION_CODE            = 1,
    /*e \dref_ExceptionCode_t_SYSTEM_EXCEPTION_CODE
     */    
    DDS_SYSTEM_EXCEPTION_CODE          = 2,
    /*e \dref_ExceptionCode_t_BAD_PARAM_SYSTEM_EXCEPTION_CODE
     */
    DDS_BAD_PARAM_SYSTEM_EXCEPTION_CODE = 3,
    /*e \dref_ExceptionCode_t_NO_MEMORY_SYSTEM_EXCEPTION_CODE
     */
    DDS_NO_MEMORY_SYSTEM_EXCEPTION_CODE = 4,
    /*e \dref_ExceptionCode_t_BAD_TYPECODE_SYSTEM_EXCEPTION_CODE
     */
    DDS_BAD_TYPECODE_SYSTEM_EXCEPTION_CODE = 5,
    /*e \dref_ExceptionCode_t_BADKIND_USER_EXCEPTION_CODE
     */
    DDS_BADKIND_USER_EXCEPTION_CODE    = 6,
    /*e \dref_ExceptionCode_t_BOUNDS_USER_EXCEPTION_CODE
     */
    DDS_BOUNDS_USER_EXCEPTION_CODE     = 7
} DDS_ExceptionCode_t;

typedef enum {
    /*e \dref_ReturnCode_t_RETCODE_OK
     */
    DDS_RETCODE_OK                   = 0,

    /*e \dref_ReturnCode_t_RETCODE_ERROR
     */
    DDS_RETCODE_ERROR                = 1,

    /*e \dref_ReturnCode_t_RETCODE_UNSUPPORTED
     */
    DDS_RETCODE_UNSUPPORTED         = 2,

    /*e \dref_ReturnCode_t_RETCODE_BAD_PARAMETER
     */
    DDS_RETCODE_BAD_PARAMETER        = 3,

    /*e \dref_ReturnCode_t_RETCODE_PRECONDITION_NOT_MET
     */
    DDS_RETCODE_PRECONDITION_NOT_MET = 4,

    /*e \dref_ReturnCode_t_RETCODE_OUT_OF_RESOURCES
     */
    DDS_RETCODE_OUT_OF_RESOURCES     = 5,

    /*e \dref_ReturnCode_t_RETCODE_NOT_ENABLED
     */
    DDS_RETCODE_NOT_ENABLED          = 6,

    /*e \dref_ReturnCode_t_RETCODE_IMMUTABLE_POLICY
     */
    DDS_RETCODE_IMMUTABLE_POLICY     = 7,

    /*e \dref_ReturnCode_t_RETCODE_INCONSISTENT_POLICY
     */
    DDS_RETCODE_INCONSISTENT_POLICY  = 8,

    /*e \dref_ReturnCode_t_RETCODE_ALREADY_DELETED
     */
    DDS_RETCODE_ALREADY_DELETED  = 9,

    /*e \dref_ReturnCode_t_RETCODE_TIMEOUT
     */
    DDS_RETCODE_TIMEOUT  = 10,

    /*e \dref_ReturnCode_t_RETCODE_NO_DATA
     */
    DDS_RETCODE_NO_DATA  = 11,

    /*e \dref_ReturnCode_t_RETCODE_ILLEGAL_OPERATION
     */
    DDS_RETCODE_ILLEGAL_OPERATION  = 12

} DDS_ReturnCode_t;

typedef DDS_UnsignedLong DDS_StatusMask;


#define DDS_STATUS_MASK_NONE   ((DDS_StatusMask) 0)


#define DDS_STATUS_MASK_ALL    (~DDS_STATUS_MASK_NONE)

typedef enum {
    /*e \dref_StatusKind_INCONSISTENT_TOPIC_STATUS
     */
    DDS_INCONSISTENT_TOPIC_STATUS = 0x0001 << 0,

    /*e \dref_StatusKind_OFFERED_DEADLINE_MISSED_STATUS
     */
    DDS_OFFERED_DEADLINE_MISSED_STATUS = 0x0001 << 1,

    /*e \dref_StatusKind_REQUESTED_DEADLINE_MISSED_STATUS
     */
    DDS_REQUESTED_DEADLINE_MISSED_STATUS = 0x0001 << 2,

    /*e \dref_StatusKind_OFFERED_INCOMPATIBLE_QOS_STATUS
     */
    DDS_OFFERED_INCOMPATIBLE_QOS_STATUS = 0x0001 << 5,

    /*e \dref_StatusKind_REQUESTED_INCOMPATIBLE_QOS_STATUS
     */
    DDS_REQUESTED_INCOMPATIBLE_QOS_STATUS = 0x0001 << 6,

    /*e \dref_StatusKind_SAMPLE_LOST_STATUS
     */
    DDS_SAMPLE_LOST_STATUS = 0x0001 << 7,

    /*e \dref_StatusKind_SAMPLE_REJECTED_STATUS
     */
    DDS_SAMPLE_REJECTED_STATUS = 0x0001 << 8,

    /*e \dref_StatusKind_DATA_ON_READERS_STATUS
     */
    DDS_DATA_ON_READERS_STATUS = 0x0001 << 9,

    /*e \dref_StatusKind_DATA_AVAILABLE_STATUS
     */
    DDS_DATA_AVAILABLE_STATUS = 0x0001 << 10,

    /*e \dref_StatusKind_LIVELINESS_LOST_STATUS
     */
    DDS_LIVELINESS_LOST_STATUS = 0x0001 << 11,

    /*e \dref_StatusKind_LIVELINESS_CHANGED_STATUS
     */
    DDS_LIVELINESS_CHANGED_STATUS = 0x0001 << 12,

    /*e \dref_StatusKind_PUBLICATION_MATCHED_STATUS
     */
    DDS_PUBLICATION_MATCHED_STATUS = 0x0001 << 13,

    /*e \dref_StatusKind_SUBSCRIPTION_MATCHED_STATUS
     */
    DDS_SUBSCRIPTION_MATCHED_STATUS = 0x0001 << 14,
    
    /* --- Begin extended statuses --- */
    /* The "right"-most 24 bits of the StatusMask are reserved
     * for standard statuses. The remaining 8 bits are for extended statuses.
     */
    
    /*e \dref_StatusKind_RELIABLE_WRITER_CACHE_CHANGED_STATUS
     */
    DDS_RELIABLE_WRITER_CACHE_CHANGED_STATUS    = 0x00000001 << 24,
    
    /*e \dref_StatusKind_RELIABLE_READER_ACTIVITY_CHANGED_STATUS
     */
    DDS_RELIABLE_READER_ACTIVITY_CHANGED_STATUS = 0x00000001 << 25,

    /*i \dref_StatusKind_WRITER_MATCHED_STATISTICS_REQUESTED_STATUS
     */
    DDS_WRITER_MATCHED_STATISTICS_REQUESTED_STATUS = 0x00000001 << 26,

    /*i \dref_StatusKind_WRITER_MATCHED_STATISTICS_REQUESTED_STATUS
     */
    DDS_READER_MATCHED_STATISTICS_REQUESTED_STATUS = 0x00000001 << 27

} DDS_StatusKind;

typedef DDS_UnsignedLong DDS_ThreadSettingsKindMask;


#define DDS_THREAD_SETTINGS_KIND_MASK_DEFAULT \
    ((DDS_ThreadSettingsKindMask)RTI_OSAPI_THREAD_OPTION_DEFAULT)

typedef enum {
    /*e \dref_ThreadSettingsKind_THREAD_SETTINGS_FLOATING_POINT
     */
    DDS_THREAD_SETTINGS_FLOATING_POINT =
    RTI_OSAPI_THREAD_OPTION_FLOATING_POINT,
    
    /*e \dref_ThreadSettingsKind_THREAD_SETTINGS_STDIO
     */
    DDS_THREAD_SETTINGS_STDIO = RTI_OSAPI_THREAD_OPTION_STDIO,

    /*e \dref_ThreadSettingsKind_THREAD_SETTINGS_REALTIME_PRIORITY
     */
    DDS_THREAD_SETTINGS_REALTIME_PRIORITY =
    RTI_OSAPI_THREAD_OPTION_REALTIME_PRIORITY,

    /*e \dref_ThreadSettingsKind_THREAD_SETTINGS_PRIORITY_ENFORCE
     */
    DDS_THREAD_SETTINGS_PRIORITY_ENFORCE =
    RTI_OSAPI_THREAD_OPTION_PRIORITY_ENFORCE,

    /*e \dref_ThreadSettingsKind_THREAD_SETTINGS_CANCEL_ASYNCHRONOUS
     */
    DDS_THREAD_SETTINGS_CANCEL_ASYNCHRONOUS =
    RTI_OSAPI_THREAD_OPTION_CANCEL_ASYNCHRONOUS

} DDS_ThreadSettingsKind;

struct DDS_ThreadSettings_t {
    /*e \dref_ThreadSettings_t_mask
     */
    DDS_ThreadSettingsKindMask mask;
    /*e \dref_ThreadSettings_t_priority
     */
    DDS_Long priority;
    /*e \dref_ThreadSettings_t_stack_size
     */
    DDS_Long stack_size;
};


#define DDS_THREAD_SETTINGS_DEFAULT \
{ DDS_THREAD_SETTINGS_KIND_MASK_DEFAULT, \
  RTI_OSAPI_THREAD_PRIORITY_DEFAULT, \
  RTI_OSAPI_THREAD_STACK_SIZE_DEFAULT }

typedef enum {
    /*e \dref_QosPolicyId_t_INVALID_QOS_POLICY_ID
     */
    DDS_INVALID_QOS_POLICY_ID           = 0,
    
    /*e \dref_QosPolicyId_t_USERDATA_QOS_POLICY_ID
     */
    DDS_USERDATA_QOS_POLICY_ID          = 1,
    
    /*e \dref_QosPolicyId_t_DURABILITY_QOS_POLICY_ID
     */
    DDS_DURABILITY_QOS_POLICY_ID        = 2,
    
    /*e \dref_QosPolicyId_t_PRESENTATION_QOS_POLICY_ID
     */
    DDS_PRESENTATION_QOS_POLICY_ID      = 3,
    
    /*e \dref_QosPolicyId_t_DEADLINE_QOS_POLICY_ID
     */
    DDS_DEADLINE_QOS_POLICY_ID          = 4,
    
    /*e \dref_QosPolicyId_t_LATENCYBUDGET_QOS_POLICY_ID
     */
    DDS_LATENCYBUDGET_QOS_POLICY_ID     = 5,
    
    /*e \dref_QosPolicyId_t_OWNERSHIP_QOS_POLICY_ID
     */
    DDS_OWNERSHIP_QOS_POLICY_ID         = 6,
    
    /*e \dref_QosPolicyId_t_OWNERSHIPSTRENGTH_QOS_POLICY_ID
     */
    DDS_OWNERSHIPSTRENGTH_QOS_POLICY_ID = 7,
    
    /*e \dref_QosPolicyId_t_LIVELINESS_QOS_POLICY_ID
     */
    DDS_LIVELINESS_QOS_POLICY_ID        = 8,
    
    /*e \dref_QosPolicyId_t_TIMEBASEDFILTER_QOS_POLICY_ID
     */
    DDS_TIMEBASEDFILTER_QOS_POLICY_ID   = 9,
    
    /*e \dref_QosPolicyId_t_PARTITION_QOS_POLICY_ID
     */
    DDS_PARTITION_QOS_POLICY_ID         = 10,
    
    /*e \dref_QosPolicyId_t_RELIABILITY_QOS_POLICY_ID
     */
    DDS_RELIABILITY_QOS_POLICY_ID       = 11,
    
    /*e \dref_QosPolicyId_t_DESTINATIONORDER_QOS_POLICY_ID
     */
    DDS_DESTINATIONORDER_QOS_POLICY_ID  = 12,
    
    /*e \dref_QosPolicyId_t_HISTORY_QOS_POLICY_ID
     */
    DDS_HISTORY_QOS_POLICY_ID           = 13,
    
    /*e \dref_QosPolicyId_t_RESOURCELIMITS_QOS_POLICY_ID
     */
    DDS_RESOURCELIMITS_QOS_POLICY_ID    = 14,

    /*e \dref_QosPolicyId_t_ENTITYFACTORY_QOS_POLICY_ID
     */
    DDS_ENTITYFACTORY_QOS_POLICY_ID     = 15,

    /*e \dref_QosPolicyId_t_WRITERDATALIFECYCLE_QOS_POLICY_ID
     */
    DDS_WRITERDATALIFECYCLE_QOS_POLICY_ID = 16,

    /*e \dref_QosPolicyId_t_READERDATALIFECYCLE_QOS_POLICY_ID
     */
    DDS_READERDATALIFECYCLE_QOS_POLICY_ID = 17,

    /*e \dref_QosPolicyId_t_TOPICDATA_QOS_POLICY_ID
     */
    DDS_TOPICDATA_QOS_POLICY_ID         = 18,

    /*e \dref_QosPolicyId_t_GROUPDATA_QOS_POLICY_ID
     */
    DDS_GROUPDATA_QOS_POLICY_ID         = 19,

    /*e \dref_QosPolicyId_t_TRANSPORTPRIORITY_QOS_POLICY_ID
     */
    DDS_TRANSPORTPRIORITY_QOS_POLICY_ID = 20,

    /*e \dref_QosPolicyId_t_LIFESPAN_QOS_POLICY_ID
     */
    DDS_LIFESPAN_QOS_POLICY_ID          = 21,
    
    /*e \dref_QosPolicyId_t_DURABILITYSERVICE_QOS_POLICY_ID
     */
    DDS_DURABILITYSERVICE_QOS_POLICY_ID = 22,

    /* --- Extension QoS policies: --- */
    /*i
     * We start at 1000 to allow room for future policies added to 
     * the \dds specification.
     */
    /*e \dref_QosPolicyId_t_WIREPROTOCOL_QOS_POLICY_ID
     */
    DDS_WIREPROTOCOL_QOS_POLICY_ID      = 1000,

    /*e \dref_QosPolicyId_t_DISCOVERY_QOS_POLICY_ID
     */
    DDS_DISCOVERY_QOS_POLICY_ID      = 1001,

    /*e \dref_QosPolicyId_t_DATAREADERRESOURCELIMITS_QOS_POLICY_ID
     */
    DDS_DATAREADERRESOURCELIMITS_QOS_POLICY_ID = 1003,

    /*e \dref_QosPolicyId_t_DATAWRITERRESOURCELIMITS_QOS_POLICY_ID
     */
    DDS_DATAWRITERRESOURCELIMITS_QOS_POLICY_ID = 1004,

    /*e \dref_QosPolicyId_t_DATAREADERPROTOCOL_QOS_POLICY_ID
     */
    DDS_DATAREADERPROTOCOL_QOS_POLICY_ID = 1005,

    /*e \dref_QosPolicyId_t_DATAWRITERPROTOCOL_QOS_POLICY_ID
     */
    DDS_DATAWRITERPROTOCOL_QOS_POLICY_ID = 1006,

    /*e \dref_QosPolicyId_t_DOMAINPARTICIPANTRESOURCELIMITS_QOS_POLICY_ID
     */
    DDS_DOMAINPARTICIPANTRESOURCELIMITS_QOS_POLICY_ID = 1007,

    /*e \dref_QosPolicyId_t_EVENT_QOS_POLICY_ID
     */
    DDS_EVENT_QOS_POLICY_ID = 1008,

    /*e \dref_QosPolicyId_t_DATABASE_QOS_POLICY_ID
     */
    DDS_DATABASE_QOS_POLICY_ID = 1009,

    /*e \dref_QosPolicyId_t_RECEIVERPOOL_QOS_POLICY_ID
     */
    DDS_RECEIVERPOOL_QOS_POLICY_ID = 1010,

    /*e \dref_QosPolicyId_t_DISCOVERYCONFIG_QOS_POLICY_ID
     */
    DDS_DISCOVERYCONFIG_QOS_POLICY_ID = 1011,

    /*e \dref_QosPolicyId_t_EXCLUSIVEAREA_QOS_POLICY_ID
     */
    DDS_EXCLUSIVEAREA_QOS_POLICY_ID = 1012,

    /*i \dref_QosPolicyId_t_USEROBJECT_QOS_POLICY_ID
     */
    DDS_USEROBJECT_QOS_POLICY_ID = 1013,

    /*i \dref_QosPolicyId_t_SYSTEMRESOURCELIMITS_QOS_POLICY_ID
     */
    DDS_SYSTEMRESOURCELIMITS_QOS_POLICY_ID = 1014,

    /*e \dref_QosPolicyId_t_TRANSPORTSELECTION_QOS_POLICY_ID
     */
    DDS_TRANSPORTSELECTION_QOS_POLICY_ID = 1015,
    
    /*e \dref_QosPolicyId_t_TRANSPORTUNICAST_QOS_POLICY_ID
     */
    DDS_TRANSPORTUNICAST_QOS_POLICY_ID = 1016,    

    /*e \dref_QosPolicyId_t_TRANSPORTMULTICAST_QOS_POLICY_ID
     */
    DDS_TRANSPORTMULTICAST_QOS_POLICY_ID = 1017,
    
    /*e \dref_QosPolicyId_t_TRANSPORTBUILTIN_QOS_POLICY_ID
     */
    DDS_TRANSPORTBUILTIN_QOS_POLICY_ID = 1018,

    /*e \dref_QosPolicyId_t_TYPESUPPORT_QOS_POLICY_ID
     */
    DDS_TYPESUPPORT_QOS_POLICY_ID = 1019,

    /*e \dref_QosPolicyId_t_PROPERTY_QOS_POLICY_ID
     */
    DDS_PROPERTY_QOS_POLICY_ID = 1020,

    /*e \dref_QosPolicyId_t_PUBLISHMODE_QOS_POLICY_ID
     */
    DDS_PUBLISHMODE_QOS_POLICY_ID = 1021,

    /*e \dref_QosPolicyId_t_ASYNCHRONOUSPUBLISHER_QOS_POLICY_ID
     */
    DDS_ASYNCHRONOUSPUBLISHER_QOS_POLICY_ID = 1022,

    /*e \dref_QosPolicyId_t_ENTITYNAME_QOS_POLICY_ID
     */
    DDS_ENTITYNAME_QOS_POLICY_ID = 1023,

    /*i \dref_QosPolicyId_t_STATISTICS_QOS_POLICY_ID
     */
    DDS_STATISTICS_QOS_POLICY_ID = 1024,

    /*i \dref_QosPolicyId_t_SERVICE_QOS_POLICY_ID
     */
    DDS_SERVICE_QOS_POLICY_ID = 1025
    
} DDS_QosPolicyId_t;

struct DDS_QosPolicyCount {
    /*e \dref_QosPolicyCount_policy_id
     */
    DDS_QosPolicyId_t policy_id;
    
    /*e \dref_QosPolicyCount_count
     */
    DDS_Long count;
};


DDS_SEQUENCE(DDS_QosPolicyCountSeq, struct DDS_QosPolicyCount);

typedef enum {
    /*e \dref_EntityKind_t_UNKNOWN_ENTITY_KIND
     */
    DDS_UNKNOWN_ENTITY_KIND                 = 0,
    /*e \dref_EntityKind_t_PARTICIPANT_ENTITY_KIND
     */
    DDS_PARTICIPANT_ENTITY_KIND             = 1,
    /*e \dref_EntityKind_t_PUBLISHER_ENTITY_KIND
     */
    DDS_PUBLISHER_ENTITY_KIND               = 2,
    /*e \dref_EntityKind_t_SUBSCRIBER_ENTITY_KIND
     */
    DDS_SUBSCRIBER_ENTITY_KIND              = 3,
    /*e \dref_EntityKind_t_TOPIC_ENTITY_KIND
     */
    DDS_TOPIC_ENTITY_KIND                   = 4,
    /*e \dref_EntityKind_t_DATAREADER_ENTITY_KIND
     */
    DDS_DATAREADER_ENTITY_KIND              = 5,
    /*e \dref_EntityKind_t_DATAWRITER_ENTITY_KIND
     */
    DDS_DATAWRITER_ENTITY_KIND              = 6

} DDS_EntityKind_t;

 extern DDSCDllVariable const char *const
DDS_USERDATA_QOS_POLICY_NAME;


DDSC_VARIABLE_LENGTH_VALUE_TYPE_SUPPORT(DDS_UserDataQosPolicy);

struct DDS_UserDataQosPolicy {
    /*e \dref_UserDataQosPolicy_value
     */
    struct DDS_OctetSeq value;

    DDSCPP_VARIABLE_LENGTH_VALUE_TYPE_SUPPORT(DDS_UserDataQosPolicy)
};


#define DDS_USER_DATA_QOS_POLICY_DEFAULT \
{ DDS_SEQUENCE_INITIALIZER }

 extern DDSCDllVariable const char *const
DDS_TOPICDATA_QOS_POLICY_NAME;


DDSC_VARIABLE_LENGTH_VALUE_TYPE_SUPPORT(DDS_TopicDataQosPolicy);

struct DDS_TopicDataQosPolicy {
    /*e \dref_TopicDataQosPolicy_value
     */
    struct DDS_OctetSeq value;

    DDSCPP_VARIABLE_LENGTH_VALUE_TYPE_SUPPORT(DDS_TopicDataQosPolicy)
};


#define DDS_TOPIC_DATA_QOS_POLICY_DEFAULT { DDS_SEQUENCE_INITIALIZER }

 extern DDSCDllVariable const char *const
DDS_GROUPDATA_QOS_POLICY_NAME;


DDSC_VARIABLE_LENGTH_VALUE_TYPE_SUPPORT(DDS_GroupDataQosPolicy);

struct DDS_GroupDataQosPolicy {
    /*e \dref_GroupDataQosPolicy_value
     */
    struct DDS_OctetSeq value;

    DDSCPP_VARIABLE_LENGTH_VALUE_TYPE_SUPPORT(DDS_GroupDataQosPolicy)
};


#define DDS_GROUP_DATA_QOS_POLICY_DEFAULT { DDS_SEQUENCE_INITIALIZER }

 extern DDSCDllVariable const char *const
DDS_DURABILITY_QOS_POLICY_NAME;

typedef enum {
    /*e \dref_DurabilityQosPolicyKind_VOLATILE_DURABILITY_QOS
     */
    DDS_VOLATILE_DURABILITY_QOS,
    
    /*e \dref_DurabilityQosPolicyKind_TRANSIENT_LOCAL_DURABILITY_QOS
     */
    DDS_TRANSIENT_LOCAL_DURABILITY_QOS,

    /*e \dref_DurabilityQosPolicyKind_TRANSIENT_DURABILITY_QOS
     */
    DDS_TRANSIENT_DURABILITY_QOS,
    
    /*e \dref_DurabilityQosPolicyKind_PERSISTENT_DURABILITY_QOS
     */
    DDS_PERSISTENT_DURABILITY_QOS
} DDS_DurabilityQosPolicyKind;

struct DDS_DurabilityQosPolicy {
    /*e \dref_DurabilityQosPolicy_kind
     */
    DDS_DurabilityQosPolicyKind kind;
    /*e \dref_DurabilityQosPolicy_direct_communication 
    */
    DDS_Boolean direct_communication;
};


#define DDS_DURABILITY_QOS_POLICY_DEFAULT \
{ DDS_VOLATILE_DURABILITY_QOS, \
  RTI_TRUE }

 extern DDSCDllVariable const char *const 
DDS_PRESENTATION_QOS_POLICY_NAME;

typedef enum {
    /*e \dref_PresentationQosPolicyAccessScopeKind_INSTANCE_PRESENTATION_QOS
     */
    DDS_INSTANCE_PRESENTATION_QOS,
    
    /*e \dref_PresentationQosPolicyAccessScopeKind_TOPIC_PRESENTATION_QOS
     */
    DDS_TOPIC_PRESENTATION_QOS,
    
    /*e \dref_PresentationQosPolicyAccessScopeKind_GROUP_PRESENTATION_QOS
     */
    DDS_GROUP_PRESENTATION_QOS
} DDS_PresentationQosPolicyAccessScopeKind;

struct DDS_PresentationQosPolicy {
    /*e \dref_PresentationQosPolicy_access_scope
     */
    DDS_PresentationQosPolicyAccessScopeKind access_scope;
    
    /*e \dref_PresentationQosPolicy_coherent_access
     */
    DDS_Boolean coherent_access;
    
    /*e \dref_PresentationQosPolicy_ordered_access
     */
    DDS_Boolean ordered_access;
};


#define DDS_PRESENTATION_QOS_POLICY_DEFAULT \
{ DDS_INSTANCE_PRESENTATION_QOS, DDS_BOOLEAN_FALSE, DDS_BOOLEAN_FALSE }

 extern DDSCDllVariable const char *const
DDS_DEADLINE_QOS_POLICY_NAME;

struct DDS_DeadlineQosPolicy {
    /*e \dref_DeadlineQosPolicy_period
     */
    struct DDS_Duration_t period;
};


#define DDS_DEADLINE_QOS_POLICY_DEFAULT  \
{{ 0x7fffffffL, 0x7fffffffUL }}

 extern DDSCDllVariable const char *const 
DDS_LATENCYBUDGET_QOS_POLICY_NAME;

struct DDS_LatencyBudgetQosPolicy {
    /*e \dref_LatencyBudgetQosPolicy_duration
     */
    struct DDS_Duration_t duration;
};


#define DDS_LATENCY_BUDGET_QOS_POLICY_DEFAULT { {0L, 0UL} }

 extern DDSCDllVariable const char *const
DDS_OWNERSHIP_QOS_POLICY_NAME;

typedef enum {
    /*e \dref_OwnershipQosPolicyKind_SHARED_OWNERSHIP_QOS
     */
    DDS_SHARED_OWNERSHIP_QOS,
    
    /*e \dref_OwnershipQosPolicyKind_EXCLUSIVE_OWNERSHIP_QOS
     */
    DDS_EXCLUSIVE_OWNERSHIP_QOS
} DDS_OwnershipQosPolicyKind;

struct DDS_OwnershipQosPolicy {
    /*e \dref_OwnershipQosPolicy_kind
     */
    DDS_OwnershipQosPolicyKind kind;
};


#define DDS_OWNERSHIP_QOS_POLICY_DEFAULT \
{ DDS_SHARED_OWNERSHIP_QOS }

 extern DDSCDllVariable const char *const 
DDS_OWNERSHIPSTRENGTH_QOS_POLICY_NAME;

struct DDS_OwnershipStrengthQosPolicy {
    /*e \dref_OwnershipStrengthQosPolicy_value
     */
    DDS_Long value;
};


#define DDS_OWNERSHIP_STRENGTH_QOS_POLICY_DEFAULT { 0L }

 extern DDSCDllVariable const char *const
DDS_LIVELINESS_QOS_POLICY_NAME;

typedef enum {
    /*e \dref_LivelinessQosPolicyKind_AUTOMATIC_LIVELINESS_QOS
     */
    DDS_AUTOMATIC_LIVELINESS_QOS,
    
    /*e \dref_LivelinessQosPolicyKind_MANUAL_BY_PARTICIPANT_LIVELINESS_QOS
     */
    DDS_MANUAL_BY_PARTICIPANT_LIVELINESS_QOS,
    
    /*e \dref_LivelinessQosPolicyKind_MANUAL_BY_TOPIC_LIVELINESS_QOS
     */
    DDS_MANUAL_BY_TOPIC_LIVELINESS_QOS
} DDS_LivelinessQosPolicyKind;

struct DDS_LivelinessQosPolicy {
    /*e \dref_LivelinessQosPolicy_kind
     */
    DDS_LivelinessQosPolicyKind kind;
    
    /*e \dref_LivelinessQosPolicy_lease_duration
     */
    struct DDS_Duration_t lease_duration;
};


#define DDS_LIVELINESS_QOS_POLICY_DEFAULT \
{ DDS_AUTOMATIC_LIVELINESS_QOS, {0x7fffffff, 0x7fffffffUL}}

 extern DDSCDllVariable const char *const 
DDS_TIMEBASEDFILTER_QOS_POLICY_NAME;

struct DDS_TimeBasedFilterQosPolicy {
    /*e \dref_TimeBasedFilterQosPolicy_minimum_separation
    */
    struct DDS_Duration_t minimum_separation;
};


#define DDS_TIME_BASED_FILTER_QOS_POLICY_DEFAULT { {0L, 0UL} }

 extern DDSCDllVariable const char *const
DDS_PARTITION_QOS_POLICY_NAME;


DDSC_VARIABLE_LENGTH_VALUE_TYPE_SUPPORT(DDS_PartitionQosPolicy); 

/*e \dref_PartitionQosPolicy
 */
struct DDS_PartitionQosPolicy {
    /*e \dref_PartitionQosPolicy_name
     */
    struct DDS_StringSeq name;
 
    DDSCPP_VARIABLE_LENGTH_VALUE_TYPE_SUPPORT(DDS_PartitionQosPolicy)
};


#define DDS_PARTITION_QOS_POLICY_DEFAULT { DDS_SEQUENCE_INITIALIZER }

 extern DDSCDllVariable const char *const
DDS_RELIABILITY_QOS_POLICY_NAME;

typedef enum {
    /*e \dref_ReliabilityQosPolicyKind_BEST_EFFORT_RELIABILITY_QOS
     */
    DDS_BEST_EFFORT_RELIABILITY_QOS,
    
    /*e \dref_ReliabilityQosPolicyKind_RELIABLE_RELIABILITY_QOS
     */
    DDS_RELIABLE_RELIABILITY_QOS
} DDS_ReliabilityQosPolicyKind;

struct DDS_ReliabilityQosPolicy {
    /*e \dref_ReliabilityQosPolicy_kind
     */
    DDS_ReliabilityQosPolicyKind kind;
    /*e \dref_ReliabilityQosPolicy_max_blocking_time
     */
    struct DDS_Duration_t max_blocking_time;
};


#define DDS_RELIABILITY_QOS_POLICY_DEFAULT \
          { DDS_BEST_EFFORT_RELIABILITY_QOS, \
          {0L, 100000000UL} }

 extern DDSCDllVariable const char *const 
DDS_DESTINATIONORDER_QOS_POLICY_NAME;

typedef enum {
    /*e \dref_DestinationOrderQosPolicyKind_BY_RECEPTION_TIMESTAMP_DESTINATIONORDER_QOS
     */
    DDS_BY_RECEPTION_TIMESTAMP_DESTINATIONORDER_QOS,

    /*e \dref_DestinationOrderQosPolicyKind_BY_SOURCE_TIMESTAMP_DESTINATIONORDER_QOS
     */
    DDS_BY_SOURCE_TIMESTAMP_DESTINATIONORDER_QOS

} DDS_DestinationOrderQosPolicyKind;

typedef enum {
    /*e \dref_DestinationOrderQosPolicyScopeKind_INSTANCE_SCOPE_DESTINATIONORDER_QOS
     */
    DDS_INSTANCE_SCOPE_DESTINATIONORDER_QOS,

    /*e \dref_DestinationOrderQosPolicyScopeKind_TOPIC_SCOPE_DESTINATIONORDER_QOS
     */
    DDS_TOPIC_SCOPE_DESTINATIONORDER_QOS
} DDS_DestinationOrderQosPolicyScopeKind;

struct DDS_DestinationOrderQosPolicy {
    /*e \dref_DestinationOrderQosPolicy_kind
     */
    DDS_DestinationOrderQosPolicyKind kind;
    DDS_DestinationOrderQosPolicyScopeKind scope;
};


#define DDS_DESTINATION_ORDER_QOS_POLICY_DEFAULT \
{ DDS_BY_RECEPTION_TIMESTAMP_DESTINATIONORDER_QOS, \
  DDS_INSTANCE_SCOPE_DESTINATIONORDER_QOS }

 extern DDSCDllVariable const char *const
DDS_HISTORY_QOS_POLICY_NAME;

typedef enum {
    /*e \dref_HistoryQosPolicyKind_KEEP_LAST_HISTORY_QOS
     */
    DDS_KEEP_LAST_HISTORY_QOS,
    
    /*e \dref_HistoryQosPolicyKind_KEEP_ALL_HISTORY_QOS
     */
    DDS_KEEP_ALL_HISTORY_QOS

} DDS_HistoryQosPolicyKind;

typedef enum {
    /*e \dref_RefilterQosPolicyKind_NONE_REFILTER_QOS
     */
    DDS_NONE_REFILTER_QOS,
    
    /*e \dref_RefilterQosPolicyKind_ALL_REFILTER_QOS
     */
    DDS_ALL_REFILTER_QOS,

    /*e \dref_RefilterQosPolicyKind_ON_DEMAND_REFILTER_QOS
     */
    DDS_ON_DEMAND_REFILTER_QOS

} DDS_RefilterQosPolicyKind;

struct DDS_HistoryQosPolicy {
    /*e \dref_HistoryQosPolicy_kind
     */
    DDS_HistoryQosPolicyKind kind;
    
    /*e \dref_HistoryQosPolicy_depth
     */
    DDS_Long depth;

   /*e \dref_HistoryQosPolicy_refilter
    */
    DDS_RefilterQosPolicyKind refilter;
};


#define DDS_HISTORY_QOS_POLICY_DEFAULT { DDS_KEEP_LAST_HISTORY_QOS, \
                                         1L, /* depth */\
                                         DDS_NONE_REFILTER_QOS }


 extern DDSCDllVariable const char *const 
DDS_DURABILITYSERVICE_QOS_POLICY_NAME;

struct DDS_DurabilityServiceQosPolicy {
    /*e \dref_DurabilityServiceQosPolicy_service_cleanup_delay */
    struct DDS_Duration_t service_cleanup_delay;

    /*e \dref_DurabilityServiceQosPolicy_history_kind */
    DDS_HistoryQosPolicyKind history_kind;

    /*e \dref_DurabilityServiceQosPolicy_history_depth */
    DDS_Long history_depth;

    /*e \dref_DurabilityServiceQosPolicy_max_samples */
    DDS_Long max_samples;

    /*e \dref_DurabilityServiceQosPolicy_max_instances */
    DDS_Long max_instances;

    /*e \dref_DurabilityServiceQosPolicy_max_samples_per_instance */
    DDS_Long max_samples_per_instance;
};


#define DDS_DURABILITY_SERVICE_QOS_POLICY_DEFAULT { \
  {0L, 0UL}, /* service_cleanup_delay */        \
  DDS_KEEP_LAST_HISTORY_QOS, 1L, /* history_kind and depth */ \
  -1L, -1L, -1L /* resource_limits */ \
}

 extern DDSCDllVariable const char *const 
DDS_RESOURCELIMITS_QOS_POLICY_NAME;

 extern DDSCDllVariable const DDS_Long DDS_LENGTH_UNLIMITED;

struct DDS_ResourceLimitsQosPolicy {
    /*e \dref_ResourceLimitsQosPolicy_max_samples
     */
    DDS_Long max_samples;
    
    /*e \dref_ResourceLimitsQosPolicy_max_instances
     */
    DDS_Long max_instances;
    
    /*e \dref_ResourceLimitsQosPolicy_max_samples_per_instance
     */
    DDS_Long max_samples_per_instance;

    /*e \dref_ResourceLimitsQosPolicy_initial_samples
     */
    DDS_Long initial_samples;
    
    /*e \dref_ResourceLimitsQosPolicy_initial_instances
     */
    DDS_Long initial_instances;
};


#define DDS_RESOURCE_LIMITS_QOS_POLICY_DEFAULT { \
    -1L, /* max_samples */ \
    -1L, /* max_instances */ \
    -1L, /* max_samples_per_instance */ \
    32L, /* initial_samples */ \
    32L /* initial_instances */ \
}

 extern DDSCDllVariable const char *const 
DDS_TRANSPORTPRIORITY_QOS_POLICY_NAME;

struct DDS_TransportPriorityQosPolicy {
    /*e \dref_TransportPriorityQosPolicy_value
     */
    DDS_Long value;
};


#define DDS_TRANSPORT_PRIORITY_QOS_POLICY_DEFAULT   {0L}

 extern DDSCDllVariable const char *const 
DDS_LIFESPAN_QOS_POLICY_NAME;

struct DDS_LifespanQosPolicy {
    /*e \dref_LifespanQosPolicy_duration
    */
    struct DDS_Duration_t duration;
};


#define DDS_LIFESPAN_QOS_POLICY_DEFAULT {{0x7fffffff, 0x7fffffffUL}}

 extern DDSCDllVariable const char *const 
DDS_WRITERDATALIFECYCLE_QOS_POLICY_NAME;

struct DDS_WriterDataLifecycleQosPolicy {
    /*e \dref_WriterDataLifecycleQosPolicy_autodispose_unregistered_instances
     */
    DDS_Boolean autodispose_unregistered_instances;
};


#define DDS_WRITER_DATA_LIFECYCLE_QOS_POLICY_DEFAULT   { DDS_BOOLEAN_TRUE }

 extern DDSCDllVariable const char *const 
DDS_READERDATALIFECYCLE_QOS_POLICY_NAME;

struct DDS_ReaderDataLifecycleQosPolicy {
    /*e \dref_ReaderDataLifecycleQosPolicy_autopurge_nowriter_samples_delay
     */
    struct DDS_Duration_t autopurge_nowriter_samples_delay;
    /*e \dref_ReaderDataLifecycleQosPolicy_autopurge_disposed_samples_delay
     */
    struct DDS_Duration_t autopurge_disposed_samples_delay;
};


#define DDS_READER_DATA_LIFECYCLE_QOS_POLICY_DEFAULT \
{ {0x7fffffffL, 0x7fffffffUL}, \
  {0x7fffffffL, 0x7fffffffUL}}

 extern DDSCDllVariable const char *const 
DDS_ENTITYFACTORY_QOS_POLICY_NAME;

struct DDS_EntityFactoryQosPolicy {
    /*e \dref_EntityFactoryQosPolicy_autoenable_created_entities
     */
    DDS_Boolean autoenable_created_entities;
};


#define DDS_ENTITY_FACTORY_QOS_POLICY_DEFAULT   { DDS_BOOLEAN_TRUE }

struct DDS_AllocationSettings_t {
    /*e \dref_AllocationSettings_t_initial_count
     */
    DDS_Long initial_count;

    /*e \dref_AllocationSettings_t_max_count
     */
    DDS_Long max_count;

    /*e \dref_AllocationSettings_t_incremental_count
     */
    DDS_Long incremental_count;
};

extern DDSCDllExport void
DDS_AllocationSettings_add(
        struct DDS_AllocationSettings_t* answer,
        struct DDS_AllocationSettings_t* left,
        struct DDS_AllocationSettings_t* right);

struct DDS_RtpsReliableReaderProtocol_t {
    /*e \dref_RtpsReliableReaderProtocol_t_min_heartbeat_response_delay
     */
    struct DDS_Duration_t min_heartbeat_response_delay;

    /*e \dref_RtpsReliableReaderProtocol_t_max_heartbeat_response_delay
     */
    struct DDS_Duration_t max_heartbeat_response_delay;

    /*e \dref_RtpsReliableReaderProtocol_t_heartbeat_suppression_duration
     */
    struct DDS_Duration_t heartbeat_suppression_duration;
};


#define DDS_RTPS_RELIABLE_READER_PROTOCOL_DEFAULT \
{{0L, 0UL}, {0L, 500000000UL}, \
 {0, 62500 * 1000} /* heartbeat_suppression_duration */ }


#define DDS_RTPS_RELIABLE_READER_PROTOCOL_DISCOVERY_CONFIG_DEFAULT \
{{0L, 0UL}, {0L, 0UL}, \
 {0, 62500 * 1000} /* heartbeat_suppression_duration */}

struct DDS_RtpsReliableWriterProtocol_t {
    /*e \dref_RtpsReliableWriterProtocol_t_low_watermark
     */
    DDS_Long low_watermark;
    
    /*e \dref_RtpsReliableWriterProtocol_t_high_watermark
     */
    DDS_Long high_watermark;
    
    /*e \dref_RtpsReliableWriterProtocol_t_heartbeat_period
     */
    struct DDS_Duration_t heartbeat_period;
    
    /*e \dref_RtpsReliableWriterProtocol_t_fast_heartbeat_period
     */
    struct DDS_Duration_t fast_heartbeat_period;

    /*e \dref_RtpsReliableWriterProtocol_t_late_joiner_heartbeat_period
     */
    struct DDS_Duration_t late_joiner_heartbeat_period;

    /*e \dref_RtpsReliableWriterProtocol_t_max_heartbeat_retries
     */
    DDS_Long max_heartbeat_retries;
    
    /*e \dref_RtpsReliableWriterProtocol_t_heartbeats_per_max_samples
     */
    DDS_Long heartbeats_per_max_samples;
    
    /*e \dref_RtpsReliableWriterProtocol_t_min_nack_response_delay
     */
    struct DDS_Duration_t min_nack_response_delay;

    /*e \dref_RtpsReliableWriterProtocol_t_max_nack_response_delay
     */
    struct DDS_Duration_t max_nack_response_delay;

    /*e \dref_RtpsReliableWriterProtocol_t_nack_suppression_duration
     */
    struct DDS_Duration_t nack_suppression_duration;

    /*e \dref_RtpsReliableWriterProtocol_t_max_bytes_per_nack_response
     */
    DDS_Long max_bytes_per_nack_response;
};


#define DDS_RTPS_RELIABLE_WRITER_PROTOCOL_DEFAULT { \
    /*watermarks*/ 0, 1,                 \
    /*hb periods*/ {3, 0}, {3, 0}, {3, 0},  \
    /*hb retries*/ 10,                   \
    /*hb/queue*/   8,                    \
    /*delays*/     {0L, 0UL}, {0L, 200000000UL}, \
    /* nackSuppressionDuration */ {0, 0}, \
    /*B/response*/ 131072                \
}


#define DDS_RTPS_RELIABLE_WRITER_PROTOCOL_DISCOVERY_CONFIG_DEFAULT { \
    /*watermarks*/ 0, 1,                 \
    /*hb periods*/ {3, 0}, {3, 0}, {3, 0},  \
    /*lj-priority*/ /* DDS_BOOLEAN_TRUE, */ \
    /*hb retries*/ 10,                   \
    /*hb/queue*/   8,                    \
    /*delays*/     {0L, 0UL}, {0L, 0UL}, \
    /*nackSuppressionDuration */ {0, 0}, \
    /*B/response*/ 131072                \
}

struct DDS_UserObjectSettings_t {
    /*i \dref_UserObjectSettings_t_size
     */
    DDS_Long size;
    /*i \dref_UserObjectSettings_t_alignment
     */
    DDS_Long alignment;
};


DDSC_VARIABLE_LENGTH_VALUE_TYPE_SUPPORT(DDS_TransportUnicastSettings_t);


#if defined(RTI_WIN32) || defined(RTI_WINCE)
#pragma warning(push)
#pragma warning(disable:4190)
#endif /* RTI_WIN32 || RTI_WINCE */

struct DDS_TransportUnicastSettings_t {

    /*e \dref_TransportUnicastSettings_t_transports
     */
    struct DDS_StringSeq transports;    

    /*e \dref_TransportUnicastSettings_t_receive_port
     */
    DDS_Long receive_port;
    
    DDSCPP_VARIABLE_LENGTH_VALUE_TYPE_SUPPORT(DDS_TransportUnicastSettings_t)
};


DDS_SEQUENCE(DDS_TransportUnicastSettingsSeq, struct DDS_TransportUnicastSettings_t);
#if defined(RTI_WIN32) || defined(RTI_WINCE)
/* restore extern "C"-related warning */
#pragma warning(pop)
#endif /* RTI_WIN32 || RTI_WINCE */


DDSC_VARIABLE_LENGTH_VALUE_TYPE_SUPPORT(DDS_TransportMulticastSettings_t); 


#define DDS_TRANSPORT_MULTICAST_LOCATORS_DEFAULT \
{ DDS_SEQUENCE_INITIALIZER /* transports */, \
  NULL, /* receive_address_string */ \
  0 /* receive_port */ }


#if defined(RTI_WIN32) || defined(RTI_WINCE)
#pragma warning(push)
#pragma warning(disable:4190)
#endif /* RTI_WIN32 || RTI_WINCE */

struct DDS_TransportMulticastSettings_t {
    /*e \dref_TransportMulticastSettings_t_transports
    */
    struct DDS_StringSeq transports;

    /*e \dref_TransportMulticastSettings_t_receive_address
    */
    char* receive_address;
    
    /*e \dref_TransportMulticastSettings_t_receive_port 
    */
    DDS_Long receive_port;

    DDSCPP_VARIABLE_LENGTH_VALUE_TYPE_SUPPORT(DDS_TransportMulticastSettings_t)
};


DDS_SEQUENCE(DDS_TransportMulticastSettingsSeq, struct DDS_TransportMulticastSettings_t);
#if defined(RTI_WIN32) || defined(RTI_WINCE)
/* restore extern "C"-related warning */
#pragma warning(pop)
#endif /* RTI_WIN32 || RTI_WINCE */

 extern DDSCDllVariable const char *const
DDS_TRANSPORTSELECTION_QOS_POLICY_NAME;


DDSC_VARIABLE_LENGTH_VALUE_TYPE_SUPPORT(DDS_TransportSelectionQosPolicy); 

/*e \dref_TransportSelectionQosPolicy 
 */
struct DDS_TransportSelectionQosPolicy {
    /*e \dref_TransportSelectionQosPolicy_enabled_transports 
     */
    struct DDS_StringSeq enabled_transports;

    DDSCPP_VARIABLE_LENGTH_VALUE_TYPE_SUPPORT(DDS_TransportSelectionQosPolicy)
};


#define DDS_TRANSPORT_SELECTION_QOS_POLICY_DEFAULT \
{ DDS_SEQUENCE_INITIALIZER }

 extern DDSCDllVariable const char *const
DDS_TRANSPORTUNICAST_QOS_POLICY_NAME;


DDSC_VARIABLE_LENGTH_VALUE_TYPE_SUPPORT(DDS_TransportUnicastQosPolicy);

struct DDS_TransportUnicastQosPolicy {
    /*e \dref_TransportUnicastQosPolicy_value
     */
    struct DDS_TransportUnicastSettingsSeq value;
    
    DDSCPP_VARIABLE_LENGTH_VALUE_TYPE_SUPPORT(DDS_TransportUnicastQosPolicy)
};


#define DDS_TRANSPORT_UNICAST_QOS_POLICY_DEFAULT \
{ DDS_SEQUENCE_INITIALIZER }

 extern DDSCDllVariable const char *const
DDS_TRANSPORTMULTICAST_QOS_POLICY_NAME;


DDSC_VARIABLE_LENGTH_VALUE_TYPE_SUPPORT(DDS_TransportMulticastQosPolicy);

struct DDS_TransportMulticastQosPolicy {
    /*e \dref_TransportMulticastQosPolicy_value
     */
    struct DDS_TransportMulticastSettingsSeq value;
    
    DDSCPP_VARIABLE_LENGTH_VALUE_TYPE_SUPPORT(DDS_TransportMulticastQosPolicy)
};


#define DDS_TRANSPORT_MULTICAST_QOS_POLICY_DEFAULT \
        { DDS_SEQUENCE_INITIALIZER }

 extern DDSCDllVariable const char *const
DDS_DISCOVERY_QOS_POLICY_NAME;


DDSC_VARIABLE_LENGTH_VALUE_TYPE_SUPPORT(DDS_DiscoveryQosPolicy); 

struct DDS_DiscoveryQosPolicy {
    /*e \dref_DiscoveryQosPolicy_enabled_transports
     */
    struct DDS_StringSeq enabled_transports;

    /*e \dref_DiscoveryQosPolicy_multicast_receive_addresses
     */
    struct DDS_StringSeq initial_peers;

    /*e \dref_DiscoveryQosPolicy_multicast_receive_addresses
     */
    struct DDS_StringSeq multicast_receive_addresses;

    /*e \dref_DiscoveryQosPolicy_metatraffic_transport_priority
     */
    DDS_Long metatraffic_transport_priority;

    /*e \dref_DiscoveryQosPolicy_accept_unknown_peers
     */
    DDS_Boolean accept_unknown_peers;

    DDSCPP_VARIABLE_LENGTH_VALUE_TYPE_SUPPORT(DDS_DiscoveryQosPolicy)
};


#define DDS_DISCOVERY_QOS_POLICY_DEFAULT { \
DDS_SEQUENCE_INITIALIZER, /* enabled_transports */\
DDS_SEQUENCE_INITIALIZER, /* initial_peers */\
DDS_SEQUENCE_INITIALIZER, /* multicast_receive_addresses */\
0L, /* metatraffic_transport_priority */\
DDS_BOOLEAN_TRUE /* accept_unknown_peers */\
}


DDSC_VARIABLE_LENGTH_VALUE_TYPE_SUPPORT(DDS_Discovery_ParticipantInformation);


#if defined(RTI_WIN32) || defined(RTI_WINCE)
#pragma warning(push)
#pragma warning(disable:4190)
#endif /* RTI_WIN32 || RTI_WINCE */

struct DDS_Discovery_ParticipantInformation {
    /*i \dref_Discovery_ParticipantInformation_participant_discovery_id
     */
    DDS_Long participant_discovery_id;

    /*i \dref_Discovery_ParticipantInformation_participant_discovery_version
 */
    DDS_Long participant_discovery_version;

    /*i \dref_Discovery_ParticipantInformation_participant_discovery_vendor_id
 */
    DDS_Long participant_discovery_vendor_id;

    /*i \dref_Discovery_ParticipantInformation_participant_discovery_parameters
 */
    struct DDS_OctetSeq participant_discovery_parameters;

    DDSCPP_VARIABLE_LENGTH_VALUE_TYPE_SUPPORT(DDS_Discovery_ParticipantInformation)
};


DDS_SEQUENCE(DDS_Discovery_ParticipantInformationSeq, struct DDS_Discovery_ParticipantInformation);
#if defined(RTI_WIN32) || defined(RTI_WINCE)
/* restore extern "C"-related warning */
#pragma warning(pop)
#endif /* RTI_WIN32 || RTI_WINCE */


DDSC_VARIABLE_LENGTH_VALUE_TYPE_SUPPORT(DDS_Discovery_EndpointInformation);


#if defined(RTI_WIN32) || defined(RTI_WINCE)
#pragma warning(push)
#pragma warning(disable:4190)
#endif /* RTI_WIN32 || RTI_WINCE */

struct DDS_Discovery_EndpointInformation {
    /*i \dref_Discovery_EndpointInformation_endpoint_discovery_id
     */
    DDS_Long endpoint_discovery_id;

    /*i \dref_Discovery_EndpointInformation_endpoint_discovery_version
     */    
    DDS_Long endpoint_discovery_version;
        
    /*i \dref_Discovery_EndpointInformation_endpoint_discovery_vendor_id
     */
    DDS_Long endpoint_discovery_vendor_id;
    
    /*i \dref_Discovery_EndpointInformation_endpoint_discovery_parameters
     */
    struct DDS_OctetSeq endpoint_discovery_parameters;
    
    DDSCPP_VARIABLE_LENGTH_VALUE_TYPE_SUPPORT(DDS_Discovery_EndpointInformation)
};


DDS_SEQUENCE(DDS_Discovery_EndpointInformationSeq, struct DDS_Discovery_EndpointInformation);
#if defined(RTI_WIN32) || defined(RTI_WINCE)
/* restore extern "C"-related warning */
#pragma warning(pop)
#endif /* RTI_WIN32 || RTI_WINCE */

 extern DDSCDllVariable const char *const
DDS_TRANSPORTBUILTIN_QOS_POLICY_NAME;

typedef enum {
    /*e \dref_TransportBuiltinKind_TRANSPORTBUILTIN_UDPv4
     */
    DDS_TRANSPORTBUILTIN_UDPv4 = 0x0001 << 0,
    
    /*e \dref_TransportBuiltinKind_TRANSPORTBUILTIN_SHMEM
     */
    DDS_TRANSPORTBUILTIN_SHMEM = 0x0001 << 1, 
    
    /*i \dref_TransportBuiltinKind_INTRA
     */
    DDS_TRANSPORTBUILTIN_INTRA = 0x0001 << 2,
    
    /*e \dref_TransportBuiltinKind_TRANSPORTBUILTIN_UDPv6
     */
    DDS_TRANSPORTBUILTIN_UDPv6 = 0x0001 << 3
    
} DDS_TransportBuiltinKind;

 extern DDSCDllVariable const char *const
DDS_TRANSPORTBUILTIN_INTRA_ALIAS;

 extern DDSCDllVariable const char *const
DDS_TRANSPORTBUILTIN_SHMEM_ALIAS;

 extern DDSCDllVariable const char *const
DDS_TRANSPORTBUILTIN_UDPv4_ALIAS;

 extern DDSCDllVariable const char *const
DDS_TRANSPORTBUILTIN_UDPv6_ALIAS;

typedef DDS_Long DDS_TransportBuiltinKindMask;


#define DDS_TRANSPORTBUILTIN_MASK_NONE  ((DDS_TransportBuiltinKindMask) 0)


#define DDS_TRANSPORTBUILTIN_MASK_DEFAULT (DDS_TRANSPORTBUILTIN_UDPv4 | DDS_TRANSPORTBUILTIN_SHMEM)


#define DDS_TRANSPORTBUILTIN_MASK_ALL   (~DDS_TRANSPORTBUILTIN_MASK_NONE)

struct DDS_TransportBuiltinQosPolicy {
    /*e \dref_TransportBuiltinQosPolicy_mask   
     */
    DDS_TransportBuiltinKindMask mask;
};


#define DDS_TRANSPORT_BUILTIN_QOS_POLICY_DEFAULT \
        { DDS_TRANSPORTBUILTIN_MASK_DEFAULT }

struct DDS_RtpsWellKnownPorts_t {
    /*e \dref_RtpsWellKnownPorts_t_port_base
     */
    DDS_Long port_base;
    /*e \dref_RtpsWellKnownPorts_t_domain_id_gain
     */
    DDS_Long domain_id_gain;

    /*e \dref_RtpsWellKnownPorts_t_participant_id_gain
     */
    DDS_Long participant_id_gain;

    /*e \dref_RtpsWellKnownPorts_t_builtin_multicast_port_offset
     */
    DDS_Long builtin_multicast_port_offset;

    /*e \dref_RtpsWellKnownPorts_t_builtin_unicast_port_offset
     */
    DDS_Long builtin_unicast_port_offset;

    /*e \dref_RtpsWellKnownPorts_t_user_multicast_port_offset
     */
    DDS_Long user_multicast_port_offset;

    /*e \dref_RtpsWellKnownPorts_t_user_unicast_port_offset
     */
    DDS_Long user_unicast_port_offset;
};

 extern DDSCDllVariable 
struct DDS_RtpsWellKnownPorts_t DDS_RTI_BACKWARDS_COMPATIBLE_RTPS_WELL_KNOWN_PORTS;

 extern DDSCDllVariable 
struct DDS_RtpsWellKnownPorts_t DDS_INTEROPERABLE_RTPS_WELL_KNOWN_PORTS;


#define DDS_RTPS_WELL_KNOWN_PORTS_DEFAULT \
{ \
    7400, /* port_base */ \
    250, /* domain_id_gain */ \
    2, /* participant_id_gain */ \
    0, /* builtin_multicast_port_offset */ \
    10, /* builtin_unicast_port_offset */ \
    1, /* user_multicast_port_offset */ \
    11 /* user_unicast_port_offset */ \
}

 extern DDSCDllVariable const char *const 
DDS_WIREPROTOCOL_QOS_POLICY_NAME;

struct DDS_WireProtocolQosPolicy {
    /*e \dref_WireProtocolQosPolicy_participant_id
     */
    DDS_Long participant_id;
    /*e \dref_WireProtocolQosPolicy_rtps_host_id
     */
    DDS_UnsignedLong rtps_host_id;

    /*e \dref_WireProtocolQosPolicy_rtps_app_id
     */
    DDS_UnsignedLong rtps_app_id;

    /*e \dref_WireProtocolQosPolicy_rtps_instance_id
    */
    DDS_UnsignedLong rtps_instance_id;
    /*e \dref_WireProtocolQosPolicy_rtps_well_known_ports
     */
    struct DDS_RtpsWellKnownPorts_t rtps_well_known_ports;
};


/*e \dref_WireProtocolQosPolicy_RTPS_AUTO_ID
 */
 enum {
    /*e \dref_WireProtocolQosPolicy_RTPS_AUTO_ID
    */
    DDS_RTPS_AUTO_ID = 0
};


#define DDS_WIRE_PROTOCOL_QOS_POLICY_DEFAULT {      \
-1 /* auto participant_id */,                       \
DDS_RTPS_AUTO_ID /* rtps_host_id */,                \
DDS_RTPS_AUTO_ID /* rtps_app_id */,                 \
DDS_RTPS_AUTO_ID /* rtps_instance_id */,            \
DDS_RTPS_WELL_KNOWN_PORTS_DEFAULT /* rtps_well_known_ports */\
}


#define DDS_LOCATOR_ADDRESS_LENGTH_MAX 16

struct DDS_Locator_t {
    /*e \dref_Locator_t_kind
     */
    DDS_Long kind;
    /*e \dref_Locator_t_port
     */
    DDS_UnsignedLong port;
    /*e \dref_Locator_t_address
     */
    DDS_Octet address[DDS_LOCATOR_ADDRESS_LENGTH_MAX];    
};


DDS_SEQUENCE(DDS_LocatorSeq, struct DDS_Locator_t);

 extern DDSCDllVariable const struct DDS_Locator_t DDS_LOCATOR_INVALID;

 extern DDSCDllVariable const DDS_Long DDS_LOCATOR_KIND_INVALID;

 extern DDSCDllVariable const DDS_UnsignedLong DDS_LOCATOR_PORT_INVALID;

 extern DDSCDllVariable const DDS_Octet DDS_LOCATOR_ADDRESS_INVALID[DDS_LOCATOR_ADDRESS_LENGTH_MAX];

 extern DDSCDllVariable const DDS_Long DDS_LOCATOR_KIND_UDPv4;

 extern DDSCDllVariable const DDS_Long DDS_LOCATOR_KIND_UDPv6;

 extern DDSCDllVariable const DDS_Long DDS_LOCATOR_KIND_RESERVED;

 extern DDSCDllVariable const DDS_Long DDS_LOCATOR_KIND_SHMEM;

typedef struct DDS_ProtocolVersion_t {
    /*e \dref_ProtocolVersion_t_major
     */
    DDS_Octet major;

    /*e \dref_ProtocolVersion_t_minor
     */
    DDS_Octet minor;
} DDS_ProtocolVersion_t;


#define DDS_PROTOCOL_VERSION_DEFAULT { 0, 0 }


  /*e \dref_ProtocolVersion_t_PROTOCOLVERSION_1_0
   */
  #define DDS_PROTOCOLVERSION_1_0 { 1, 0 }
  /*e \dref_ProtocolVersion_t_PROTOCOLVERSION_1_1
   */
  #define DDS_PROTOCOLVERSION_1_1 { 1, 1 }
  /*e \dref_ProtocolVersion_t_PROTOCOLVERSION_1_2
   */
  #define DDS_PROTOCOLVERSION_1_2 { 1, 2 }
  /*e \dref_ProtocolVersion_t_PROTOCOLVERSION_2_0
   */
  #define DDS_PROTOCOLVERSION_2_0 { 2, 0 }
  /*e \dref_ProtocolVersion_t_PROTOCOLVERSION_2_1
   */
  #define DDS_PROTOCOLVERSION_2_1 { 2, 1 }
  /*e \dref_ProtocolVersion_t_PROTOCOLVERSION
   */
  #define DDS_PROTOCOLVERSION { 2, 1 }


#define DDS_VENDOR_ID_LENGTH_MAX 2

struct DDS_VendorId_t {
    /*e \dref_VendorId_t_vendorId
     */
    DDS_Octet vendorId[DDS_VENDOR_ID_LENGTH_MAX];
};


  #define DDS_VENDOR_ID_DEFAULT { {0, 0} }


  /*i \dref_VendorId_t_VENDORID_UNKNOWN
   */
  #define DDS_VENDORID_UNKNOWN { {0, 0} }  

struct DDS_ProductVersion_t {
    /*e \dref_ProductVersion_t_major
     */
    DDS_Char major;
    /*e \dref_ProductVersion_t_minor
     */
    DDS_Char minor;
    /*e \dref_ProductVersion_t_release
     */
    DDS_Char release;
    /*e \dref_ProductVersion_t_revision
     */
    DDS_Char revision;
};


  /*e \dref_ProductVersion_t_UNKNOWN
   */
  #define DDS_PRODUCTVERSION_UNKNOWN { 0, 0, '0', 0 }  

 extern DDSCDllVariable const char *const
DDS_DATAREADERRESOURCELIMITS_QOS_POLICY_NAME;

struct DDS_DataReaderResourceLimitsQosPolicy {
    /*e \dref_DataReaderResourceLimitsQosPolicy_max_remote_writers
     */
    DDS_Long    max_remote_writers;
    
    /*e \dref_DataReaderResourceLimitsQosPolicy_max_remote_writers_per_instance
     */
    DDS_Long    max_remote_writers_per_instance;

    /*e \dref_DataReaderResourceLimitsQosPolicy_max_samples_per_remote_writer
     */
    DDS_Long    max_samples_per_remote_writer;

    /*e \dref_DataReaderResourceLimitsQosPolicy_max_infos
     */
    DDS_Long    max_infos;

    /*e \dref_DataReaderResourceLimitsQosPolicy_initial_remote_writers
     */
    DDS_Long    initial_remote_writers;

    /*e \dref_DataReaderResourceLimitsQosPolicy_initial_remote_writers_per_instance
     */
    DDS_Long    initial_remote_writers_per_instance;

    /*e \dref_DataReaderResourceLimitsQosPolicy_initial_infos
     */
    DDS_Long    initial_infos;

    /*e \dref_DataReaderResourceLimitsQosPolicy_initial_outstanding_reads
     */
    DDS_Long    initial_outstanding_reads;

    /*e \dref_DataReaderResourceLimitsQosPolicy_max_outstanding_reads
     */
    DDS_Long    max_outstanding_reads;

    /*e \dref_DataReaderResourceLimitsQosPolicy_max_samples_per_read
     */
    DDS_Long max_samples_per_read;

    /*e \dref_DataReaderResourceLimitsQosPolicy_disable_fragmentation_support
     */
    DDS_Boolean disable_fragmentation_support;

    /*e \dref_DataReaderResourceLimitsQosPolicy_max_fragmented_samples
     */
    DDS_Long max_fragmented_samples;

    /*e \dref_DataReaderResourceLimitsQosPolicy_initial_fragmented_samples
     */
    DDS_Long initial_fragmented_samples;

    /*e \dref_DataReaderResourceLimitsQosPolicy_max_fragmented_samples_per_remote_writer
     */
    DDS_Long max_fragmented_samples_per_remote_writer;

    /*e \dref_DataReaderResourceLimitsQosPolicy_max_fragments_per_sample
     */
    DDS_Long max_fragments_per_sample;

    /*e \dref_DataReaderResourceLimitsQosPolicy_dynamically_allocate_fragmented_samples
     */
    DDS_Boolean dynamically_allocate_fragmented_samples;
};


#define DDS_DATA_READER_RESOURCE_LIMITS_QOS_POLICY_DEFAULT { \
    -1L,/* max_remote_writers: was 1024 before introduction of unlimited */ \
    -1L,/* max_remote_writers_per_instance: was 1024 before introduction of unlimited */ \
    -1L,/* max_samples_per_remote_writer: was 256 before introduction of unlimited */ \
    -1L,/* max_infos: was 100000 before introduction of unlimited */ \
    2L,/* initial_remote_writers */ \
    2L,/* initial_remote_writers_per_instance */ \
    32L,/* initial_infos */ \
    2L,/* initial_outstanding_reads */ \
    -1L,/* max_outstanding_reads: was 1024 before introduction of unlimited */ \
    1024L,/* max_samples_per_read: must never be unlimited */ \
    DDS_BOOLEAN_FALSE,/*disable_fragmentation_support: */ \
    1024L,/* max_fragmented_samples: */ \
    4L,/* initial_fragmented_samples: */ \
    256L,/* max_fragmented_samples_per_remote_writer: */ \
    512L,/* max_fragments_per_sample: */ \
    DDS_BOOLEAN_FALSE/* dynamically_allocate_fragmented_samples */ \
}

 extern DDSCDllVariable const char *const
DDS_DATAWRITERRESOURCELIMITS_QOS_POLICY_NAME;

struct DDS_DataWriterResourceLimitsQosPolicy {
    /*e \dref_DataWriterResourceLimitsQosPolicy_initial_concurrent_blocking_threads
     */
    DDS_Long initial_concurrent_blocking_threads;
    
    /*e \dref_DataWriterResourceLimitsQosPolicy_max_concurrent_blocking_threads
     */
    DDS_Long max_concurrent_blocking_threads;

    /*e \dref_DataWriterResourceLimitsQosPolicy_max_remote_reader_filters
     */
    DDS_Long    max_remote_reader_filters;
};


#define DDS_DATA_WRITER_RESOURCE_LIMITS_QOS_POLICY_DEFAULT { 1L, -1L /* unlimited: was 8 before */, 32L }

 extern DDSCDllVariable const char *const
DDS_STATISTICS_QOS_POLICY_NAME;

struct DDS_StatisticsQosPolicy {
    /*i \dref_StatisticsQosPolicy_gather_statistics
     */
    DDS_Boolean gather_statistics;
};


#define DDS_STATISTICS_QOS_POLICY_DEFAULT { DDS_BOOLEAN_FALSE /* gather_statistics */ }

 extern DDSCDllVariable const char *const
DDS_SERVICE_QOS_POLICY_NAME;

typedef enum {
    /*i \dref_ServiceQosPolicyKind_NO_SERVICE_QOS
     */
    DDS_NO_SERVICE_QOS,
    
    /*i \dref_ServiceQosPolicyKind_PERSISTENCE_SERVICE_QOS
     */
    DDS_PERSISTENCE_SERVICE_QOS
} DDS_ServiceQosPolicyKind;

struct DDS_ServiceQosPolicy {
    /*i \dref_ServiceQosPolicy_kind
     */
    DDS_ServiceQosPolicyKind kind;
};


#define DDS_SERVICE_QOS_POLICY_DEFAULT \
{ DDS_NO_SERVICE_QOS }

 extern DDSCDllVariable const char *const
DDS_DATAREADERPROTOCOL_QOS_POLICY_NAME;

struct DDS_DataReaderProtocolQosPolicy {
    /*e \dref_DataReaderProtocolQosPolicy_virtual_guid 
    */
    struct DDS_GUID_t virtual_guid;
    /*e \dref_DataReaderProtocolQosPolicy_rtps_object_id
    */
    DDS_UnsignedLong rtps_object_id;
    /*e \dref_DataReaderProtocolQosPolicy_rtps_reliable_reader
     */
    struct DDS_RtpsReliableReaderProtocol_t    rtps_reliable_reader;
    /*e \dref_DataReaderProtocolQosPolicy_expects_inline_qos
     */
    DDS_Boolean expects_inline_qos;
};


#define DDS_DATA_READER_PROTOCOL_QOS_POLICY_DEFAULT \
{ \
  {{0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0}}, \
  DDS_RTPS_AUTO_ID, \
  DDS_RTPS_RELIABLE_READER_PROTOCOL_DEFAULT, \
  DDS_BOOLEAN_FALSE /* expects_inline_qos */ \
}

 extern DDSCDllVariable const char *const
DDS_DATAWRITERPROTOCOL_QOS_POLICY_NAME;

struct DDS_DataWriterProtocolQosPolicy {
    /*e \dref_DataWriterProtocolQosPolicy_virtual_guid 
    */
    struct DDS_GUID_t virtual_guid;
    /*e \dref_DataWriterProtocolQosPolicy_rtps_object_id
    */
    DDS_UnsignedLong rtps_object_id;
    /*e \dref_DataWriterProtocolQosPolicy_push_on_write
     */
    DDS_Boolean push_on_write;
    /*e \dref_DataWriterProtocolQosPolicy_rtps_reliable_writer
     */
    struct DDS_RtpsReliableWriterProtocol_t    rtps_reliable_writer;
};


#define DDS_DATA_WRITER_PROTOCOL_QOS_POLICY_DEFAULT \
{ {{0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0}}, DDS_RTPS_AUTO_ID, RTI_TRUE, DDS_RTPS_RELIABLE_WRITER_PROTOCOL_DEFAULT }

 extern DDSCDllVariable const char *const
DDS_SYSTEMRESOURCELIMITS_QOS_POLICY_NAME;

struct DDS_SystemResourceLimitsQosPolicy {
    /*e \dref_SystemResourceLimitsQosPolicy_max_objects_per_thread
     */
    DDS_Long  max_objects_per_thread;
};


#define DDS_SYSTEM_RESOURCE_LIMITS_QOS_POLICY_DEFAULT { 512L }

 extern DDSCDllVariable const char *const
DDS_DOMAINPARTICIPANTRESOURCELIMITS_QOS_POLICY_NAME;

struct DDS_DomainParticipantResourceLimitsQosPolicy {
    /*e \dref_DomainParticipantResourceLimitsQosPolicy_local_writer_allocation
     */
    struct DDS_AllocationSettings_t local_writer_allocation;
    /*e \dref_DomainParticipantResourceLimitsQosPolicy_local_reader_allocation
     */
    struct DDS_AllocationSettings_t local_reader_allocation;
    /*e \dref_DomainParticipantResourceLimitsQosPolicy_local_publisher_allocation
     */
    struct DDS_AllocationSettings_t local_publisher_allocation;
    /*e \dref_DomainParticipantResourceLimitsQosPolicy_local_subscriber_allocation
     */
    struct DDS_AllocationSettings_t local_subscriber_allocation;
    /*e \dref_DomainParticipantResourceLimitsQosPolicy_local_topic_allocation
     */
    struct DDS_AllocationSettings_t local_topic_allocation;

    /*e \dref_DomainParticipantResourceLimitsQosPolicy_remote_writer_allocation
     */
    struct DDS_AllocationSettings_t remote_writer_allocation;
    
    /*e \dref_DomainParticipantResourceLimitsQosPolicy_remote_reader_allocation
     */
    struct DDS_AllocationSettings_t remote_reader_allocation;
    
    /*e \dref_DomainParticipantResourceLimitsQosPolicy_remote_participant_allocation
     */
    struct DDS_AllocationSettings_t remote_participant_allocation;
    
    /*e \dref_DomainParticipantResourceLimitsQosPolicy_matching_writer_reader_pair_allocation
     */
    struct DDS_AllocationSettings_t matching_writer_reader_pair_allocation;
    
    /*e \dref_DomainParticipantResourceLimitsQosPolicy_matching_reader_writer_pair_allocation
     */
    struct DDS_AllocationSettings_t matching_reader_writer_pair_allocation;

    /*e \dref_DomainParticipantResourceLimitsQosPolicy_ignored_entity_allocation
     */
    struct DDS_AllocationSettings_t ignored_entity_allocation;

    /*e \dref_DomainParticipantResourceLimitsQosPolicy_content_filtered_topic_allocation
     */
    struct DDS_AllocationSettings_t content_filtered_topic_allocation;

    /*e \dref_DomainParticipantResourceLimitsQosPolicy_content_filter_allocation
     */
    struct DDS_AllocationSettings_t content_filter_allocation;

    /*e \dref_DomainParticipantResourceLimitsQosPolicy_read_condition_allocation
     */
    struct DDS_AllocationSettings_t read_condition_allocation;

    /*e \dref_DomainParticipantResourceLimitsQosPolicy_outstanding_asynchronous_sample_allocation
     */
    struct DDS_AllocationSettings_t outstanding_asynchronous_sample_allocation;

    /*e \dref_DomainParticipantResourceLimitsQosPolicy_flow_controller_allocation
     */
    struct DDS_AllocationSettings_t flow_controller_allocation;

    /*e \dref_DomainParticipantResourceLimitsQosPolicy_local_writer_hash_buckets
     */
    DDS_Long local_writer_hash_buckets;
    /*e \dref_DomainParticipantResourceLimitsQosPolicy_local_reader_hash_buckets
     */
    DDS_Long local_reader_hash_buckets;
    /*e \dref_DomainParticipantResourceLimitsQosPolicy_local_publisher_hash_buckets
     */
    DDS_Long local_publisher_hash_buckets;
    /*e \dref_DomainParticipantResourceLimitsQosPolicy_local_subscriber_hash_buckets
     */
    DDS_Long local_subscriber_hash_buckets;
    /*e \dref_DomainParticipantResourceLimitsQosPolicy_local_topic_hash_buckets
     */
    DDS_Long local_topic_hash_buckets;
    /*e \dref_DomainParticipantResourceLimitsQosPolicy_remote_writer_hash_buckets
     */
    DDS_Long remote_writer_hash_buckets;
    /*e \dref_DomainParticipantResourceLimitsQosPolicy_remote_reader_hash_buckets
     */
    DDS_Long remote_reader_hash_buckets;
    /*e \dref_DomainParticipantResourceLimitsQosPolicy_remote_participant_hash_buckets
     */
    DDS_Long remote_participant_hash_buckets;
    /*e \dref_DomainParticipantResourceLimitsQosPolicy_matching_writer_reader_pair_hash_buckets
     */
    DDS_Long matching_writer_reader_pair_hash_buckets;
    /*e \dref_DomainParticipantResourceLimitsQosPolicy_matching_reader_writer_pair_hash_buckets
     */
    DDS_Long matching_reader_writer_pair_hash_buckets;
    /*e \dref_DomainParticipantResourceLimitsQosPolicy_ignored_entity_hash_buckets
     */
    DDS_Long ignored_entity_hash_buckets;
    /*e \dref_DomainParticipantResourceLimitsQosPolicy_content_filtered_topic_hash_buckets
     */
    DDS_Long content_filtered_topic_hash_buckets;
    /*e \dref_DomainParticipantResourceLimitsQosPolicy_content_filter_hash_buckets
     */
    DDS_Long content_filter_hash_buckets;

    /*e \dref_DomainParticipantResourceLimitsQosPolicy_flow_controller_hash_buckets
     */
    DDS_Long flow_controller_hash_buckets;

    /*e \dref_DomainParticipantResourceLimitsQosPolicy_max_gather_destinations
     */
    DDS_Long max_gather_destinations;

    /*e \dref_DomainParticipantResourceLimitsQosPolicy_participant_user_data_max_length
     */
    DDS_Long participant_user_data_max_length;

    /*i \dref_DomainParticipantResourceLimitsQosPolicy_inter_participant_data_max_length
     */
    DDS_Long inter_participant_data_max_length;

    /*e \dref_DomainParticipantResourceLimitsQosPolicy_topic_data_max_length
     */
    DDS_Long topic_data_max_length;

    /*e \dref_DomainParticipantResourceLimitsQosPolicy_publisher_group_data_max_length
     */
    DDS_Long publisher_group_data_max_length;

    /*e \dref_DomainParticipantResourceLimitsQosPolicy_subscriber_group_data_max_length
     */
    DDS_Long subscriber_group_data_max_length;

    /*e \dref_DomainParticipantResourceLimitsQosPolicy_writer_user_data_max_length
     */
    DDS_Long writer_user_data_max_length;

    /*e \dref_DomainParticipantResourceLimitsQosPolicy_reader_user_data_max_length
     */
    DDS_Long reader_user_data_max_length;

    /*e \dref_DomainParticipantResourceLimitsQosPolicy_max_partitions
     */
    DDS_Long max_partitions;

    /*e \dref_DomainParticipantResourceLimitsQosPolicy_max_partition_cumulative_characters
     */
    DDS_Long max_partition_cumulative_characters;

    /*i \dref_DomainParticipantResourceLimitsQosPolicy_default_partition_matches_all
     */
    DDS_Boolean default_partition_matches_all;

    /*i \dref_DomainParticipantResourceLimitsQosPolicy_allow_no_partitions
     */
    DDS_Boolean allow_no_partitions;

    /*e \dref_DomainParticipantResourceLimitsQosPolicy_type_code_max_serialized_length
     */
    DDS_Long type_code_max_serialized_length;
    
    /*e \dref_DomainParticipantResourceLimitsQosPolicy_contentfilter_property_max_length
     */
    DDS_Long contentfilter_property_max_length;

    /*e \dref_DomainParticipantResourceLimitsQosPolicy_participant_property_list_max_length
     */
    DDS_Long participant_property_list_max_length;

    /*e \dref_DomainParticipantResourceLimitsQosPolicy_participant_property_string_max_length
     */
    DDS_Long participant_property_string_max_length;

    /*e \dref_DomainParticipantResourceLimitsQosPolicy_writer_property_list_max_length
     */
    DDS_Long writer_property_list_max_length;

    /*e \dref_DomainParticipantResourceLimitsQosPolicy_writer_property_string_max_length
     */
    DDS_Long writer_property_string_max_length;

    /*e \dref_DomainParticipantResourceLimitsQosPolicy_reader_property_list_max_length
     */
    DDS_Long reader_property_list_max_length;

    /*e \dref_DomainParticipantResourceLimitsQosPolicy_reader_property_string_max_length
     */
    DDS_Long reader_property_string_max_length;

    /*i \dref_DomainParticipantResourceLimitsQosPolicy_plugin_info_parameter_max_length
     */
    DDS_Long plugin_info_parameter_max_length;
};


#define DDS_DomainParticipantResourceLimitsQosPolicy_MATCH_INIT (32L)


#define DDS_DOMAIN_PARTICIPANT_RESOURCE_LIMITS_QOS_POLICY_DEFAULT \
{{16L, -1L, -1L}, /*local_writer_allocation*/      \
 {16L, -1L, -1L}, /*local_reader_allocation*/      \
 { 4L, -1L, -1L}, /*local_publisher_allocation*/     \
 { 4L, -1L, -1L}, /*local_subscriber_allocation*/    \
 {16L, -1L, -1L}, /*local_topic_allocation*/       \
 {64L, -1L, -1L}, /*remote_writer_allocation*/     \
 {64L, -1L, -1L}, /*remote_reader_allocation*/     \
 {16L, -1L, -1L}, /*remote_participant_allocation*/\
 {DDS_DomainParticipantResourceLimitsQosPolicy_MATCH_INIT, -1L, -1L}, /*matching_writer_reader_pair_allocation*/   \
 {DDS_DomainParticipantResourceLimitsQosPolicy_MATCH_INIT, -1L, -1L}, /*matching_reader_writer_pair_allocation*/   \
 {8L, -1L, -1L}, /*ignored_entity_allocation*/\
 {4L, -1L, -1L}, /*content_filtered_topic_allocation*/\
 {4L, -1L, -1L}, /*content_filter_allocation*/\
 {4L, -1L, -1L}, /*read_condition_allocation*/\
 {64L, -1L, -1L}, /*outstanding_asynchronous_sample_allocation*/\
 {4L, -1L, -1L}, /*flow_controller_allocation*/\
 4, /* local_writer_hash_buckets */ \
 4, /* local_reader_hash_buckets */ \
 1, /* local_publisher_hash_buckets */ \
 1, /* local_subscriber_hash_buckets */ \
 4, /* local_topic_hash_buckets */ \
 16, /* remote_writer_hash_buckets */ \
 16, /* remote_reader_hash_buckets */ \
 4, /* remote_participant_hash_buckets */ \
 32, /* matching_writer_reader_pair_hash_buckets */ \
 32, /* matching_reader_writer_pair_hash_buckets */  \
 1, /* ignored_entity_hash_buckets */  \
 1, /* content_filtered_topic_hash_buckets */  \
 1, /* content_filter_hash_buckets */  \
 1, /* flow_controller_hash_buckets */ \
 8,  /* max_gather_destinations */      \
 256, /* participant_user_data_max_length */ \
 256, /* inter_participant_data_max_length */ \
 256, /* topic_data_max_length */ \
 256, /* publisher_group_data_max_length */ \
 256, /* subscriber_group_data_max_length */ \
 256, /* writer_user_data_max_length */ \
 256, /* reader_user_data_max_length */  \
 64, /* max_partitions */ \
 256, /* max_partition_cumulative_characters */        \
 DDS_BOOLEAN_FALSE, /* default_partition_match_all */ \
 DDS_BOOLEAN_FALSE, /* allow_no_partition */         \
 2048, /* Type code max serialized size */              \
 256, /* content filter max serialized length */     \
 32,  /* participant property list max length */\
 1024, /* participant property string max length */\
 32,  /* writer property list max length */\
 1024, /* writer property string max length */\
 32,  /* reader property list max length */\
 1024, /* reader property string max length */\
 256 /* plugin_info_parameter_max_length */ \
}

 extern DDSCDllVariable const char *const
DDS_EVENT_QOS_POLICY_NAME;

struct DDS_EventQosPolicy {
    /*e \dref_EventQosPolicy_thread
     */
    struct DDS_ThreadSettings_t thread;
    /*e \dref_EventQosPolicy_initial_count
     */
    DDS_Long initial_count;
    /*e \dref_EventQosPolicy_max_count
     */
    DDS_Long max_count;
};


#define DDS_EVENT_QOS_POLICY_DEFAULT \
{ DDS_THREAD_SETTINGS_DEFAULT, \
  256, /* initial_count */ \
  -1 /* max_count: unlimited */ \
}

 extern DDSCDllVariable const char *const
DDS_DATABASE_QOS_POLICY_NAME;

struct DDS_DatabaseQosPolicy {
    /*e \dref_DatabaseQosPolicy_thread
     */
    struct DDS_ThreadSettings_t thread;
    
    /*e \dref_DatabaseQosPolicy_shutdown_timeout
     */
    struct DDS_Duration_t shutdown_timeout;
    
    /*e \dref_DatabaseQosPolicy_cleanup_period
     */
    struct DDS_Duration_t cleanup_period;

    /*e \dref_DatabaseQosPolicy_shutdown_cleanup_period
     */
    struct DDS_Duration_t shutdown_cleanup_period;
    
    /*e \dref_DatabaseQosPolicy_initial_records
     */
    DDS_Long initial_records;

    /*e \dref_DatabaseQosPolicy_max_skiplist_level
     */
    DDS_Long max_skiplist_level;
    
    /*i \dref_DatabaseQosPolicy_table_allocation_block_size
     */
    DDS_Long table_allocation_block_size;

    /*e \dref_DatabaseQosPolicy_max_weak_references
     */
    DDS_Long max_weak_references;
    
    /*e \dref_DatabaseQosPolicy_initial_weak_references
     */
    DDS_Long initial_weak_references;
};


#define DDS_DATABASE_QOS_POLICY_DEFAULT { \
    DDS_THREAD_SETTINGS_DEFAULT, /* thread */ \
    {15, 0} /* shutdown_timeout */, \
    {61, 0} /* cleanup_period */, \
    {1, 0} /* shutdown_cleanup_period */, \
    1024 /* initial_records */, \
    7 /* max_skiplist_level, was 14, but that's unnecessarily high! */, \
    48, /* table_allocation_block_size */ \
   -1 /*max_weak_references: unlimited */, \
    2049 /*initial_weak_references*/ \
}

 extern DDSCDllVariable const char *const
DDS_RECEIVERPOOL_QOS_POLICY_NAME;

struct DDS_ReceiverPoolQosPolicy {
    /*e \dref_ReceiverPoolQosPolicy_thread
     */
    struct DDS_ThreadSettings_t thread;
    
    /*i \dref_ReceiverPoolQosPolicy_initial_receive_threads
     * 
     * These docs are internal because the receive threads in the lower
     * layer are not yet implemented in the way implied by this policy.
     * In fact, the docs state that this field is currently unsupported.
     * It doesn't make much sense to add a DDS extension and then not
     * support it.
     */
    DDS_Long initial_receive_threads;
    
    /*i \dref_ReceiverPoolQosPolicy_max_receive_threads
     * 
     * These docs are internal because this field is not yet used. It exists
     * to be symmetrical with initial_receive_threads and will likely be
     * supported one day once we have a better receive thread pool.
     */
    DDS_Long max_receive_threads;
    
    /*e \dref_ReceiverPoolQosPolicy_buffer_size
     */
    DDS_Long buffer_size;
    
    /*e \dref_ReceiverPoolQosPolicy_buffer_alignment
     */
    DDS_Long buffer_alignment;
    
    /*i \dref_ReceiverPoolQosPolicy_is_timestamp_enabled
     */
    DDS_Boolean is_timestamp_enabled;
};


#define DDS_ReceiverPoolQosPolicy_MAX_RECEIVE_THREADS_DEFAULT (-1)


#define DDS_RECEIVER_POOL_QOS_POLICY_DEFAULT \
    { DDS_THREAD_SETTINGS_DEFAULT, 4, \
      DDS_ReceiverPoolQosPolicy_MAX_RECEIVE_THREADS_DEFAULT, \
      9216, 16, RTI_TRUE }

struct DDS_BuiltinTopicReaderResourceLimits_t {
    /*e \dref_BuiltinTopicReaderResourceLimits_t_initial_samples
     */
    DDS_Long initial_samples;
    /*e \dref_BuiltinTopicReaderResourceLimits_t_max_samples
     */
    DDS_Long max_samples;
    /*e \dref_BuiltinTopicReaderResourceLimits_t_initial_infos
     */
    DDS_Long initial_infos;
    /*e \dref_BuiltinTopicReaderResourceLimits_t_max_infos
     */
    DDS_Long max_infos;
    /*e \dref_BuiltinTopicReaderResourceLimits_t_initial_outstanding_reads
     */
    DDS_Long initial_outstanding_reads;

    /*e \dref_BuiltinTopicReaderResourceLimits_t_max_outstanding_reads
     */
    DDS_Long max_outstanding_reads;

    /*e \dref_BuiltinTopicReaderResourceLimits_t_max_samples_per_read
     */
    DDS_Long max_samples_per_read;
};


#define DDS_BUILTIN_TOPIC_READER_RESOURCE_LIMITS_DEFAULT {   \
    64,  /* initial samples */                               \
    -1L, /* max_samples: was 16384 before being unlimited */ \
    64,  /* initial_infos */                                 \
    -1L, /* max_infos: was 16384 before being unlimited */   \
    2,   /* initial_outstanding_reads */                     \
    -1L, /* max_outstanding_reads: was 1024 before being unlimited */ \
    1024 /* max_samples_per_read */ }


#define DDS_BUILTIN_TOPIC_KEY_TYPE_NATIVE_LENGTH (4)

typedef struct DDS_BuiltinTopicKey_t {
    /*e \dref_BuiltinTopicKey_t_value
     */
    DDS_BUILTIN_TOPIC_KEY_TYPE_NATIVE value[DDS_BUILTIN_TOPIC_KEY_TYPE_NATIVE_LENGTH];
} DDS_BuiltinTopicKey_t;


#define DDS_BuiltinTopicKey_t_INITIALIZER { {0, 0, 0, 0} }

extern DDSCDllExport DDS_Boolean 
DDS_BuiltinTopicKey_equals(DDS_BuiltinTopicKey_t *a, DDS_BuiltinTopicKey_t *b);

 extern DDSCDllVariable const char *const
DDS_PUBLISHMODE_QOS_POLICY_NAME;


DDSC_VARIABLE_LENGTH_VALUE_TYPE_SUPPORT(DDS_PublishModeQosPolicy);

typedef enum {
    /*e \dref_PublishModeQosPolicyKind_SYNCHRONOUS_PUBLISH_MODE_QOS
     */
    DDS_SYNCHRONOUS_PUBLISH_MODE_QOS,
    
    /*e \dref_PublishModeQosPolicyKind_ASYNCHRONOUS_PUBLISH_MODE_QOS
     */
    DDS_ASYNCHRONOUS_PUBLISH_MODE_QOS

} DDS_PublishModeQosPolicyKind;

struct DDS_PublishModeQosPolicy {
    /*e \dref_PublishModeQosPolicy_kind
     */
    DDS_PublishModeQosPolicyKind kind;
    /*e \dref_PublishModeQosPolicy_flow_controller_name
     */
    char *flow_controller_name;

    DDSCPP_VARIABLE_LENGTH_VALUE_TYPE_SUPPORT(DDS_PublishModeQosPolicy)
};


#define DDS_PUBLISH_MODE_QOS_POLICY_DEFAULT \
{ DDS_SYNCHRONOUS_PUBLISH_MODE_QOS, NULL }

 extern DDSCDllVariable const char *const
DDS_DISCOVERYCONFIG_QOS_POLICY_NAME;

typedef DDS_Long DDS_DiscoveryConfigBuiltinPluginKindMask;

typedef enum {
    /*i \dref_DiscoveryConfigBuiltinPluginKind_DISCOVERYCONFIG_BUILTIN_SPDP
     */
    DDS_DISCOVERYCONFIG_BUILTIN_SPDP = 0x0001 << 0,
    /*i \dref_DiscoveryConfigBuiltinPluginKind_DISCOVERYCONFIG_BUILTIN_SEDP
     */
    DDS_DISCOVERYCONFIG_BUILTIN_SEDP = 0x0001 << 1,
    /*e \dref_DiscoveryConfigBuiltinPluginKind_DISCOVERYCONFIG_BUILTIN_SDP
     */
    DDS_DISCOVERYCONFIG_BUILTIN_SDP = DDS_DISCOVERYCONFIG_BUILTIN_SPDP |
                                      DDS_DISCOVERYCONFIG_BUILTIN_SEDP,
    /*e \dref_DiscoveryConfigBuiltinPluginKind_DISCOVERYCONFIG_BUILTIN_EDS
     */
    DDS_DISCOVERYCONFIG_BUILTIN_EDS   = 0x0001 << 2
} DDS_DiscoveryConfigBuiltinPluginKind;


/*e \dref_DISCOVERYCONFIG_BUILTIN_PLUGIN_MASK_ALL
 */
  #define DDS_DISCOVERYCONFIG_BUILTIN_PLUGIN_MASK_ALL  (DDS_DiscoveryConfigBuiltinPluginKindMask)(0xefff)
/*e \dref_DISCOVERYCONFIG_BUILTIN_PLUGIN_MASK_NONE
 */
  #define DDS_DISCOVERYCONFIG_BUILTIN_PLUGIN_MASK_NONE (DDS_DiscoveryConfigBuiltinPluginKindMask)(0x0)
/*e \dref_DISCOVERYCONFIG_BUILTIN_PLUGIN_MASK_DEFAULT
 */
  #define DDS_DISCOVERYCONFIG_BUILTIN_PLUGIN_MASK_DEFAULT  (DDS_DiscoveryConfigBuiltinPluginKindMask)DDS_DISCOVERYCONFIG_BUILTIN_SDP

typedef enum {
    /*i \dref_DiscoveryPluginPromiscuityKind_DISCOVERYPLUGIN_DISCOVER_MATCHING_REMOTE_ENTITIES_PROMISCUITY
     */
    DDS_DISCOVERYPLUGIN_DISCOVER_MATCHING_REMOTE_ENTITIES_PROMISCUITY = 0x0001,
    /*i \dref_DiscoveryPluginPromiscuityKind_DISCOVERYPLUGIN_DISCOVER_ALL_REMOTE_ENTITIES_PROMISCUITY
     */
    DDS_DISCOVERYPLUGIN_DISCOVER_ALL_REMOTE_ENTITIES_PROMISCUITY = 0xFFFF    
} DDS_DiscoveryPluginPromiscuityKind;

typedef enum {
    /*e \dref_RemoteParticipantPurgeKind_LIVELINESS_BASED_REMOTE_PARTICIPANT_PURGE
     */
    DDS_LIVELINESS_BASED_REMOTE_PARTICIPANT_PURGE,
    /*e \dref_RemoteParticipantPurgeKind_NO_REMOTE_PARTICIPANT_PURGE
     */
    DDS_NO_REMOTE_PARTICIPANT_PURGE
} DDS_RemoteParticipantPurgeKind;

struct DDS_DiscoveryBuiltinReaderFragmentationResourceLimits_t {
    /*i \dref_DiscoveryBuiltinReaderFragmentationResourceLimits_disable_fragmentation_support
     */
    DDS_Boolean disable_fragmentation_support;
    /*i \dref_DiscoveryBuiltinReaderFragmentationResourceLimits_max_fragmented_samples
     */
    DDS_Long max_fragmented_samples;
    /*i \dref_DiscoveryBuiltinReaderFragmentationResourceLimits_initial_fragmented_samples
     */
    DDS_Long initial_fragmented_samples;
    /*i \dref_DiscoveryBuiltinReaderFragmentationResourceLimits_max_fragmented_samples_per_remote_writer
     */
    DDS_Long max_fragmented_samples_per_remote_writer;
    /*i \dref_DiscoveryBuiltinReaderFragmentationResourceLimits_max_fragments_per_sample
     */
    DDS_Long max_fragments_per_sample;
    /*i \dref_DiscoveryBuiltinReaderFragmentationResourceLimits_dynamically_allocate_fragmented_samples
     */
    DDS_Boolean dynamically_allocate_fragmented_samples;
};


#define DISCOVERY_BUILTIN_READER_FRAGMENTATION_RESOURCE_LIMITS_DEFAULT { \
    DDS_BOOLEAN_FALSE,/*disable_fragmentation_support */\
    1024L, /* max_fragmented_samples */\
    4L, /* initial_fragmented_samples */\
    256L, /* max_fragmented_samples_per_remote_writer */\
    512L, /* max_fragments_per_sample */\
    DDS_BOOLEAN_FALSE /* dynamically_allocate_fragmented_samples */\
}

struct DDS_DiscoveryConfigQosPolicy {
     /*e \dref_DiscoveryConfigQosPolicy_participant_liveliness_lease_duration
     */
    struct DDS_Duration_t participant_liveliness_lease_duration;
    
    /*e \dref_DiscoveryConfigQosPolicy_participant_liveliness_assert_period
     */
    struct DDS_Duration_t participant_liveliness_assert_period;
    
    /*e \dref_DiscoveryConfigQosPolicy_remote_participant_purge_kind
     */
    DDS_RemoteParticipantPurgeKind remote_participant_purge_kind;
    
    /*e \dref_DiscoveryConfigQosPolicy_max_liveliness_loss_detection_period
     */
    struct DDS_Duration_t max_liveliness_loss_detection_period;

    /*e \dref_DiscoveryConfigQosPolicy_initial_participant_announcements
     */
    DDS_Long initial_participant_announcements;

    /*e \dref_DiscoveryConfigQosPolicy_min_initial_participant_announcement_period
     */
    struct DDS_Duration_t min_initial_participant_announcement_period;

    /*e \dref_DiscoveryConfigQosPolicy_max_initial_participant_announcement_period
     */
    struct DDS_Duration_t max_initial_participant_announcement_period;

    /*e \dref_DiscoveryConfigQosPolicy_participant_reader_resource_limits
     */
    struct DDS_BuiltinTopicReaderResourceLimits_t participant_reader_resource_limits;

    /*e \dref_DiscoveryConfigQosPolicy_publication_reader
     */
    struct DDS_RtpsReliableReaderProtocol_t publication_reader;

    /*e \dref_DiscoveryConfigQosPolicy_publication_reader_resource_limits
     */
    struct DDS_BuiltinTopicReaderResourceLimits_t publication_reader_resource_limits;
    
    /*e \dref_DiscoveryConfigQosPolicy_subscription_reader
     */
    struct DDS_RtpsReliableReaderProtocol_t subscription_reader;
    
    /*e \dref_DiscoveryConfigQosPolicy_subscription_reader_resource_limits
     */    
    struct DDS_BuiltinTopicReaderResourceLimits_t subscription_reader_resource_limits;
    
    /*e \dref_DiscoveryConfigQosPolicy_publication_writer
     */    
    struct DDS_RtpsReliableWriterProtocol_t publication_writer;
    
    /*e \dref_DiscoveryConfigQosPolicy_subscription_writer
     */    
    struct DDS_RtpsReliableWriterProtocol_t subscription_writer;
    
    /*i \dref_DiscoveryConfigQosPolicy_endpoint_plugin_redundancy_level
     */    
    DDS_Long endpoint_plugin_redundancy_level;
    
    /*e \dref_DiscoveryConfigQosPolicy_builtin_discovery_plugins
     */    
    DDS_DiscoveryConfigBuiltinPluginKindMask builtin_discovery_plugins;

    /***************** HIDDEN FROM USER ********************************/

    /*i \dref_DiscoveryConfigQosPolicy_publication_reader_fragmentation_resource_limits
     */
    struct DDS_DiscoveryBuiltinReaderFragmentationResourceLimits_t 
        publication_reader_fragmentation_resource_limits;

    /*i \dref_DiscoveryConfigQosPolicy_subscription_reader_fragmentation_resource_limits
     */
    struct DDS_DiscoveryBuiltinReaderFragmentationResourceLimits_t 
        subscription_reader_fragmentation_resource_limits;

    /*i \dref_DiscoveryConfigQosPolicy_sedp_rely_on_spdp_only
     */
    DDS_Boolean sedp_rely_on_spdp_only;

    /*i \dref_DiscoveryConfigQosPolicy_inter_participant_reader
     */
    struct DDS_RtpsReliableReaderProtocol_t inter_participant_reader;

    /*i \dref_DiscoveryConfigQosPolicy_inter_participant_writer
     */
    struct DDS_RtpsReliableWriterProtocol_t inter_participant_writer;

    /* --- Publication announcer --- */

    /*i \dref_DiscoveryConfigQosPolicy_publication_writer_latency_budget
     */
    struct DDS_LatencyBudgetQosPolicy publication_writer_latency_budget;

    /*i \dref_DiscoveryConfigQosPolicy_publication_writer_push_on_write
     */
    DDS_Boolean publication_writer_push_on_write;

    /*i \dref_DiscoveryConfigQosPolicy_publication_writer_publish_mode
     */
    struct DDS_PublishModeQosPolicy publication_writer_publish_mode;

    /* --- Subscription announcer --- */

    /*i \dref_DiscoveryConfigQosPolicy_subscription_writer_latency_budget
     */
    struct DDS_LatencyBudgetQosPolicy subscription_writer_latency_budget;

    /*i \dref_DiscoveryConfigQosPolicy_subscription_writer_push_on_write
     */
    DDS_Boolean subscription_writer_push_on_write;

    /*i \dref_DiscoveryConfigQosPolicy_subscription_writer_publish_mode
     */
    struct DDS_PublishModeQosPolicy subscription_writer_publish_mode;

    /* --- Participant state writer --- */

    /*i \dref_DiscoveryConfigQosPolicy_participant_state_writer
     */
    struct DDS_RtpsReliableWriterProtocol_t participant_state_writer;

    /*i \dref_DiscoveryConfigQosPolicy_participant_state_writer_latency_budget
     */
    struct DDS_LatencyBudgetQosPolicy participant_state_writer_latency_budget;

    /*i \dref_DiscoveryConfigQosPolicy_participant_state_writer_push_on_write
     */
    DDS_Boolean participant_state_writer_push_on_write;

    /*i \dref_DiscoveryConfigQosPolicy_participant_state_writer_publish_mode
     */
    struct DDS_PublishModeQosPolicy participant_state_writer_publish_mode;

    /* --- Participant proxy reader --- */

    /*i \dref_DiscoveryConfigQosPolicy_participant_proxy_reader
     */
    struct DDS_RtpsReliableReaderProtocol_t participant_proxy_reader;

    /*i \dref_DiscoveryConfigQosPolicy_participant_proxy_reader_fragmentation_resource_limits
     */
    struct DDS_DiscoveryBuiltinReaderFragmentationResourceLimits_t 
        participant_proxy_reader_fragmentation_resource_limits;

    /*i \dref_DiscoveryConfigQosPolicy_plugin_promiscuity_kind
     */
    DDS_DiscoveryPluginPromiscuityKind plugin_promiscuity_kind;
};


#define DDS_DISCOVERY_CONFIG_QOS_POLICY_DEFAULT { \
{100L,0L}, /* participant_liveliness_lease_duration */\
{30L,0L}, /* participant_liveliness_assert_period */\
DDS_LIVELINESS_BASED_REMOTE_PARTICIPANT_PURGE, /*remote_participant_purge_kind*/\
{60L,0L}, /* max_liveliness_loss_detection_period */ \
5L, /* new_remote_participant_announcements */\
{1L,0L}, /* min_new_remote_participant_announcement_period */\
{1L,0L}, /* max_new_remote_participant_announcement_period */\
 DDS_BUILTIN_TOPIC_READER_RESOURCE_LIMITS_DEFAULT,/* participant_reader_resource_limits */\
DDS_RTPS_RELIABLE_READER_PROTOCOL_DISCOVERY_CONFIG_DEFAULT, /* publication_reader */\
 DDS_BUILTIN_TOPIC_READER_RESOURCE_LIMITS_DEFAULT,/* publication_reader_resource_limits */\
DDS_RTPS_RELIABLE_READER_PROTOCOL_DISCOVERY_CONFIG_DEFAULT, /* subscription_reader */\
 DDS_BUILTIN_TOPIC_READER_RESOURCE_LIMITS_DEFAULT,/* subscription_reader_resource_limits */\
DDS_RTPS_RELIABLE_WRITER_PROTOCOL_DISCOVERY_CONFIG_DEFAULT, /* publication_writer */\
DDS_RTPS_RELIABLE_WRITER_PROTOCOL_DISCOVERY_CONFIG_DEFAULT, /* subscription_writer */\
-1, /* endpoint_plugin_redundancy_level - cannot use DDS_LENGTH_UNLIMITED since it's externed */\
DDS_DISCOVERYCONFIG_BUILTIN_PLUGIN_MASK_DEFAULT, /* builtin_discovery_plugins */\
DISCOVERY_BUILTIN_READER_FRAGMENTATION_RESOURCE_LIMITS_DEFAULT, /* publication_reader_fragmentation_resource_limits */\
DISCOVERY_BUILTIN_READER_FRAGMENTATION_RESOURCE_LIMITS_DEFAULT, /* subscription_reader_fragmentation_resource_limits */\
DDS_BOOLEAN_FALSE, /* sedp_rely_on_spdp_only */\
DDS_RTPS_RELIABLE_READER_PROTOCOL_DISCOVERY_CONFIG_DEFAULT, /* inter_participant_reader */\
DDS_RTPS_RELIABLE_WRITER_PROTOCOL_DISCOVERY_CONFIG_DEFAULT, /* inter_participant_writer */\
DDS_LATENCY_BUDGET_QOS_POLICY_DEFAULT, /* publication_writer_latency_budget */\
DDS_BOOLEAN_TRUE, /* publication_writer_push_on_write */\
DDS_PUBLISH_MODE_QOS_POLICY_DEFAULT, /* publication_writer_publish_mode */\
DDS_LATENCY_BUDGET_QOS_POLICY_DEFAULT, /* subscription_writer_latency_budget */\
DDS_BOOLEAN_TRUE, /* subscription_writer_push_on_write */\
DDS_PUBLISH_MODE_QOS_POLICY_DEFAULT, /* subscription_writer_publish_mode */\
DDS_RTPS_RELIABLE_WRITER_PROTOCOL_DISCOVERY_CONFIG_DEFAULT, /* participant_state_writer */\
DDS_LATENCY_BUDGET_QOS_POLICY_DEFAULT, /* participant_state_writer_latency_budget */\
DDS_BOOLEAN_TRUE, /* participant_state_writer_push_on_write */\
DDS_PUBLISH_MODE_QOS_POLICY_DEFAULT, /* participant_state_writer_publish_mode */\
DDS_RTPS_RELIABLE_READER_PROTOCOL_DISCOVERY_CONFIG_DEFAULT, /* participant_proxy_reader */\
DISCOVERY_BUILTIN_READER_FRAGMENTATION_RESOURCE_LIMITS_DEFAULT, /* participant_proxy_reader_fragmentation_resource_limits */\
DDS_DISCOVERYPLUGIN_DISCOVER_MATCHING_REMOTE_ENTITIES_PROMISCUITY /* plugin_promiscuity_kind */\
}

 extern DDSCDllVariable const char *const
DDS_TYPESUPPORT_QOS_POLICY_NAME;

struct DDS_TypeSupportQosPolicy {
    /*e \dref_TypeSupportQosPolicy_plugin_data
     */
    void* plugin_data;
};


#define DDS_TYPESUPPORT_QOS_POLICY_DEFAULT \
{ NULL }

 extern DDSCDllVariable const char *const
DDS_ASYNCHRONOUSPUBLISHER_QOS_POLICY_NAME;

struct DDS_AsynchronousPublisherQosPolicy {
    /*e \dref_AsynchronousPublisherQosPolicy_disable_asynchronous_write
     */
     DDS_Boolean disable_asynchronous_write;
    /*e \dref_AsynchronousPublisherQosPolicy_thread
     */
     struct DDS_ThreadSettings_t thread;
};


#define DDS_ASYNCHRONOUS_PUBLISHER_QOS_POLICY_DEFAULT { \
    DDS_BOOLEAN_FALSE, DDS_THREAD_SETTINGS_DEFAULT \
}

 extern DDSCDllVariable const char *const 
DDS_USEROBJECT_QOS_POLICY_NAME;

struct DDS_UserObjectQosPolicy {
    /*i \dref_UserObjectQosPolicy_participant_user_object
     */
    struct DDS_UserObjectSettings_t participant_user_object;
    /*i \dref_UserObjectQosPolicy_topic_user_object
     */
    struct DDS_UserObjectSettings_t topic_user_object;
    /*i \dref_UserObjectQosPolicy_content_filtered_topic_user_object
     */
    struct DDS_UserObjectSettings_t content_filtered_topic_user_object;
    /*i \dref_UserObjectQosPolicy_publisher_user_object
     */
    struct DDS_UserObjectSettings_t publisher_user_object;
    /*i \dref_UserObjectQosPolicy_data_writer_user_object
     */
    struct DDS_UserObjectSettings_t data_writer_user_object;
    /*i \dref_UserObjectQosPolicy_subscriber_user_object
     */
    struct DDS_UserObjectSettings_t subscriber_user_object;
    /*i \dref_UserObjectQosPolicy_data_reader_user_object
     */
    struct DDS_UserObjectSettings_t data_reader_user_object;
    /*i \dref_UserObjectQosPolicy_read_condition_user_object
     */
    struct DDS_UserObjectSettings_t read_condition_user_object;
    /*i \dref_UserObjectQosPolicy_flow_controller_user_object
     */
    struct DDS_UserObjectSettings_t flow_controller_user_object;
};


#define DDS_USER_OBJECT_QOS_POLICY_DEFAULT \
{{0,0}, {0,0}, {0,0}, {0,0}, {0,0}, {0,0}, {0,0}, {0,0}, {0,0}}

 extern DDSCDllVariable const char *const 
DDS_EXCLUSIVEAREA_QOS_POLICY_NAME;

struct DDS_ExclusiveAreaQosPolicy {
    /*e \dref_ExclusiveAreaQosPolicy_use_shared_exclusive_area
     */
    DDS_Boolean use_shared_exclusive_area;
};


#define DDS_EXCLUSIVE_AREA_QOS_POLICY_DEFAULT   { RTI_FALSE }

struct DDS_Property_t {
    /*e \dref_Property_t_name
     */
    char *name;

    /*e \dref_Property_t_value
     */
    char *value;

    /*e \dref_Property_t_propagate
     */
    DDS_Boolean propagate;
};


DDS_SEQUENCE(DDS_PropertySeq, struct DDS_Property_t);

 extern DDSCDllVariable const char *const
DDS_PROPERTY_QOS_POLICY_NAME;


DDSC_VARIABLE_LENGTH_VALUE_TYPE_SUPPORT(DDS_PropertyQosPolicy);

struct DDS_PropertyQosPolicy {
    /*e \dref_PropertyQosPolicy_value
    */
    struct DDS_PropertySeq value;
	
    DDSCPP_VARIABLE_LENGTH_VALUE_TYPE_SUPPORT(DDS_PropertyQosPolicy)
};


	    
#define DDS_PROPERTY_QOS_POLICY_DEFAULT {DDS_SEQUENCE_INITIALIZER}


extern DDSCDllExport DDS_Long
DDS_PropertyQosPolicyHelper_get_number_of_properties(struct DDS_PropertyQosPolicy * policy);

extern DDSCDllExport DDS_ReturnCode_t
DDS_PropertyQosPolicyHelper_assert_property(struct DDS_PropertyQosPolicy * policy,
                                            const char *name,const char *value,
                                            DDS_Boolean propagate);

extern DDSCDllExport DDS_ReturnCode_t
DDS_PropertyQosPolicyHelper_add_property(struct DDS_PropertyQosPolicy * policy,
                                         const char *name,const char *value,
                                         DDS_Boolean propagate);

extern DDSCDllExport struct DDS_Property_t*
DDS_PropertyQosPolicyHelper_lookup_property(struct DDS_PropertyQosPolicy * policy,
                                            const char *name);

extern DDSCDllExport DDS_ReturnCode_t
DDS_PropertyQosPolicyHelper_remove_property(struct DDS_PropertyQosPolicy * policy,
                                            const char *name);

extern DDSCDllExport DDS_ReturnCode_t
DDS_PropertyQosPolicyHelper_get_properties(struct DDS_PropertyQosPolicy * policy,
                                           struct DDS_PropertySeq * properties,
                                           const char * name_prefix);


DDSC_VARIABLE_LENGTH_VALUE_TYPE_SUPPORT(DDS_ContentFilterProperty_t);

struct DDS_ContentFilterProperty_t {
    
    /*e \dref_ContentFilterProperty_t_content_filter_topic_name
     */
    char *content_filter_topic_name;

    /*e \dref_ContentFilterProperty_t_related_topic_name
     */
    char *related_topic_name;

    /*e \dref_ContentFilterProperty_t_filter_class_name
     */
    char *filter_class_name;

    /*e \dref_ContentFilterProperty_t_filter_expression
     */
    char *filter_expression;

    /*e \dref_ContentFilterProperty_t_expression_parameters
     */
    struct DDS_StringSeq expression_parameters;

    DDSCPP_VARIABLE_LENGTH_VALUE_TYPE_SUPPORT(DDS_ContentFilterProperty_t)
};


#define DDS_CONTENT_FILTER_PROPERTY_DEFAULT \
{ \
  NULL, \
  NULL, \
  NULL, \
  NULL, \
  DDS_SEQUENCE_INITIALIZER \
}

struct DDS_Listener {
    /*ce \dref_Listener_listener_data
     */
    void* listener_data; 
};


#define DDS_Listener_INITIALIZER    { NULL }

typedef struct DDS_EntityImpl DDS_Entity;

typedef struct DDS_DomainEntityImpl DDS_DomainEntity;

typedef struct DDS_ConditionImpl DDS_Condition;

typedef struct DDS_ConditionImpl* DDS_Condition_ptr;


DDS_SEQUENCE(DDS_ConditionSeq, DDS_Condition_ptr);

extern DDSCDllExport DDS_Boolean DDS_Condition_get_trigger_value(
    DDS_Condition* self);

typedef struct DDS_GuardConditionImpl DDS_GuardCondition;


#define DDS_GuardCondition_as_condition(guardConditionPtr) \
            ((DDS_Condition*) guardConditionPtr)

extern DDSCDllExport DDS_GuardCondition* DDS_GuardCondition_new();

extern DDSCDllExport DDS_ReturnCode_t DDS_GuardCondition_delete(DDS_GuardCondition* self);

extern DDSCDllExport DDS_ReturnCode_t DDS_GuardCondition_set_trigger_value(
    DDS_GuardCondition* self, DDS_Boolean value);

typedef struct DDS_StatusConditionImpl DDS_StatusCondition;


#define DDS_StatusCondition_as_condition(statusConditionPtr) \
            ((DDS_Condition*) statusConditionPtr)

extern DDSCDllExport DDS_StatusMask 
DDS_StatusCondition_get_enabled_statuses(
    DDS_StatusCondition* self);

extern DDSCDllExport DDS_ReturnCode_t DDS_StatusCondition_set_enabled_statuses(
    DDS_StatusCondition* self, DDS_StatusMask mask);

extern DDSCDllExport DDS_Entity* DDS_StatusCondition_get_entity(
    DDS_StatusCondition* self);

typedef struct DDS_WaitSetImpl DDS_WaitSet;

extern DDSCDllExport DDS_WaitSet* DDS_WaitSet_new();

extern DDSCDllExport DDS_ReturnCode_t DDS_WaitSet_delete(DDS_WaitSet* self);

extern DDSCDllExport DDS_ReturnCode_t DDS_WaitSet_wait(
    DDS_WaitSet* self,
    struct DDS_ConditionSeq* active_conditions, 
    const struct DDS_Duration_t* timeout);

extern DDSCDllExport DDS_ReturnCode_t DDS_WaitSet_attach_condition(
    DDS_WaitSet* self,
    DDS_Condition* cond);

extern DDSCDllExport DDS_ReturnCode_t DDS_WaitSet_detach_condition(
    DDS_WaitSet* self,
    DDS_Condition* cond);

extern DDSCDllExport DDS_ReturnCode_t DDS_WaitSet_get_conditions(
    DDS_WaitSet* self, struct DDS_ConditionSeq* attached_conditions);

extern DDSCDllExport DDS_ReturnCode_t DDS_Entity_enable(DDS_Entity* self);

extern DDSCDllExport DDS_StatusCondition* DDS_Entity_get_statuscondition(
    DDS_Entity* self);

extern DDSCDllExport DDS_StatusMask DDS_Entity_get_status_changes(
    DDS_Entity* self);

extern DDSCDllExport DDS_InstanceHandle_t DDS_Entity_get_instance_handle(
    DDS_Entity* self);

extern DDSCDllExport DDS_EntityKind_t DDS_Entity_get_entity_kind(
    DDS_Entity* self);

 extern DDSCDllVariable const char *const
DDS_ENTITYNAME_QOS_POLICY_NAME;

 extern DDSCDllVariable const char* const DDS_AUTO_NAME_ENTITY;


DDSC_VARIABLE_LENGTH_VALUE_TYPE_SUPPORT(DDS_EntityNameQosPolicy);

struct DDS_EntityNameQosPolicy {
    /*e \dref_EntityNameQosPolicy_name
     */
    char* name;

    DDSCPP_VARIABLE_LENGTH_VALUE_TYPE_SUPPORT(DDS_EntityNameQosPolicy)
};


#define DDS_ENTITY_NAME_QOS_POLICY_DEFAULT   { NULL }

typedef struct DDS_DomainParticipantImpl DDS_DomainParticipant;



  #define DDS_BuiltinTopicKey_equals(a, b)   \
    ((a)->value[0] == (b)->value[0] && \
     (a)->value[1] == (b)->value[1] && \
     (a)->value[2] == (b)->value[2] && \
     (a)->value[3] == (b)->value[3])
  
#ifdef __cplusplus
    }	/* extern "C" */
#endif

#endif /* dds_c_infrastructure_h */
