/*
 * @(#)dds_c_builtin_impl.h    generated by: makeheader    Mon Dec  3 23:08:26 2007
 *
 *		built from:	builtin_impl.ifc
 */

#ifndef dds_c_builtin_impl_h
#define dds_c_builtin_impl_h


  #ifndef dds_c_dll_h
    #include "dds_c/dds_c_dll.h"
  #endif
  #ifndef dds_c_topic_impl_h
    #include "dds_c/dds_c_topic_impl.h"
  #endif
  #ifndef dds_c_builtin_h
    #include "dds_c/dds_c_builtin.h"
  #endif
  #ifndef cdr_stream_impl_h
    #include "cdr/cdr_stream_impl.h"
  #endif

#ifdef __cplusplus
    extern "C" {
#endif

 extern DDSCDllVariable const char *DDS_PARTICIPANT_TYPE_NAME;

extern DDSCDllExport DDS_DataTypeUtility*
DDS_ParticipantBuiltinTopicDataTypeSupport_get_or_delete_instanceI(DDS_Boolean deleteInstance);

extern DDSCDllExport struct PRESTypePlugin* 
DDS_ParticipantBuiltinTopicDataPlugin_new();

extern DDSCDllExport void 
DDS_ParticipantBuiltinTopicDataPlugin_delete(struct PRESTypePlugin *self);

 extern DDSCDllVariable const char *DDS_TOPIC_TYPE_NAME;

extern DDSCDllExport DDS_DataTypeUtility*
DDS_TopicBuiltinTopicDataTypeSupport_get_or_delete_instanceI(DDS_Boolean deleteInstance);

extern DDSCDllExport struct PRESTypePlugin* 
DDS_TopicBuiltinTopicDataPlugin_new();

extern DDSCDllExport void 
DDS_TopicBuiltinTopicDataPlugin_delete(struct PRESTypePlugin *self);

 extern DDSCDllVariable const char *DDS_PUBLICATION_TYPE_NAME;

extern DDSCDllExport DDS_DataTypeUtility*
DDS_PublicationBuiltinTopicDataTypeSupport_get_or_delete_instanceI(DDS_Boolean deleteInstance);

extern DDSCDllExport struct PRESTypePlugin* 
DDS_PublicationBuiltinTopicDataPlugin_new();

extern DDSCDllExport void
DDS_PublicationBuiltinTopicDataPlugin_delete(struct PRESTypePlugin *self);

 extern DDSCDllVariable const char *DDS_SUBSCRIPTION_TYPE_NAME;

extern DDSCDllExport DDS_DataTypeUtility*
DDS_SubscriptionBuiltinTopicDataTypeSupport_get_or_delete_instanceI(DDS_Boolean deleteInstance);

extern DDSCDllExport struct PRESTypePlugin* 
DDS_SubscriptionBuiltinTopicDataPlugin_new();

extern DDSCDllExport void
DDS_SubscriptionBuiltinTopicDataPlugin_delete(struct PRESTypePlugin *self);

extern DDSCDllExport DDS_Boolean DDS_Builtin_is_builtin_topicI(
    const char* topic_name);


#ifdef __cplusplus
    }	/* extern "C" */
#endif

#endif /* dds_c_builtin_impl_h */
