/*
 * @(#)osapi_bufferUtils.h    generated by: makeheader    Mon Dec  3 23:07:48 2007
 *
 *		built from:	bufferUtils.ifc
 */

#ifndef osapi_bufferUtils_h
#define osapi_bufferUtils_h


  #ifndef osapi_dll_h
    #include "osapi/osapi_dll.h"
  #endif

#ifdef __cplusplus
    extern "C" {
#endif

extern RTIOsapiDllExport void 
RTIOsapiMemory_copy(void *dest, const void *src, int size);

extern RTIOsapiDllExport void RTIOsapiMemory_zero(void *mem, int size);

extern RTIOsapiDllExport int 
RTIOsapiMemory_compare(const void *left, const void *right, int size);


#ifdef __cplusplus
    }	/* extern "C" */
#endif

/* pick up hidden performance boosting macros and optimizations */
  #include "osapi/osapi_bufferUtils_impl.h"

#endif /* osapi_bufferUtils_h */
