/*
 * @(#)osapi_host.h    generated by: makeheader    Mon Dec  3 23:07:48 2007
 *
 *		built from:	host.ifc
 */

#ifndef osapi_host_h
#define osapi_host_h


  #ifndef osapi_type_h
    #include "osapi/osapi_type.h"
  #endif
  #ifndef osapi_dll_h
    #include "osapi/osapi_dll.h"
  #endif

#ifdef __cplusplus
    extern "C" {
#endif

extern RTIOsapiDllExport RTI_UINT32 RTIOsapiHost_getId();

struct RTINtpTime;

extern RTIOsapiDllExport void
RTIOsapiHost_generateRandomTime(struct RTINtpTime* randomTimeOut,
				const struct RTINtpTime* timeMaxIn);


#ifdef __cplusplus
    }	/* extern "C" */
#endif

#endif /* osapi_host_h */
