/*
 * @(#)pres_readerStatistics.h    generated by: makeheader    Mon Dec  3 23:08:15 2007
 *
 *		built from:	readerStatistics.ifc
 */

#ifndef pres_readerStatistics_h
#define pres_readerStatistics_h


#include "osapi/osapi_type.h"
#include "commend/commend_readerStatistics.h"

#ifdef __cplusplus
    extern "C" {
#endif

struct PRESPsReaderStatistics {
    /* peak number of samples stored in reader queue */
    RTI_UINT32 entryCountPeak;
    /* peak number of matched remote writers */
    RTI_UINT32 remoteWriterCountPeak;
    /* number of samples dropped from reader-side content filtering */
    RTI_UINT32 contentFilterDropCount;
    /* number of samples dropped from time-based filtering */
    RTI_UINT32 timeBasedFilterDropCount;
};


#define PRES_PS_READER_STATISTICS_INITIALIZER { \
    0, /* entryCountPeak */ \
    0, /* remoteWriterCountPeak */ \
    0, /* contentFilterDropCount */ \
    0 /* timeBasedFilterDropCount */ \
}

struct PRESPsReaderLocalReaderStatistics {
    struct PRESPsReaderStatistics presStats;
    struct COMMENDReaderServiceLocalReaderStatistics commendStats;
};


#define PRES_PS_READER_LOCAL_READER_STATISTICS_INITIALIZER { \
PRES_PS_READER_STATISTICS_INITIALIZER, \
COMMEND_READER_SERVICE_LOCAL_READER_STATISTICS_INITIALIZER \
}

struct PRESPsReaderMatchedWriterStatistics {
    struct COMMENDReaderServiceMatchedWriterStatistics commendStats;
};


#ifdef __cplusplus
    }	/* extern "C" */
#endif

#endif /* pres_readerStatistics_h */
