/*
 * @(#)pres_psReaderQueue_impl.h    generated by: makeheader    Mon Dec  3 23:08:14 2007
 *
 *		built from:	psReaderQueue_impl.ifc
 */

#ifndef pres_psReaderQueue_impl_h
#define pres_psReaderQueue_impl_h


#ifdef __cplusplus
    extern "C" {
#endif



#define PRESPsReaderQueue_pruneLifespanExpiredEntries(me, now,      \
        requiredEntryCount, readConditionState)                     \
    (PRESPsReaderQueue_pruneAndUpdate(me, now, requiredEntryCount,  \
        RTI_FALSE, NULL, PRES_INSTANCE_STATE_INVALID, NULL, readConditionState))



#ifdef __cplusplus
    }	/* extern "C" */
#endif

#endif /* pres_psReaderQueue_impl_h */
