/*
 * @(#)pres_participant.h    generated by: makeheader    Mon Dec  3 23:08:14 2007
 *
 *		built from:	participant.ifc
 */

#ifndef pres_participant_h
#define pres_participant_h


 #ifndef osapi_type_h
    #include "osapi/osapi_type.h"
 #endif
 #ifndef osapi_ntptime_h
    #include "osapi/osapi_ntptime.h"
 #endif
 #ifndef reda_sequenceNumber_h
    #include "reda/reda_sequenceNumber.h"
 #endif
 #ifndef netio_common_h
    #include "netio/netio_common.h"
 #endif
 #ifndef mig_rtps_h
    #include "mig/mig_rtps.h"
 #endif
 #ifndef commend_activeFacade_h
    #include "commend/commend_activeFacade.h"
 #endif
 #ifndef pres_dll_h
    #include "pres/pres_dll.h"
 #endif
 #ifndef pres_common_h
    #include "pres/pres_common.h"
 #endif

#ifdef __cplusplus
    extern "C" {
#endif


/*e \ingroup PRESParticipantModule
  maximum number of IP address count.  Separate for unicast vs. multicast.
 */
#define PRES_PARTICIPANT_IPADDRESS_COUNT_MAX   (4)

/*e \ingroup PRESParticipantModule
  maximum number of manager key.
 */
#define PRES_PARTICIPANT_MANAGER_KEY_COUNT_MAX         (4)


struct PRESParticipantDerivableQosPolicy {
    /*e
     * Whether the current value has been derived from the participant
     */
    RTIBool isDerivedFromParticipant;
};

struct PRESLocatorQosPolicy {
    /*e list size */
    int count;
    /*e */
    struct RTINetioLocator locatorList[PRES_PARTICIPANT_IPADDRESS_COUNT_MAX];
};


/*e \ingroup PRESParticipantModule
  Default locator Qos policy value
*/
  #define PRES_LOCATOR_QOS_POLICY_DEFAULT { \
       0, /* count */ \
       {RTI_NETIO_LOCATOR_INVALID, /* list */ \
        RTI_NETIO_LOCATOR_INVALID, \
	RTI_NETIO_LOCATOR_INVALID, \
        RTI_NETIO_LOCATOR_INVALID} \
  }

extern int PRESLocatorQosPolicy_compare(const void* l, const void* r);

struct PRESLocatorDerivableQosPolicy {
    /*e formalize the fact that this is derived from a derivable policy */
    struct PRESParticipantDerivableQosPolicy parent;
    /*e content of the policy itself */
    struct PRESLocatorQosPolicy policy;
};


/*e \ingroup PRESParticipantModule
  Default locator Qos policy value
*/
  #define PRES_LOCATOR_DERIVABLE_QOS_POLICY_DEFAULT { \
    {RTI_TRUE}, /* derived? */			      \
    PRES_LOCATOR_QOS_POLICY_DEFAULT                   \
  }

struct PRESParticipantParameter {
    /*e immutable */
    MIGRtpsProtocolVersion protocolVersion;
    /*e immutable */
    MIGRtpsVendorId vendorId;
    
    /*e immutable */
    struct PRESLocatorQosPolicy metatrafficUnicastLocator;
    /*e immutable */
    struct PRESLocatorQosPolicy metatrafficMulticastLocator;

    /*e immutable */
    struct PRESLocatorQosPolicy defaultUnicastLocator;
    /*e immutable */
    int managerKeyCount;
    /*e immutable */
    RTI_UINT32 managerKey[PRES_PARTICIPANT_MANAGER_KEY_COUNT_MAX];
    /*e @brief  The length of time a participant declaration should be
     *          considered valid.
     * 
     * This value is immutable.
     * 
     * @default Infinite. Not all users of this structure will supply a lease
     *          duration value; in that case, the record is valid
     *          indefinitely.
     */
    RTINtpTime leaseDuration;
    /*e mutable */
    struct PRESUserDataQosPolicy userData;
    /*e mutable */
    struct PRESPropertyQosPolicy propertyList;
    /*e immutable */
    struct PRESProductVersion productVersion;
    /*e immutable */
    PRESDiscoveryPluginPromiscuityKind pluginPromiscuityKind;
    /*e immutable */
    PRESBuiltinEndpointMask builtinEndpointMask;
    /*e immutable */
    struct PRESEntityNameQosPolicy participantName;
};


/*e \ingroup MIGRtpsParticipantModule
  Default manager key for participant parameter.
*/
#define PRES_PARTICIPANT_PARAMETER_MANAGER_KEY_INVALID (0)


/*e \ingroup PRESParticipantModule
  Default participant parameter value.

  The RTPS protocol version is defaulted to the latest (2.1) as implemented.
*/
  #define PRES_PARTICIPANT_PARAMETER_DEFAULT { \
       MIG_RTPS_PROTOCOL_VERSION, \
       MIG_RTPS_VENDOR_ID_UNKNOWN, \
       PRES_LOCATOR_QOS_POLICY_DEFAULT, \
       PRES_LOCATOR_QOS_POLICY_DEFAULT, \
       PRES_LOCATOR_QOS_POLICY_DEFAULT, \
       0, /* managerKeyCount */ \
       {PRES_PARTICIPANT_PARAMETER_MANAGER_KEY_INVALID, /* managerKey */ \
	PRES_PARTICIPANT_PARAMETER_MANAGER_KEY_INVALID, \
        PRES_PARTICIPANT_PARAMETER_MANAGER_KEY_INVALID, \
	PRES_PARTICIPANT_PARAMETER_MANAGER_KEY_INVALID},\
       RTI_NTP_TIME_MAX,  /* leaseDuration */           \
       {{0, 0, NULL}}, /* userData */                   \
       {{0, 0, NULL}}, /* propertyList */\
       PRES_PRODUCT_VERSION_DEFAULT, /* productVersion */\
       PRES_DISCOVER_MATCHING_REMOTE_ENTITIES_PROMISCUITY, /* pluginPromiscuityKind */\
       PRES_BUILTIN_ENDPOINT_NONE, /*builtinEndpointMask */\
       PRES_ENTITY_NAME_QOS_POLICY_DEFAULT /* participantName */\
       }

/*e \ingroup PRESParticipantModule
  Participant parameter value for the local participant.

  The RTPS protocol version is defaulted to the latest version (2.1)
*/
  #define PRES_PARTICIPANT_PARAMETER_LOCAL_DEFAULT { \
       MIG_RTPS_PROTOCOL_VERSION, \
       MIG_RTPS_VENDOR_ID_RTI, \
       PRES_LOCATOR_QOS_POLICY_DEFAULT, \
       PRES_LOCATOR_QOS_POLICY_DEFAULT, \
       PRES_LOCATOR_QOS_POLICY_DEFAULT, \
       0, /* managerKeyCount */ \
       {PRES_PARTICIPANT_PARAMETER_MANAGER_KEY_INVALID, /* managerKey */ \
	PRES_PARTICIPANT_PARAMETER_MANAGER_KEY_INVALID, \
        PRES_PARTICIPANT_PARAMETER_MANAGER_KEY_INVALID, \
	PRES_PARTICIPANT_PARAMETER_MANAGER_KEY_INVALID},\
       RTI_NTP_TIME_MAX,  /* leaseDuration */           \
       {{0, 0, NULL}}, /* userData */                   \
       {{0, 0, NULL, 0, 0, NULL}}, /* propertyList */\
       PRES_PRODUCT_VERSION_DEFAULT, /* productVersion */\
       PRES_DISCOVER_MATCHING_REMOTE_ENTITIES_PROMISCUITY, /* pluginPromiscuityKind */\
       PRES_BUILTIN_ENDPOINT_NONE, /*builtinEndpointMask */\
       PRES_ENTITY_NAME_QOS_POLICY_DEFAULT /* participantName */\
       }


#define PRES_PARTICIPANT_USER_DATA_MAXIMUM         (256)


#define PRES_PARTICIPANT_TOPIC_DATA_MAXIMUM         (256)


#define PRES_PARTICIPANT_PROPERTY_LIST_MAXIMUM      (32)


#define PRES_PARTICIPANT_PROPERTY_STRING_MAXIMUM      (1024)

struct PRESParticipant; /* forward declare to appease the compile */

struct PRESParticipantProperty {
    /* for single threaded applications */
    RTIBool isPassive;

    /*e property that is common to both local and remote participant */
    struct PRESParticipantParameter parameter;
    
    /*e
     * @brief   Whether or not unregistered remote participants that have
     *          lost their liveliness should be removed from the database.
     * 
     * If a previously-discovered remote participant has been unregistered
     * (PRESParticipant_unregisterRemoteParticipant) and has outlived its
     * declared liveliness lease duration, it will be removed from the
     * database if this flag is set to true. It will be left in place if
     * this flag is false.
     * 
     * @default RTI_TRUE
     */
    RTIBool purgeNotAliveParticipants;
    
    /*e
     * @brief   The maximum amount of time before this participant detects
     *          the loss of liveliness of a remote participant.
     * 
     * This value must be finite, but it will be ignored if
     * purgeNotAliveParticipants is false.
     * 
     * @default 100 seconds
     */
    struct RTINtpTime maxParticipantLivelinessLossDetectionPeriod;
    
    /*e property for active facade */
    struct COMMENDActiveFacadeProperty facadeProperty;

    /*e mutable */
    struct PRESEntityFactoryQosPolicy entityFactory;

    /*e string tables stores all the topic and typeName strings. */
    struct REDATableProperty stringTable;

    /*e flow controller stores all locally flow controllers. */
    struct REDATableProperty flowControllerTable;

    /*e local type table stores all locally created type. */
    struct REDATableProperty localTypeTable;

    /*e local topic table stores all locally created topic.
      This is the number of entries that is created in the table when it
      runs out of space */
    struct REDATableProperty localTopicTable;

    /*e topic type table stores all locally and remotely discovered topic
      and type pair. */
    struct REDATableProperty topicTypeTable;

    /*e content filtered table stored all content filters. */
    struct REDATableProperty contentFilteredTopicTable;

    /*e content filter type table stores all content filter types. */
    struct REDATableProperty contentFilterTable;

    /*e remote participant table stores all asserted remote participants. */
    struct REDATableProperty remoteParticipantTable;

    /*e table of ignored entities. */
    struct REDATableProperty ignoredEntityTable;

    /*e Maximum length for participant userData */
    int participantUserDataMaximumLength;
    /*e Maximum length for topicData */
    int topicDataMaximumLength;

    /*e Size of user object to be stored in particpiant */
    int participantUserObjectSize;
    /*e Alignment user object to be stored in particpiant */
    int participantUserObjectAlignment;
    /*e Size of user object to be stored in flow controller */
    int flowControllerUserObjectSize;
    /*e Alignment of user object to be stored in flow controller */
    int flowControllerUserObjectAlignment;
    /*e Size of user object to be stored in topic */
    int topicUserObjectSize;
    /*e Alignment of user object to be stored in topic */
    int topicUserObjectAlignment;
    /*e Size of user object to be stored in content filtered topic */
    int contentFilteredTopicUserObjectSize;
    /*e Alignment of user object to be stored in content filtered topic */
    int contentFilteredTopicUserObjectAlignment;
    /*e Type code max serialized size*/
    int typeCodeMaxSerializedLength;    
    /*e Content filter property max size*/
    int contentFilterPropertyMaxLength;
    /*e Maximum length for participant property list */
    int participantPropertyListMaximumLength; 
    /*e Maximum size of string area in property buffer */
    int participantPropertyStringMaximumLength;
};


/*e \ingroup PRESParticipantModule
  Default participant property value.
*/
  #define PRES_PARTICIPANT_PROPERTY_DEFAULT { \
      RTI_FALSE, /* isPasive */ \
      PRES_PARTICIPANT_PARAMETER_LOCAL_DEFAULT, \
      RTI_TRUE, /* purgeNotAliveParticipants */ \
      {100/*sec*/,0/*frac*/}, /*maxParticipantLivelinessLossDetectionPeriod*/\
      COMMEND_ACTIVE_FACADE_PROPERTY_DEFAULT, /* facadeProperty */ \
      {RTI_TRUE}, /* entityFactory: autoEnable == TRUE */ \
      /* stringTable */ \
      {{8,REDA_FAST_BUFFER_POOL_UNLIMITED,REDA_FAST_BUFFER_POOL_UNLIMITED}, 1},\
      /* flowControllerTable */ \
      {{4,REDA_FAST_BUFFER_POOL_UNLIMITED,REDA_FAST_BUFFER_POOL_UNLIMITED}, 1},\
      /* localTypeTable */ \
      {{8,REDA_FAST_BUFFER_POOL_UNLIMITED,REDA_FAST_BUFFER_POOL_UNLIMITED}, 1},\
      {{8, 1024, REDA_FAST_BUFFER_POOL_UNLIMITED}, 1}, /* localTopicTable */ \
      /* topicTypeTable */ \
      {{8,REDA_FAST_BUFFER_POOL_UNLIMITED,REDA_FAST_BUFFER_POOL_UNLIMITED}, 1},\
      /* contentFilteredTopicTable */ \
      {{4,REDA_FAST_BUFFER_POOL_UNLIMITED,REDA_FAST_BUFFER_POOL_UNLIMITED}, 1},\
      /* contentFilterTable */ \
      {{4,REDA_FAST_BUFFER_POOL_UNLIMITED,REDA_FAST_BUFFER_POOL_UNLIMITED}, 1},\
      {{8, 4096,REDA_FAST_BUFFER_POOL_UNLIMITED}, 1}, /*remoteParticipantTable*/\
      /* ignoredEntityTable */ \
      {{8,REDA_FAST_BUFFER_POOL_UNLIMITED,REDA_FAST_BUFFER_POOL_UNLIMITED}, 1},\
      PRES_PARTICIPANT_USER_DATA_MAXIMUM, /* participantUserDataMaximumLength */\
      PRES_PARTICIPANT_TOPIC_DATA_MAXIMUM, /* topicDataMaximumLength */ \
      0, /* flowControllerUserObjectSize */ \
      0, /* flowControllerUserObjectAlignment */ \
      0, /* particpiantUserObjectSize */ \
      0, /* particpiantUserObjectAlignment */ \
      0, /* topicUserObjectSize */ \
      0, /* topicUserObjectAlignment */ \
      0, /* contentFilteredTopicUserObjectSize */ \
      0, /* contentFilteredTopicUserObjectAlignment */ \
      1024,  /* typeCodeMaxSerializedLength */\
      PRES_CONTENT_FILTER_PROPERTY_LEN_MAX, /* content filter property max length */\
      PRES_PARTICIPANT_PROPERTY_LIST_MAXIMUM, /* participantPropertyListMaximumLength */\
      PRES_PARTICIPANT_PROPERTY_STRING_MAXIMUM /* participantPropertyStringMaximumLength */\
}

struct PRESRemoteParticipantProperty {
    /*e derived from participant parameter */
    struct PRESParticipantParameter parameter;
    /*e counter that indicates if there is a change to the entities in the
      remote participant */
    struct REDASequenceNumber lastSn;
};


/*e \ingroup PRESParticipantModule
  Default value for remote participant property.
*/
  #define PRES_REMOTE_PARTICIPANT_PROPERTY_DEFAULT {         \
      PRES_PARTICIPANT_PARAMETER_DEFAULT,                    \
      REDA_SEQUENCE_NUMBER_UNKNOWN                           } 

struct REDAWorker;

struct PRESTopic;

struct PRESTopicListener;

typedef void
(*PRESTopicListenerOnInconsistentTopicCallback)(
    const struct PRESTopicListener *listener, struct PRESTopic *topic,
    const struct PRESInconsistentTopicStatus *status,
    struct REDAWorker *worker);

struct PRESTopicListener {
    PRESTopicListenerOnInconsistentTopicCallback onInconsistentTopic;
};

struct PRESParticipantListener {
    struct PRESTopicListener topicListener;
};

struct PRESParticipantConfigListener;

typedef void
(*PRESParticipantConfigListenerOnManualLivelinessAssertedCallback)(
    const struct PRESParticipantConfigListener *me,
    struct REDAWorker *worker);

typedef void
(*PRESParticipantConfigListenerOnAutomaticLivelinessRateChangedCallback)(
    const struct PRESParticipantConfigListener *me,
    const struct RTINtpTime *leastDuration,
    struct REDAWorker *worker);

typedef void
(*PRESParticipantConfigListenerOnAfterRemoteParticipantCreationCallback)(
    const struct PRESParticipantConfigListener *me,
    const MIGRtpsParticipantId *remoteParticipantId,
    const struct PRESRemoteParticipantProperty *property,
    struct REDAWorker *worker);

typedef void
(*PRESParticipantConfigListenerOnAfterRemoteParticipantDestructionCallback)(
    const struct PRESParticipantConfigListener *me,
    const MIGRtpsParticipantId *remoteParticipantId,
    struct REDAWorker *worker);

struct PRESParticipantConfigListener {
    PRESParticipantConfigListenerOnManualLivelinessAssertedCallback
    onManualLivelinessAsserted;
    PRESParticipantConfigListenerOnAutomaticLivelinessRateChangedCallback
    onAutomaticLivelinessRateChanged;
    PRESParticipantConfigListenerOnAfterRemoteParticipantCreationCallback
        onAfterRemoteParticipantCreation;
    PRESParticipantConfigListenerOnAfterRemoteParticipantDestructionCallback
        onAfterRemoteParticipantDestruction;
};

struct PRESLocalParticipantConfigListener;

typedef void
(*PRESLocalParticipantConfigListenerOnAfterLocalParticipantEnabledCallback)(
    const struct PRESLocalParticipantConfigListener *me,
    const struct MIGRtpsGuid *guid,
    const struct PRESParticipantProperty *property,
    struct REDAWorker *worker);

typedef void
(*PRESLocalParticipantConfigListenerOnAfterLocalParticipantPropertyChangedCallback)(
    const struct PRESLocalParticipantConfigListener *me,
    const struct MIGRtpsGuid *guid,
    const struct PRESParticipantProperty *newProp,
    struct REDAWorker *worker);

typedef void
(*PRESLocalParticipantConfigListenerOnBeforeLocalParticipantDestructionCallback)(
    const struct PRESLocalParticipantConfigListener *me,
    const struct MIGRtpsGuid *guid,
    struct REDAWorker *worker);

typedef void
(*PRESLocalParticipantConfigListenerOnAfterLocalParticipantDestructionCallback)(
    const struct PRESLocalParticipantConfigListener *me,
    const struct MIGRtpsGuid *guid,
    struct REDAWorker *worker);

typedef void
(*PRESLocalParticipantConfigListenerOnBeforeRemoteParticipantIgnoredCallback)(
    const struct PRESLocalParticipantConfigListener *me,
    const struct MIGRtpsGuid *guid,
    struct REDAWorker *worker);

struct PRESLocalParticipantConfigListener {
    PRESLocalParticipantConfigListenerOnAfterLocalParticipantEnabledCallback
        onAfterLocalParticipantEnabled;
    PRESLocalParticipantConfigListenerOnAfterLocalParticipantPropertyChangedCallback
        onAfterLocalParticipantPropertyChanged;
    PRESLocalParticipantConfigListenerOnBeforeLocalParticipantDestructionCallback
        onBeforeLocalParticipantDestruction;
    PRESLocalParticipantConfigListenerOnAfterLocalParticipantDestructionCallback
        onAfterLocalParticipantDestruction;
    PRESLocalParticipantConfigListenerOnBeforeRemoteParticipantIgnoredCallback
        onBeforeRemoteParticipantIgnored;
};

struct PRESRemoteParticipantConfigListener;

typedef void
(*PRESRemoteParticipantConfigListenerOnAfterRemoteParticipantCreationCallback)(
    const struct PRESRemoteParticipantConfigListener *me,
    const MIGRtpsParticipantId *remoteParticipantId, /*RTPS.2.0*/
    const struct PRESRemoteParticipantProperty *property,
    struct REDAWorker *worker);

typedef void
(*PRESRemoteParticipantConfigListenerOnAfterRemoteParticipantDestructionCallback)(
    const struct PRESRemoteParticipantConfigListener *me,
    const MIGRtpsParticipantId *remoteParticipantId, /*RTPS.2.0*/
    struct REDAWorker *worker);

typedef void
(*PRESRemoteParticipantConfigListenerOnAfterRemoteParticipantPropertyChangedCallback)(
    const struct PRESRemoteParticipantConfigListener *me,
    const MIGRtpsParticipantId *remoteParticipantId, /*RTPS.2.0*/
    const struct PRESRemoteParticipantProperty *newProp,
    struct REDAWorker *worker);

struct PRESRemoteParticipantConfigListener {
    PRESRemoteParticipantConfigListenerOnAfterRemoteParticipantCreationCallback
        onAfterRemoteParticipantCreation;
    PRESRemoteParticipantConfigListenerOnAfterRemoteParticipantDestructionCallback
    onAfterRemoteParticipantDestruction;
    PRESRemoteParticipantConfigListenerOnAfterRemoteParticipantPropertyChangedCallback
    onAfterRemoteParticipantPropertyChanged;
};

struct PRESParticipantEntityFinalizeListener;

typedef void
(*PRESParticipantEntityFinalizeListenerOnBeforeTopicFinalizeFnc)(
    void* topicFinalizeParam,
    void* userObject, struct REDAWorker *worker);

typedef void
(*PRESParticipantEntityFinalizeListenerOnBeforeContentFilteredTopicFinalizeFnc)(
    void* contentFilteredTopicFinalizeParam,
    void* userObject, struct REDAWorker *worker);

typedef void
(*PRESParticipantEntityFinalizeListenerOnBeforeFlowControllerFinalizeFnc)(
    void* flowControllerFinalizeParam,
    void* userObject, struct REDAWorker *worker);

struct PRESParticipantEntityFinalizeListener {
    PRESParticipantEntityFinalizeListenerOnBeforeTopicFinalizeFnc
        onBeforeTopicFinalizeFnc;
    void* topicFinalizeParam;

    PRESParticipantEntityFinalizeListenerOnBeforeContentFilteredTopicFinalizeFnc
        onBeforeContentFilteredTopicFinalizeFnc;
    void* contentFilteredTopicFinalizeParam;

    PRESParticipantEntityFinalizeListenerOnBeforeFlowControllerFinalizeFnc
        onBeforeFlowControllerFinalizeFnc;
    void* flowControllerFinalizeParam;
};

struct REDADatabase;

struct REDAExclusiveArea;

struct RTIClock;

extern PRESDllExport
struct PRESParticipant * PRESParticipant_new(
    const struct MIGRtpsGuid *guid,
    struct RTINetioConfigurator* configuratorIn,
    struct REDAWorkerFactory *workerFactory,
    struct RTIEventActiveDatabase *database, struct RTIClock *clock,
    struct REDAExclusiveArea *tableEa,
    struct REDAExclusiveArea *recordEa,
    const struct COMMENDActiveFacadeThreadListener *threadListener,
    const struct PRESParticipantEntityFinalizeListener *finalizeListener,
    const struct PRESParticipantProperty *property,
    const struct PRESParticipantListener *listener,
    PRESStatusKindMask listenerMask,
    struct RTIOsapiThreadFactory *recv_thread_factory,
    struct RTIOsapiThreadFactory *event_thread_factory,
    struct RTIOsapiThreadFactory *asynch_pub_thread_factory,
    struct REDAWorker *worker);

extern PRESDllExport
RTIBool PRESParticipant_enable(
    struct PRESParticipant *me,
    RTIBool *autoenableContainedEntities,
    const struct PRESLocatorQosPolicy *defaultUnicastLocator,
    const struct PRESLocatorQosPolicy *metatrafficUnicastLocator,
    const struct PRESLocatorQosPolicy *metatrafficMulticastLocator,
    struct REDAWorker *worker);

extern PRESDllExport
RTIBool PRESParticipant_postEnable(
    struct PRESParticipant *me,
    struct REDAWorker *worker);

extern PRESDllExport
RTIBool PRESParticipant_enableAllEntities(struct PRESParticipant *me,
					  int *failReason,
					  struct REDAWorker *worker);

extern PRESDllExport
RTIBool PRESParticipant_destroyAllEntities(struct PRESParticipant *me,
					   int *failReason,
					   struct REDAWorker *worker);

extern PRESDllExport
RTIBool PRESParticipant_isEnabled(struct PRESParticipant *me);

extern PRESDllExport void
PRESParticipant_getInstanceHandle(
    struct PRESParticipant *me,
    struct PRESInstanceHandle *handle);

extern PRESDllExport RTIBool
PRESParticipant_containsEntity(
    struct PRESParticipant *me,
    const struct MIGRtpsGuid *guid);

extern PRESDllExport
RTIBool PRESParticipant_hasTopic(struct PRESParticipant *me,
				 struct REDAWorker *worker);

extern PRESDllExport
RTIBool PRESParticipant_preShutdown(
    struct PRESParticipant *me,
    struct REDAWorker *worker);

extern PRESDllExport
RTIBool PRESParticipant_preShutdownWakeup(struct PRESParticipant *me,
					  int *failReason,
					  struct REDAWorker *worker);

extern PRESDllExport
RTIBool PRESParticipant_shutdown(struct PRESParticipant *me,
				 int *failReason,
				 struct REDAWorker *worker);

extern PRESDllExport
RTIBool PRESParticipant_delete(struct PRESParticipant *me,
			       int *failReason,
			       struct REDAWorker *worker);

struct PRESService;

extern PRESDllExport
RTIBool PRESParticipant_assertService(struct PRESParticipant *me,
				      PRESServiceId serviceId,
				      struct PRESService *service,
				      struct REDAWorker *worker);

extern PRESDllExport
RTIBool PRESParticipant_removeService(struct PRESParticipant *me,
				      int *failReason,
				      PRESServiceId serviceId,
				      struct REDAWorker *worker);

struct PRESTypePlugin;

extern PRESDllExport
RTIBool PRESParticipant_registerType(struct PRESParticipant *me,
				     int *failReason,
				     const struct PRESTypePlugin *typePlugin,
				     const char *typeName,
				     struct REDAWorker *worker);

struct PRESTopic;

struct PRESContentFilteredTopic;

struct PRESContentFilterType;

struct PRESTopicProperty;

extern PRESDllExport
struct PRESTopic* PRESParticipant_createTopic(
    struct PRESParticipant *me,
    int *failReason,
    RTIBool *autoenableContainedEntities,
    const char *topicName,
    const char *typeName,
    MIGRtpsObjectId oid,
    struct PRESTopicProperty *property,
    const struct PRESTopicListener *listener,
    PRESStatusKindMask listenerMask,
    struct REDAWorker *worker);

extern PRESDllExport
RTIBool PRESParticipant_destroyTopic(
    struct PRESParticipant *me,
    int *failReason,
    struct PRESTopic *topic,
    struct REDAWorker *worker);

extern PRESDllExport
struct PRESTopic* PRESParticipant_lookupTopic(
    struct PRESParticipant *me,
    const char *topicName, struct REDAWorker *worker);

extern PRESDllExport
struct PRESTopic* PRESParticipant_findTopic(
    struct PRESParticipant *me,
    const char *topicName, 
    const struct RTINtpTime *timeout,
    struct REDAWorker *worker);

extern PRESDllExport
struct PRESEntity* PRESParticipant_lookupEntity(
    struct PRESParticipant *me,
    int *failReason,
    struct MIGRtpsGuid *guid,
    struct REDAWorker *worker);


#define PRESTopicTypeIterator REDACursor

extern PRESDllExport
RTIBool PRESParticipant_beginGetTopicTypes(
                              struct PRESParticipant *me,
                              struct PRESTopicTypeIterator **iter,
                              int *maxTopicTypes,
                              struct REDAWorker *worker);

extern PRESDllExport                                   
RTIBool PRESParticipant_endGetTopicTypes(
			      struct PRESParticipant *me,
                              struct PRESTopicTypeIterator *iter,
                              struct REDAWorker *worker);

extern PRESDllExport
RTIBool PRESParticipant_getNextTopicType(
			      struct PRESParticipant *me,
			      int *failReason,
                              struct PRESTopicTypeIterator *iter,
			      struct PRESInstanceHandle *handle,
                              struct REDAWorker *worker);

extern PRESDllExport
RTIBool PRESParticipant_getTopicPropertyByHandle(
			      struct PRESParticipant *me,
			      int *failReason,
			      struct PRESTopicProperty *property,
			      char *topicName, int topicMaxLength,
			      char *typeName, int typeMaxLength,
			      const struct PRESInstanceHandle *handle,
                              struct REDAWorker *worker);

extern PRESDllExport
RTIBool PRESParticipant_ignoreTopicByHandle(
			      struct PRESParticipant *me,
			      int *failReason,
			      const struct PRESInstanceHandle *handle,
                              struct REDAWorker *worker);

extern PRESDllExport
RTIBool PRESParticipant_registerContentFilterType(
               struct PRESParticipant *me,
               int *failReason,
               const char *name,
               const PRESContentFilterCompile compile,
               const PRESContentFilterEvaluate evaluate,
               const PRESContentFilterEvaluate evaluateOnSerialized,
               const PRESContentFilterFinalize finalizeFunc,
               void *handle,
               struct REDAWorker *worker);

extern PRESDllExport
RTIBool PRESParticipant_unregisterContentFilterType(
               struct PRESParticipant *me,
               int *failReason,
	       const char *name,
               void **handle,
	       struct REDAWorker *worker);

struct REDAWeakReference;

extern PRESDllExport
RTIBool PRESParticipant_lookupContentFilterType(
    struct PRESParticipant *me,
    const char *name,
    PRESContentFilterCompile *compile,
    PRESContentFilterEvaluate *evaluate,
    PRESContentFilterEvaluate *evaluateOnSerialized,
    PRESContentFilterFinalize *finalizeFunc,
    void **handle,
    struct REDAWeakReference *filterWR,
    RTIBool update_refcount,
    struct REDAWorker *worker);

extern PRESDllExport
struct PRESContentFilteredTopic* PRESParticipant_createContentFilteredTopic(
    struct PRESParticipant *me,
    int *failReason,
    const char *name,
    struct PRESTopic *related_topic,
    const char *filter_expression,
    const char **filter_parameters,
    RTI_INT32 parameter_length,
    const char *filter_name,
    const struct PRESContentFilteredTopicProperty *property,
    struct REDAWorker *worker);

extern PRESDllExport
struct PRESContentFilteredTopicProperty PRESParticipant_getDefaultContentFilteredTopicProperty(void);

extern PRESDllExport
RTIBool PRESParticipant_destroyContentFilteredTopic(
    struct PRESParticipant *me,
    int *failReason,
    struct PRESContentFilteredTopic *topic,
    struct REDAWorker *worker);

extern PRESDllExport
struct PRESContentFilteredTopic* 
PRESParticipant_lookupContentFilteredTopic(
    struct PRESParticipant *me,
    const char *name,
    struct REDAWorker *worker);

extern PRESDllExport
RTIBool PRESParticipant_assertRemoteParticipant(
    struct PRESParticipant *me,
    int *failReason,
    const MIGRtpsParticipantId *remoteParticipantId, /*RTPS.2.0*/
    const struct PRESRemoteParticipantProperty *remoteParticipantProperty,
    struct REDAWorker *worker);

struct PRESLivelinessParameter;

extern PRESDllExport
RTIBool PRESParticipant_updateRemoteParticipantLiveliness(
    struct PRESParticipant *me,
    int *failReason,
    const MIGRtpsParticipantId *remoteParticipantId, /*RTPS.2.0*/
    RTIBool manualLivelinessUpdate,
    struct REDAWorker *worker);

extern PRESDllExport
RTIBool PRESParticipant_removeRemoteParticipant(
    struct PRESParticipant *me, int *failReason, 
    const MIGRtpsParticipantId *remoteParticipantId, /*RTPS.2.0*/
    struct REDAWorker *worker);

extern PRESDllExport
RTIBool PRESParticipant_unregisterRemoteParticipant(
    struct PRESParticipant *me,
    int *failReason,
    const MIGRtpsParticipantId *remoteParticipantId,
    struct REDAWorker *worker);


#define PRESRemoteParticipantIterator REDACursor

extern PRESDllExport
RTIBool PRESParticipant_beginGetRemoteParticipants(
                              struct PRESParticipant *me,
                              struct PRESRemoteParticipantIterator **iter,
                              int *maxRemoteParticipants,
                              struct REDAWorker *worker);

extern PRESDllExport                                   
RTIBool PRESParticipant_endGetRemoteParticipants(
			      struct PRESParticipant *me,
                              struct PRESRemoteParticipantIterator *iter,
                              struct REDAWorker *worker);

extern PRESDllExport
RTIBool PRESParticipant_getNextRemoteParticipant(
			      struct PRESParticipant *me,
			      int *failReason,
                              struct PRESRemoteParticipantIterator *iter,
                              MIGRtpsParticipantId *remoteParticipantId, /*RTPS.2.0*/
                              struct REDAWorker *worker);

struct PRESGroupListener;

extern PRESDllExport
struct PRESGroup* PRESParticipant_createGroup(
    struct PRESParticipant *me, int *failReason,
    RTIBool *autoenableContainedEntities, PRESServiceId serviceId,
    MIGRtpsObjectId oid, 
    const struct PRESGroupProperty *property,
    const struct PRESGroupListener *listener,
    PRESStatusKindMask listenerMask,
    struct REDAExclusiveArea *ea,
    struct REDAWorker *worker);

extern PRESDllExport
RTIBool PRESParticipant_destroyGroup(struct PRESParticipant *me,
				     int *failReason,
				     struct PRESGroup *group,
				     struct REDAWorker *worker);

struct PRESLocalEndpointListener;

struct PRESLocalEndpointStatisticsListener;

extern PRESDllExport
struct PRESLocalEndpoint* PRESParticipant_createLocalEndpoint(
    struct PRESParticipant *me,
    int *failReason,
    RTIBool *autoenableContainedEntities,
    struct PRESGroup *group,
    struct PRESTopic *topic,
    MIGRtpsObjectId oid,
    const struct PRESLocalEndpointProperty *property,
    const struct PRESLocalEndpointListener *listener, 
    PRESStatusKindMask listenerMask,
    struct REDAWorker *worker);

extern PRESDllExport
RTIBool PRESParticipant_destroyLocalEndpoint(
    struct PRESParticipant *me,
    int *failReason,
    struct PRESGroup *group,
    struct PRESLocalEndpoint *localEndpoint, struct REDAWorker *worker);

extern PRESDllExport
RTIBool PRESParticipant_assertRemoteEndpoint(
    struct PRESParticipant *me,
    int *failReason,
    PRESServiceId serviceId,
    const struct MIGRtpsGuid *guid, 
    const struct PRESRemoteEndpointProperty *property,
    struct REDAWorker *worker);

extern PRESDllExport
RTIBool PRESParticipant_removeRemoteEndpoint(
    struct PRESParticipant *me,
    int *failReason,
    PRESServiceId serviceId,
    const struct MIGRtpsGuid *guid, struct REDAWorker *worker);

extern PRESDllExport
RTIBool PRESParticipant_removeRemoteEndpointsOfRemoteParticipant(
    struct PRESParticipant *me, 
    const MIGRtpsParticipantId *remoteParticipantId, /*RTPS.2.0*/
    struct REDAWorker *worker);

extern PRESDllExport
RTIBool PRESParticipant_unregisterRemoteEndpointsOfRemoteParticipant(
    struct PRESParticipant *me,
    const MIGRtpsParticipantId *remoteParticipantId, /*RTPS.2.0*/
    struct REDAWorker *worker);

extern PRESDllExport
RTIBool PRESParticipant_removeRemoteEndpointsWithOid(
    struct PRESParticipant *me, MIGRtpsObjectId remoteOid,
    struct REDAWorker *worker);

extern PRESDllExport
RTIBool PRESParticipant_unregisterRemoteEndpoint(
    struct PRESParticipant *me,
    int *failReason,
    PRESServiceId serviceId,
    const struct MIGRtpsGuid *guid,
    struct REDAWorker *worker);

extern PRESDllExport 
PRESWord *PRESParticipant_getUserObject(struct PRESParticipant *me);

extern PRESDllExport
void* PRESEntity_getUserObject(struct PRESEntity *me);

extern PRESDllExport
MIGRtpsHostId PRESParticipant_getHostId(
    const struct PRESParticipant *me);

extern PRESDllExport
MIGRtpsAppId PRESParticipant_getAppId(
    const struct PRESParticipant *me);

extern PRESDllExport
MIGRtpsInstanceId PRESParticipant_getInstanceId(
    const struct PRESParticipant *me);

extern PRESDllExport
RTIBool PRESParticipant_setListener(
    struct PRESParticipant *me,
    const struct PRESParticipantListener *listener,
    PRESStatusKindMask mask, struct REDAWorker *worker);

extern PRESDllExport
const struct PRESParticipantListener* PRESParticipant_getListener(
    const struct PRESParticipant *me, struct REDAWorker *worker);

extern PRESDllExport
RTIBool PRESParticipant_getProperty(
    const struct PRESParticipant *me,
    struct PRESParticipantProperty *property,
    struct REDAWorker *worker);

extern PRESDllExport
RTIBool PRESParticipant_setProperty(
    struct PRESParticipant *me,
    int *failReason,
    const struct PRESParticipantProperty *property,
    struct REDAWorker *worker);

extern PRESDllExport
void PRESParticipant_getGuid(
    const struct PRESParticipant *me,
    struct MIGRtpsGuid *guid);

extern PRESDllExport
RTIBool PRESParticipant_setLocalParticipantConfigListener(
    struct PRESParticipant *me,
    const struct PRESLocalParticipantConfigListener *listener, 
    struct REDAWorker *worker);

extern PRESDllExport
const struct PRESLocalParticipantConfigListener *
PRESParticipant_getLocalParticipantConfigListener(
    const struct PRESParticipant *me, struct REDAWorker *worker);

extern PRESDllExport
RTIBool PRESParticipant_setParticipantConfigListener(
    struct PRESParticipant *me,
    const struct PRESParticipantConfigListener *listener,
    struct REDAWorker *worker
    );

extern PRESDllExport
RTIBool PRESParticipant_getRemoteParticipantProperty(
    const struct PRESParticipant *me,
    struct PRESRemoteParticipantProperty *property,
    const MIGRtpsParticipantId *remoteParticipantId, /*RTPS.2.0*/
    struct REDAWorker *worker);

extern PRESDllExport
RTIBool PRESParticipant_setRemoteParticipantConfigListener(
    struct PRESParticipant *me,
    const struct PRESRemoteParticipantConfigListener *listener, 
    struct REDAWorker *worker);

extern PRESDllExport
const struct PRESRemoteParticipantConfigListener *
PRESParticipant_getRemoteParticipantConfigListener(
    const struct PRESParticipant *me, struct REDAWorker *worker);

extern PRESDllExport
RTIBool PRESParticipant_setLocalEndpointConfigListener(
    struct PRESParticipant *me,
    PRESServiceId serviceId,
    const struct PRESLocalEndpointConfigListener *listener, 
    struct REDAWorker *worker);

extern PRESDllExport
RTIBool PRESParticipant_setLocalParticipantConfigListener(
    struct PRESParticipant *me,
    const struct PRESLocalParticipantConfigListener *listener,
    struct REDAWorker *worker);

extern PRESDllExport
const struct PRESLocalEndpointConfigListener *
PRESParticipant_getLocalEndpointConfigListener(
    const struct PRESParticipant *me,
    PRESServiceId serviceId, struct REDAWorker *worker);

extern PRESDllExport
RTIBool PRESParticipant_setRemoteEndpointConfigListener(
    struct PRESParticipant *me,
    PRESServiceId serviceId,
    const struct PRESRemoteEndpointConfigListener *listener, 
    struct REDAWorker *worker);

extern PRESDllExport
const struct PRESRemoteEndpointConfigListener *
PRESParticipant_getRemoteEndpointConfigListener(
    const struct PRESParticipant *me,
    PRESServiceId serviceId, struct REDAWorker *worker);

extern PRESDllExport
RTIBool PRESParticipant_assertLiveliness(
    struct PRESParticipant *me, struct REDAWorker *worker);

extern PRESDllExport
RTIBool PRESParticipant_refresh(
    struct PRESParticipant *me, struct REDAWorker *worker);

extern PRESDllExport
PRESStatusKind PRESParticipant_getStatusChanges(
    struct PRESParticipant *me, struct REDAWorker *worker);

extern PRESDllExport
const struct PRESTypePlugin *PRESParticipant_lookupTypePlugin(
    struct PRESParticipant *me, const char *typeName,
    struct REDAWorker *worker);

extern PRESDllExport
RTIBool PRESParticipant_ignoreRemoteParticipant(
    struct PRESParticipant *me,
    const struct MIGRtpsGuid* remoteParticipantGuidIn,
    struct REDAWorker *worker);

extern PRESDllExport
RTIBool PRESParticipant_ignoreRemoteEndpoint(
    struct PRESParticipant *me, PRESServiceId serviceId,
    const struct MIGRtpsGuid* remoteEndpointGuidIn, struct REDAWorker *worker);

extern PRESDllExport
struct COMMENDFacade* PRESParticipant_getFacade(struct PRESParticipant* me);

extern PRESDllExport void PRESParticipant_cleanup(struct PRESParticipant *me,
						  struct REDAWorker *worker);


#ifdef __cplusplus
    }	/* extern "C" */
#endif

  #include "pres/pres_participant_impl.h"

#endif /* pres_participant_h */
