/*
 * @(#)pres_psReaderWriter_impl.h    generated by: makeheader    Mon Dec  3 23:08:14 2007
 *
 *		built from:	psReaderWriter_impl.ifc
 */

#ifndef pres_psReaderWriter_impl_h
#define pres_psReaderWriter_impl_h


  #ifndef pres_service_h
    #include "pres/pres_service.h"
  #endif

#ifdef __cplusplus
    extern "C" {
#endif



/*---------------------------------------------------------------------------*/
#define PRESPsWriter_getUserObject(me) ((me)->parent.userObject)
#define PRESPsReader_getUserObject(me) ((me)->parent.userObject)
/*---------------------------------------------------------------------------*/

#define PRESPsWriter_isEnabled(me) \
    ((me)->parent.state == PRES_ENTITY_STATE_ENABLED)
#define PRESPsReader_isEnabled(me) \
    ((me)->parent.state == PRES_ENTITY_STATE_ENABLED)

/*---------------------------------------------------------------------------*/
#define PRESPsWriter_getProperty(me, p, worker)                          \
    (me)->_service->getLocalEndpointProperty((me)->_service, p, me, worker)

#define PRESPsWriter_setProperty(me, failReason, p, worker)                \
    (me)->_service->setLocalEndpointProperty((me)->_service, failReason, me, \
                                             p, worker)

/*---------------------------------------------------------------------------*/

#define PRESPsReader_getProperty(me, p, worker)                          \
    (me)->_service->getLocalEndpointProperty((me)->_service, p, me, worker)

#define PRESPsReader_setProperty(me, failReason, p, worker)                  \
    (me)->_service->setLocalEndpointProperty((me)->_service, failReason, me, \
                                             p, worker)

/*---------------------------------------------------------------------------*/

#define PRESPsWriter_getListener(me, worker)                          \
    (me)->_service->getLocalEndpointListener((me)->_service, me, worker)

#define PRESPsWriter_setListener(me, failReason, l, mask, worker)            \
    (me)->_service->setLocalEndpointListener((me)->_service, failReason, me, \
                                             l, mask, worker)

/*---------------------------------------------------------------------------*/

#define PRESPsReader_getListener(me, worker)                          \
    (me)->_service->getLocalEndpointListener((me)->_service, me, worker)

#define PRESPsReader_setListener(me, failReason, l, mask, worker)            \
    (me)->_service->setLocalEndpointListener((me)->_service, failReason, me, \
                                             l, mask, worker)

/*---------------------------------------------------------------------------*/

#define PRESPsReader_enable(me, fr, worker)                          \
    (me)->_service->enableLocalEndpoint((me)->_service, fr, me, worker)

#define PRESPsWriter_enable(me, fr, worker)                          \
    (me)->_service->enableLocalEndpoint((me)->_service, fr, me, worker)

/*---------------------------------------------------------------------------*/

#define PRESPsReader_getGuid(__me, __guid, __worker)                          \
    (*(__guid)) = (__me)->parent.guid

#define PRESPsWriter_getGuid(__me, __guid, __worker)                          \
    (*(__guid)) = (__me)->parent.guid

/*---------------------------------------------------------------------------*/

PRESDllExport RTIBool
PRESPsWriter_writeInternal(struct PRESPsWriter *writer, int *failReason,
                   MIGGeneratorEndian endian,
                   const struct PRESInstanceHandle * directedReaderHandle,
                   const struct PRESOriginalWriterInfo * originalWriterInfo,
                   const void *instanceData,
                   const struct PRESInstanceHandle *instanceHandle,
                   const struct RTINtpTime *sourceTimestamp,
                   struct REDAWorker *worker);

#define PRESPsWriter_write( \
    __me, __failReason, __data, __instanceHandle, __sourceTimestamp, __worker) \
    PRESPsWriter_writeInternal( \
        __me, __failReason, MIG_GENERATOR_ENDIAN_UNKNOWN, NULL, NULL, __data, __instanceHandle, __sourceTimestamp, __worker)
#define PRESPsWriter_writeEndian( \
    __me, __failReason, __endian, __data, __instanceHandle, __sourceTimestamp, __worker) \
    PRESPsWriter_writeInternal( \
        __me, __failReason, __endian, NULL, NULL, __data, __instanceHandle, __sourceTimestamp, __worker)

#define PRESPsWriter_writeDirected( \
    __me, __failReason, __directedReaderHandle, __data, __instanceHandle, __sourceTimestamp, __worker) \
    PRESPsWriter_writeInternal( \
        __me, __failReason, MIG_GENERATOR_ENDIAN_UNKNOWN, __directedReaderHandle, NULL, __data, __instanceHandle, __sourceTimestamp, __worker)
#define PRESPsWriter_writeDirectedEndian( \
    __me, __failReason, __endian, __directedReaderHandle, __data, __instanceHandle, __sourceTimestamp, __worker) \
    PRESPsWriter_writeInternal( \
        __me, __failReason, __endian, __directedReaderHandle, NULL, __data, __instanceHandle, __sourceTimestamp, __worker)

/*---------------------------------------------------------------------------*/

PRESDllExport RTIBool
PRESPsWriter_unregisterInstanceInternal(
    struct PRESPsWriter *writer, int* failReason,
    const struct PRESInstanceHandle *directedReaderHandle,
    const void *keyHolder,
    const struct PRESInstanceHandle *instanceHandle,
    const struct RTINtpTime* sourceTimestamp,
    struct REDAWorker *worker);

#define PRESPsWriter_unregisterInstance( \
    __me, __failReason, __keyHolder, __instanceHandle, __sourceTimestamp, __worker) \
    PRESPsWriter_unregisterInstanceInternal( \
        __me, __failReason, NULL, __keyHolder, __instanceHandle, __sourceTimestamp, __worker)

#define PRESPsWriter_unregisterInstanceDirected( \
    __me, __failReason, __directedReaderHandle, __keyHolder, __instanceHandle, __sourceTimestamp, __worker) \
    PRESPsWriter_unregisterInstanceInternal( \
        __me, __failReason, __directedReaderHandle, __keyHolder, __instanceHandle, __sourceTimestamp, __worker)

/*---------------------------------------------------------------------------*/

PRESDllExport RTIBool
PRESPsWriter_disposeInternal(struct PRESPsWriter *writer, int* failReasonOut,
           		     const struct PRESInstanceHandle *directedReaderHandle,
                             const struct PRESOriginalWriterInfo * originalWriterInfo,
                             const void *keyHolderIn,
                             const struct PRESInstanceHandle *instanceHandleIn,
                             const struct RTINtpTime *sourceTimestampIn,
                             struct REDAWorker *worker);

#define PRESPsWriter_dispose( \
    __me, __failReason, __keyHolder, __instanceHandle, __sourceTimestamp, __worker) \
    PRESPsWriter_disposeInternal( \
    __me, __failReason, NULL, NULL, __keyHolder, __instanceHandle, __sourceTimestamp, __worker)

#define PRESPsWriter_disposeDirected( \
    __me, __failReason, __directedReaderHandle, __keyHolder, __instanceHandle, __sourceTimestamp, __worker) \
    PRESPsWriter_disposeInternal( \
    __me, __failReason, __directedReaderHandle, NULL, __keyHolder, __instanceHandle, __sourceTimestamp, __worker)



#ifdef __cplusplus
    }	/* extern "C" */
#endif

#endif /* pres_psReaderWriter_impl_h */
