# -*- mode: ruby -*-
# vi: set ft=ruby :
#
# Copyright (C) 2016  Michael Tesch
#
# You may distribute under the terms of either the GNU General Public
# License or the Apache License, as specified in the LICENSE file.
#
# For more information, see the LICENSE file.
#
def gui?; !ENV.fetch('OVJ_VM_GUI', '').empty?; end
def ncpu; Integer(ENV.fetch('OVJ_VM_NCPU', '1')); end
def mem; Integer(ENV.fetch('OVJ_VM_MEM', "%d" % (ncpu * 1024))); end

Vagrant.configure("2") do |config|
  #config.vm.box = "ubuntu/xenial64"
  #config.vm.box_version = "v20160930.0.0"
  config.vm.box = "bento/ubuntu-16.04"
  config.vm.synced_folder '.', '/vagrant', disabled: true
  config.vm.provider "virtualbox" do |vb|
    vb.linked_clone = true
    vb.gui = gui?
    vb.memory = mem
    vb.cpus = ncpu
  end
  config.vm.post_up_message = "VM started with #{ncpu} cpus, #{mem} MB memory, and gui=#{gui?}"
  config.vm.provision "shell", inline: <<-SHELL
    export DEBIAN_FRONTEND=noninteractive
    set -e
    dpkg --add-architecture i386
    apt-get -qq update
    apt-get -qq -y dist-upgrade

    # these are needed to build
    apt-get install -y git scons g++ gfortran \
            lib32stdc++-5-dev libc6-dev-i386 libglu1-mesa-dev \
            libgsl-dev libtiff5-dev
    apt-get install -y libmotif-dev:i386 libx11-dev:i386 libxt-dev:i386

    # these are needed to install
    #apt-get install -y openjdk-8-jre
    apt-get install -y csh expect bc rsh-server tftpd mutt sharutils \
            gnome-power-manager gnome-terminal k3b kdiff3 rarpd \
            ghostscript imagemagick postgresql dos2unix zip cups \
            gnuplot enscript
    #debconf-set-selections <<< "postfix postfix/mailname string your.hostname.com"
    #debconf-set-selections <<< "postfix postfix/main_mailer_type string 'Internet Site'"
    apt-get install -y sendmail-cf

    chmod a+rw /var/run/postgresql

    echo "dash dash/sh boolean false" | debconf-set-selections
    dpkg-reconfigure dash

    apt-get install -y gdm
    #dpkg-reconfigure gdm
  SHELL
end
