/*
 * @(#)dds_cpp_data_TTypeSupport.h    generated by: makeheader    Mon Dec  3 23:08:35 2007
 *
 *		built from:	TTypeSupport.cxx
 */

#ifndef dds_cpp_data_TTypeSupport_h
#define dds_cpp_data_TTypeSupport_h

#endif /* dds_cpp_data_TTypeSupport_h */
