/*
 * @(#)commend_beReaderService.h    generated by: makeheader    Mon Dec  3 23:08:09 2007
 *
 *		built from:	beReaderService.ifc
 */

#ifndef commend_beReaderService_h
#define commend_beReaderService_h


  #ifndef reda_worker_h
    #include "reda/reda_worker.h"
  #endif
  #ifndef reda_weakReference_h
    #include "reda/reda_weakReference.h"
  #endif
  #ifndef reda_database_h
    #include "reda/reda_database.h"
  #endif
  #ifndef netio_common_h
    #include "netio/netio_common.h"
  #endif
  #ifndef mig_rtps_h
    #include "mig/mig_rtps.h"
  #endif
  #ifndef commend_dll_h
    #include "commend/commend_dll.h"
  #endif
  #ifndef commend_readerService_h
    #include "commend/commend_readerService.h"
  #endif

#ifdef __cplusplus
    extern "C" {
#endif

struct REDADatabase;

struct COMMENDFacade;

struct COMMENDBeReaderService;

extern COMMENDDllExport struct COMMENDBeReaderService *
COMMENDBeReaderService_new(
    struct REDADatabase *db, struct COMMENDFacade *facade,
    const struct COMMENDReaderServiceProperty *property,
    struct REDAExclusiveArea *ea, struct REDAWorker *worker);


#ifdef __cplusplus
    }	/* extern "C" */
#endif

#endif /* commend_beReaderService_h */
