/*
 * @(#)commend_srReaderService_impl.h    generated by: makeheader    Mon Dec  3 23:08:09 2007
 *
 *		built from:	srReaderService_impl.ifc
 */

#ifndef commend_srReaderService_impl_h
#define commend_srReaderService_impl_h


#ifdef __cplusplus
    extern "C" {
#endif



#define COMMEND_SR_READER_SERVICE_RECORD_EXCLUSIVE_AREA_LEVEL (4)
#define COMMEND_SR_READER_SERVICE_TABLE_EXCLUSIVE_AREA_LEVEL (2)



#ifdef __cplusplus
    }	/* extern "C" */
#endif

#endif /* commend_srReaderService_impl_h */
