/*
 * @(#)commend_facade_impl.h    generated by: makeheader    Mon Dec  3 23:08:09 2007
 *
 *		built from:	facade_impl.ifc
 */

#ifndef commend_facade_impl_h
#define commend_facade_impl_h

extern COMMENDDllVariable struct REDAObjectPerWorker *COMMEND_STAT_PER_WORKER;



#ifndef clock_interface_h
  #include "clock/clock_interface.h"
#endif
#ifndef reda_worker_h
  #include "reda/reda_worker.h"
#endif
#ifndef event_jobDispatcher_h
  #include "event/event_jobDispatcher.h"
#endif

#ifdef __cplusplus
    extern "C" {
#endif



/* ---------------------------------------------------------------- */
#define COMMENDWorkerStat_getStorageLazy(statPtr, worker) \
    ( *(statPtr) = (struct COMMENDWorkerStat *)           \
        REDAWorker_assertObject(worker, COMMEND_STAT_PER_WORKER) )

#define COMMENDFacadeProperty_verify(me)                       \
    ( ((me)->hostId != 0) && ((me)->appId != 0) ) 


#define COMMENDFacade_postEvent(me, time, snooze, listener, listenerStorage, \
                                bytesToCompareInReuse) \
    (me)->_eventGenerator->postEvent((me)->_eventGenerator,                  \
                                     time, snooze, listener, listenerStorage,\
                                     bytesToCompareInReuse)

#define COMMENDFacade_removeTokenBucket(me, tokenBucket, worker) \
    RTIEventJobDispatcher_removeTokenBucket((me)->_jobDispatcher, tokenBucket, worker)

/* forward declaration (facade.peer.h) */
int COMMENDWriterServiceJobDispatcherAgentCompareFnc(const void *left, const void *right);
/* forward declaration (facade.peer.h) */
int COMMENDWriterServiceJobDispatcherJobPriorityCompareFnc(const void *left, const void *right);

/* agentCompareFnc = NULL b/c unique agents are checked at the 'assert remote reader' level */
/* priorityCompareFnc = NULL to achieve RR */
/* bucketStorage = NULL b/c unique buckets are checked at PRES 'create flow controller' level */
#define COMMENDFacade_assertTokenBucketRR(me, property, worker) \
    RTIEventJobDispatcher_assertTokenBucket((me)->_jobDispatcher, \
        NULL /*agentCompareFnc*/, NULL /*priorityCompareFnc*/, \
        NULL /*bucketStorage*/, property, worker)

/* agentCompareFnc = NULL b/c unique agents are checked at the 'assert remote reader' level */
/* bucketStorage = NULL b/c unique buckets are checked at PRES 'create flow controller' level */
#define COMMENDFacade_assertTokenBucketEDF(me, property, worker) \
    RTIEventJobDispatcher_assertTokenBucket((me)->_jobDispatcher, \
        NULL /*agentCompareFnc*/, COMMENDWriterServiceJobDispatcherJobPriorityCompareFnc, \
        NULL /*bucketStorage*/, property, worker)

#define COMMENDFacade_getTokenBucketProperty(me, tokenBucket, property, worker) \
    RTIEventJobDispatcher_getTokenBucketProperty((me)->_jobDispatcher, tokenBucket, property, worker)

#define COMMENDFacade_setTokenBucketProperty(me, tokenBucket, property, worker) \
    RTIEventJobDispatcher_setTokenBucketProperty((me)->_jobDispatcher, tokenBucket, property, worker)

#define COMMENDFacade_addTokensToBucket(me, tokenBucket, worker) \
    RTIEventJobDispatcher_addTokens((me)->_jobDispatcher, tokenBucket, worker)

#define COMMENDFacade_assertThread(me, eaBeforeAgentFncs, threadStorage, property, worker) \
    RTIEventJobDispatcher_assertThread((me)->_jobDispatcher, eaBeforeAgentFncs, threadStorage, property, worker)

#define COMMENDFacade_removeThread(me, executionThread, worker) \
    RTIEventJobDispatcher_removeThread((me)->_jobDispatcher, executionThread, worker)

#define COMMENDFacade_getTime(me, now)                                 \
    ((me)->_clock->getTime((me)->_clock, now))



#ifdef __cplusplus
    }	/* extern "C" */
#endif

#endif /* commend_facade_impl_h */
