/*
 * @(#)commend_writerStatistics.h    generated by: makeheader    Mon Dec  3 23:08:09 2007
 *
 *		built from:	writerStatistics.ifc
 */

#ifndef commend_writerStatistics_h
#define commend_writerStatistics_h



#include "osapi/osapi_type.h"

#ifndef commend_dll_h
    #include "commend/commend_dll.h"
#endif

#ifdef __cplusplus
    extern "C" {
#endif

struct COMMENDWriterServiceLocalWriterStatistics {
    RTI_UINT32 samplesSentCount;
    RTI_UINT32 samplesSentBytes;
    RTI_UINT32 samplesFilteredCount;
    RTI_UINT32 samplesFilteredBytes;
    RTI_UINT32 heartbeatsSentCount;
    RTI_UINT32 heartbeatsSentBytes;
    RTI_UINT32 samplesResentCount;
    RTI_UINT32 samplesResentBytes;
    RTI_UINT32 acksReceivedCount;
    RTI_UINT32 acksReceivedBytes;
    RTI_UINT32 nacksReceivedCount;
    RTI_UINT32 nacksReceivedBytes;
    RTI_UINT32 gapsSentCount;
    RTI_UINT32 gapsSentBytes;
    RTI_UINT32 samplesRejectedCount;
};


#define COMMEND_WRITER_SERVICE_LOCAL_WRITER_STATISTICS_INITIALIZER { \
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, \
0, 0, 0, 0, 0 \
}

struct COMMENDWriterServiceMatchedReaderStatistics {
    RTI_UINT32 samplesSentCount;
    RTI_UINT32 samplesSentBytes;
    RTI_UINT32 samplesFilteredCount;
    RTI_UINT32 samplesFilteredBytes;
    RTI_UINT32 heartbeatsSentCount;
    RTI_UINT32 heartbeatsSentBytes;
    RTI_UINT32 samplesResentCount;
    RTI_UINT32 samplesResentBytes;
    RTI_UINT32 acksReceivedCount;
    RTI_UINT32 acksReceivedBytes;
    RTI_UINT32 nacksReceivedCount;
    RTI_UINT32 nacksReceivedBytes;
    RTI_UINT32 gapsSentCount;
    RTI_UINT32 gapsSentBytes;
    RTI_UINT32 samplesRejectedCount;
};


#define COMMEND_WRITER_SERVICE_MATCHED_READER_STATISTICS_INITIALIZER { \
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, \
0, 0, 0, 0, 0 \
}

struct COMMENDWriterServiceMatchedDestinationStatistics {
    RTI_UINT32 samplesSentCount;
    RTI_UINT32 samplesSentBytes;
    RTI_UINT32 samplesFilteredCount;
    RTI_UINT32 samplesFilteredBytes;
    RTI_UINT32 heartbeatsSentCount;
    RTI_UINT32 heartbeatsSentBytes;
    RTI_UINT32 samplesResentCount;
    RTI_UINT32 samplesResentBytes;
    RTI_UINT32 gapsSentCount;
    RTI_UINT32 gapsSentBytes;
};


#define COMMEND_WRITER_SERVICE_MATCHED_DESTINATION_STATISTICS_INITIALIZER { \
0, 0, 0, 0, 0, 0, 0, 0, 0, 0 \
}

typedef RTI_UINT32 COMMENDWriterStatisticsChangedBitmap;


#define COMMEND_WRITER_STATISTICS_NO_FLAG (0x00000000)
#define COMMEND_WRITER_STATISTICS_GAP_SENT_FLAG (0x00000001 << 0)
#define COMMEND_WRITER_STATISTICS_SAMPLE_SENT_FLAG (0x00000001 << 1)
#define COMMEND_WRITER_STATISTICS_SAMPLE_FILTERED_FLAG (0x00000001 << 2)
#define COMMEND_WRITER_STATISTICS_SAMPLE_RESENT_FLAG (0x00000001 << 3)
#define COMMEND_WRITER_STATISTICS_HEARTBEAT_SENT_FLAG (0x00000001 << 4)
#define COMMEND_WRITER_STATISTICS_ACK_RECEIVED_FLAG (0x00000001 << 5)
#define COMMEND_WRITER_STATISTICS_NACK_RECEIVED_FLAG (0x00000001 << 6)
#define COMMEND_WRITER_STATISTICS_SAMPLE_REJECTED_FLAG (0x00000001 << 7)

extern COMMENDDllExport 
void COMMENDWriterService_addLocalWriterStatistics(
    struct COMMENDWriterServiceLocalWriterStatistics *sum,
    struct COMMENDWriterServiceLocalWriterStatistics *in1,
    struct COMMENDWriterServiceLocalWriterStatistics *in2);

extern COMMENDDllExport 
void COMMENDWriterService_addMatchedReaderStatistics(
    struct COMMENDWriterServiceMatchedReaderStatistics *sum,
    struct COMMENDWriterServiceMatchedReaderStatistics *in1,
    struct COMMENDWriterServiceMatchedReaderStatistics *in2);

extern COMMENDDllExport 
void COMMENDWriterService_addMatchedDestinationStatistics(
    struct COMMENDWriterServiceMatchedDestinationStatistics *sum,
    struct COMMENDWriterServiceMatchedDestinationStatistics *in1,
    struct COMMENDWriterServiceMatchedDestinationStatistics *in2);


#ifdef __cplusplus
    }	/* extern "C" */
#endif

    #include "commend/commend_writerStatistics_impl.h"

#endif /* commend_writerStatistics_h */
